    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Iinicio, Opciones Principales...</strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 



<div class="row">
    <div class="col-md-3"><h4>
        <span class="form-control label label-info">Enlaces Directos al Sistema de Gestion de Personal :</span></h4>
        <hr>
        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>personal/personal" title="Enlace Directo a Personal SIGALEN" target="_self">&#8226; Personal Registrado en SIGALEN </a>: Personal SIGALEN, listado de personal  en la tabla Empleados (SIGALEN), contiene, personal CAS y Tercero asistencial y administrativos, muestra detalle como departamento, servicios, especialidad, marcaciones, programacion de citas (solo asistencial), usuario y fecha de  registro. </li>
            <li class="list-group-item"><a href="http://192.168.32.119/apps/index.php?c=firma&a=buscar" title="" target="_black">&#8226;Acuerdo de Confidencialidad  </a>: Documento para ser firmado, por el personal asistencial y administrativo de la institucion. </li>
        </ul>
    </div>

    <div class="col-md-3">
        <h4><span class="form-control label label-info">Info :</span></h4>
        <hr>

        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/horarios" title="Enlace Directo a Gestion de Horarios" target="_self">&#8226; Gestionar Horarios  </a>: Permite gestionar los horarios para todo el personal que labora en el Hospital: asistencial o administrativo. </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/licencias" title="Enlace Directo a Gestion de Licencias" target="_self">&#8226; Licencias  </a>: Permite registrar diversos tipos de licencia, para la justificacion de las faltas del personal. </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/feriados" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Feriados  </a>: Registra los feriados, tanto los repetitivos como los de unica vez. </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/condicion" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Condicion Laboral  </a>: Tenemos el listado de las condiciones laborales del personal</li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/actividades" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Actividades Medicas </a>: Son las actividades que realizan los medicos, para generar los anexos 1 y 2 de personal.</li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/motivos" title="Enlace Directo a Motivos de Renuncia" target="_self">&#8226; Motivos de Renuncia </a>: Se muestran diversos tipos de renuncia para el registro correspondiente.. </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/turnos" title="Enlace Directo a Turnos" target="_self">&#8226; Tipos de Turno </a>: Son los turnos que nos permite generar programacion medica y de las actividades.. </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/unidad" title="Enlace Directo a Turnos" target="_self">&#8226; Autorizar usuarios </a>: Son los usuarios que tienen acceso al sistema para la programacion medica.</li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/asignar_servicios" title="Enlace Directo a Asignacion de Servicios" target="_self">&#8226; Asignacion de servicios </a>: Son los servicios que contiene a la unidad correspondiente.</li>

            
            
            
            
            
        </ul>

        
        
        
        

    </div>




</div>

 