<div class="row box-cell p-x-3 p-y-1 bg-default darken caja fixed-cabecera col-md-4 ">
    <div class="row">
        <h3 class="alert-warning text-center">Agenda</h3>
        <div class="col-md-6 text-center">

        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_nuevo" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Nueva Actividad --- ">NUEVA ACTIVIDAD</button>    
    </div>
    </div>


</div>
 




<div class="row">
    <?php for ($i = 1; $i <= 2; $i++) {
        echo '<div class="form-group"></div>';
    } ?>

</div>

<div class="row">
    <div class="col-md-12 text-center"><span id="Nro_resultados"></span>
    </div>
</div>
 
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <tr class="">
                    <th>Nro</th>
                    <th>Actividad</th>
                    <th>Lugar</th>
                    <th>Fecha</th>
                    <th>Operaciones</th>
                </tr>
                <tbody id="mostrar-datos-busqueda">

                </tbody>
            </table>
        </div>
    </div>
</div>





<!-- Modal Modificar Agenda  -->
<div class="modal" id="modificar_agenda" role="dialog">

    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" name="id_agenda" id="id_agenda">
                <input type="hidden" name="tipo_operacion" id="tipo_operacion">
                <span class="alert-info" id="txt_titulo_agenda"></span>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <label>Actividad : </label><br>
                        <input type="text" name="txt_actividad" id="txt_actividad" class="form-control alert-warning">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <label>Lugar : </label><br>
                        <input type="text" name="txt_lugar" id="txt_lugar" class="form-control alert-warning">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <label>Fecha : </label><br>
                        <input type="text" class="form-control crear-tooltip color-yellow-texto-large" id="txt_fecha" data-toggle="tooltip" name="txt_fecha" placeholder="Fecha Actividad" value="<?= date("d/m/Y") ?>"><br><br>
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer bg-default">
            <div class="col-xs-3"></div>
            <div class="col-xs-3"><button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar_agenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button></div>
            <div class="col-xs-3"><button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button></div>
            <div class="col-xs-3"></div>
        </div>
    </div>
</div>




<!-- Modal Eliminar expediente -->
<div class="modal fade" id="EliminarAdjunto" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">--- CONFIRME ELIMINAR LOS ADJUNTOS --- </h4>
                <input type="hidden" name="id_autoridad_eliminar" id="id_autoridad_eliminar">
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-xs-1"></div>
                    <div class="col-xs-11">
                        <input id="chk_cv" type="checkbox" value="1">--<span id="archivo_cvt"></span><br>
                        <input id="chk_nepotismo" type="checkbox" value="2">--<span id="archivo_nepotismo"></span><br>
                        <input id="chk_bienes" type="checkbox" value="3">--<span id="archivo_bienes"></span><br>
                        <input id="chk_intereses" type="checkbox" value="4">--<span id="archivo_intereses"></span><br>
                    </div>

                    <div class="form-group"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip " id="btn_eliminar_adjunto" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Confirme eliminar  --- "><i class="fa fa-save"></i>&nbsp;ELIMINAR ADJUNTOS MARCADOS</button>
                    </div>

                </div>




            </div>

        </div>

    </div>
</div>








<!-- Modal mensaje emergente -->
<div class="modal" id="mostrar_mensaje_emergente" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center"> -- Importante -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12"></div>
                    <p class="text-center mensajes"></p>
                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>