<?php

$listar_colegios_profesionales = json_decode( $this->listar_colegios );


?>

<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<div class="container-fluid pull-left">
    <div class="page-header">
        <img src="<?= RUTA_PUBLIC_GRA?>personal_colegios_profesionales.jpg" class="img-responsive" width="960" height="80" alt=""/>
    </div>
    <div class="row">
        <div class="col-md-4 bg-color-gris">
            <?php for ( $i = 1; $i <= 1; $i++ ) {echo '<br>';}?>
            <center><span class="label label-info">C O L E G I O S  ----  P R O F E S I O N A L E S</span>
            </center>
            <select name="slc_colegios_profesionales" size="25" id="slc_colegios_profesionales" class="form-control"></select>
            <span id="espera_de_lista_de_colegios"></span>
            <?php for ( $i = 1; $i <= 1; $i++ ) {echo '<br>';}?>
        </div>
        <div class="col-md-1 ">
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Colegio Profesional"><i class="fa fa-plus"></i></button>
            <?php for ( $i = 1; $i <= 3; $i++ ) {echo '<br>';}?>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Colegio Profesional"><strong> <i class="fa fa-pencil"></i> </strong>
                </button>
            <?php for ( $i = 1; $i <= 3; $i++ ) {echo '<br>';}?>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Colegio Profesional"><strong> <i class="fa fa-times"></i> </strong></button>
            <?php for ( $i = 1; $i <= 5; $i++ ) {echo '<br>';}?>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>ID:</label>
                <input type="text" name="txt_codigo" id="txt_codigo" class="form-control">
            </div>
            <div class="form-group">
                <label>Codigo:</label>
                <input type="text" name="txt_codigo_minsa" id="txt_codigo_minsa" class="form-control">
            </div>
            <div class="form-group">
                <label>Descripcion :</label>
                <input type="text" name="txt_descripcion" id="txt_descripcion" class="form-control initialism">
            </div>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_grabar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Registro"><strong> <span class="glyphicon glyphicon-floppy-disk" ></span></strong></button>
            <span id="espera_grabacion"></span>
        </div>
        
        <div class="col-md-4">
            <div class="table-responsive">

                <table class="table table-striped" id="tabla_colegios">
                    <thead>
                        <tr>
                            <th >Codigo</th>
                            <th >Descripcion</th>

                        </tr>
                    </thead>
                    <tbody id="mostrar_colegios">

                        <?php 
					foreach($listar_colegios_profesionales as $llave => $imprimir ): ?>
                        <tr>
                            <td>
                                <?= $imprimir->codigo_minsa ?>
                            </td>
                            <td>
                                <?= $imprimir->descripcion ?>
                            </td>
                        </tr>
                        <?php endforeach;?>

                    </tbody>
                </table>
            </div>
        
        
        </div>
        
        
    </div>
</div>