<?php
$condicion = json_decode( $this->condicion );
?>


<link rel="stylesheet" href="../layout/default/css/themes.min.css">


<div class="container-fluid  pull-left">


    <div class="page-header">
        <img src="<?= RUTA_PUBLIC_GRA?>administrar_condiciones_laborales.jpg" class="img-responsive" width="960" height="80" alt=""/>
    </div>



    <div class="row">
        <div class="col-md-1">
            <button class="btn btn-info  btn-lg crear-tooltip " style="position:fixed;" id="agregar_editar_condicion" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar / Editar Condicion"><strong>C</strong></button><br><br><br><br>
            <button class="btn btn-info  btn-lg crear-tooltip " style="position:fixed;" id="eliminar_condicion" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Condicion"><strong> <i class="fa fa-times"></i> </strong></button>
        </div>

        <div class="col-md-10">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="tabla_condicion">
                    <thead>
                        <tr>
                            <th bgcolor="#EFEBEB"></th>
                            <th bgcolor="#EFEBEB">Nombre</th>
                            <th bgcolor="#EFEBEB">Estado</th>
                            <th bgcolor="#EFEBEB">Registro</th>
                            <th bgcolor="#EFEBEB">Modificacion</th>

                        </tr>
                    </thead>
                    <tbody id="tabla_condicion">
                        <?php 
							foreach($condicion as $llave => $imprimir ): ?>
                        <tr>
                            <td bgcolor="#FCFBA0"><label class="px-single"><input type="radio" id="<?= $imprimir->idtiposituacion ?>" name="single-radio" value="" class="px usuarios"><span class="lbl"></span></label>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->nombre ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->tipo_estado ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->registro ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->fecha_mostrar ?>
                            </td>

                        </tr>

                        <?php endforeach;
                            ?>
                    </tbody>
                </table>
            </div>

        </div>


    </div>




    <div id="modal-agregar_editar_condicion" class="modal fade" role="dialog">
        <div class="modal-dialog modal-mg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <img src="<?= RUTA_PUBLIC_GRA?>agregar_editar_condicion.jpg" width="550" height="72" alt=""/>
                </div>
                <div class="modal-body">

                    <div class="alert alert-success" role="alert">
                        <center>
                            <h5 class="alert-heading">AGREGAR / MODIFICAR CONDICION LABORAL </h5>
                        </center>
                    </div>
                    <form id="frm_agregar" title="Registro de Agregacion">

                        <table width="650" border="0" align="center" cellpadding="0" cellspacing="0" id="id_tabla_registro">
                            <tbody>
                                <tr>
                                    <td colspan="3" align="center" bgcolor="#D4D4D4">
                                        <span class="badge badge-secondary"><strong>CONDICIONES REGISTRADAS</strong></span>
                                    </td>
                                    <td width="140" valign="top" bgcolor="#D4D4D4"><input name="operacion" type="radio" id="operacion1" form="frm_agregar" value="1">
                                        <strong>
                                <label for="nuevo">NUEVO</label></strong>
                                    

                                    </td>
                                    <td width="136" valign="top" bgcolor="#D4D4D4">
                                        <input name="operacion" type="radio" disabled="disabled" id="operacion2" form="frm_agregar" value="2">
                                        <strong>
                                <label for="editar">EDITAR</label></strong>
                                    


                                    </td>
                                    <td width="96" valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                </tr>
                                <tr>
                                    <td width="27" valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td width="208" valign="top" bgcolor="#D4D4D4">
                                        <select name="registrados" size="25" id="registrados" form="frm_agregar">
                                            <?php foreach($condicion  as $imprimir):?>
                                            <option value="<?= $imprimir->idtiposituacion ?>" id_tipo_situacion="<?= $imprimir->idtiposituacion ?>" nombre="<?= $imprimir->nombre ?>" <font size="-2" color="#000000"><strong>
                                                  <?=$imprimir->nombre ?> </font></strong>
                                            

                                            </option>
                                            <?php endforeach;?>
                                        </select>
                                    </td>
                                    <td width="43" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td colspan="2" align="left" valign="top" bgcolor="#D4D4D4"><label class="label">Descripcion:</label><br>
                                        <textarea name="descripcion" cols="22" rows="7" disabled="disabled" id="descripcion" style="background-color:#FCFBA0; border: solid 1px #000000; height: 55px; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px" form="frm_agregar" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()"></textarea>

                                        <br>
                                        <label class="label"> </label>


                                        <p>
                                            <label> </label>
                                        </p>
                                    </td>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                </tr>
                                <tr>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td bgcolor="#D4D4D4">&nbsp;</td>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                    <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                </tr>
                            </tbody>
                        </table>

                    </form>

                </div>
                <div class="modal-footer">
                    <input name="btn-guardar-nuevo-edicion" type="button" disabled="disabled" class="btn btn-primary btn-lg  " id="btn-guardar-nuevo-edicion" form="frm_agregar" title="Pulse aqui para guardar" value="Grabar Condicion">
                    <input name="btn-cerrar-modal" type="button" class="btn btn-primary btn-lg" id="btn-cerrar-modal" form="frm_agregar_horarios" title="Cerrar Modal " onClick="window.location.reload()" value="Cerrar" data-dismiss="modal">
                </div>
            </div>
        </div>
    </div>

</div>