<?php
/*
$horarios = json_decode( $this->listarhorarios );
$turnos = json_decode( $this->turnos );

*/


?>
<div class="page-header">
    <div class="col-md-7">
        <div class="box">
            <div class="box-row">
                <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                    <div class="form-group"></div>
                    <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Parametros : Horarios Registrados</strong>
                    </div>
                    <div class="form-group"></div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="container-fluid  pull-left">

   <div class="row">
       <div class="col-md-5">
            <strong><span class="form-control bg-default glyphicon glyphicon-pushpin">&nbsp;Horarios Registrados :</span></strong>
            <input name="txt_buscar_horarios" type="text" id="txt_buscar_horarios" class="form-control alert-warning text-secondary initialism">
            <strong><span class="form-control bg-default">&nbsp;Codigo  &nbsp;&nbsp;&#124; Horario </span></strong>
           <select name="slt_lista_horarios" size="10" class="form-control" id="slt_lista_horarios"></select>
     </div>
       
  </div>
    
    
    
    
    
    <div class="row">
        <div class="col-md-1">
            <button class="btn btn-info  btn-lg crear-tooltip " style="position:fixed;" id="agregar_editar_horarios" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar / Editar Horario"><strong>H</strong></button><br><br><br>
            <button class="btn btn-info  btn-lg crear-tooltip " style="position:fixed;" id="anular_horarios" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Anular Horarios"><strong> <i class="fa fa-times"></i> </strong></button>
        </div>

        <div class="col-md-4">

            <div class="table-responsive">

                <table class="table table-bordered table-condesed" id="tabla_horarios_cabecera">
                    <thead>
                        <tr>
                            <th bgcolor="#DDDBDB"></th>
                            <th bgcolor="#DDDBDB">Codigo</th>
                            <th bgcolor="#DDDBDB">Turno</th>
                            <th bgcolor="#DDDBDB">Nombre</th>
                            <th bgcolor="#DDDBDB">Ingreso</th>
                            <th bgcolor="#DDDBDB">Salida</th>
                            <th bgcolor="#DDDBDB">Horas</th>
                            <th bgcolor="#DDDBDB">Lunes</th>
                            <th bgcolor="#DDDBDB">Martes</th>
                            <th bgcolor="#DDDBDB">Miercoles</th>
                            <th bgcolor="#DDDBDB">Jueves</th>
                            <th bgcolor="#DDDBDB">Viernes</th>
                            <th bgcolor="#DDDBDB">Sabado</th>
                            <th bgcolor="#DDDBDB">Domingo</th>
                            <th bgcolor="#DDDBDB">Registro</th>
                            <th bgcolor="#DDDBDB">Cambios</th>
                        </tr>
                    </thead>
                    <tbody id="mostrar_horarios">
                        <?php 
					foreach($horarios as $llave => $imprimir ): ?>
                        <tr>
                            <td bgcolor="#FCFBA0"><label class="px-single"><input type="radio" id="<?= $imprimir->IDHORARIO ?>" name="single-radio" value="" class="px horarios"><span class="lbl"></span></label>
                            </td>


                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->CODIGOHORARIO ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->CODIGOTURNO ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->NOMBRE ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->HORAINGRESO ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->HORASALIDA ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->HORAS ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->LUNES ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->MARTES ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->MIERCOLES ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->JUEVES ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->VIERNES ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->SABADO ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->DOMINGO ?>
                            </td>


                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->fecharegistro ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->fechamostrar ?>
                            </td>


                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>


        </div>

    </div>

</div>

<div class="row">
  <span id="espera_grabacion_horarios"></span>
</div>

<div id="modal-agregar-horarios" class="modal fade" role="dialog">

    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <center><img src="<?= RUTA_PUBLIC_GRA?>agregar_horarios.jpg" width="550" height="72" alt=""/>
                </center>
            </div>
            <div class="modal-body">

                <div class="alert alert-success" role="alert">
                    <center>
                        <h5 class="alert-heading">Agregar / Modificar Horarios</h5>
                    </center>
                </div>
                <form id="frm_agregar_horarios" title="Registro de Agregacion de Horarios ">

                    <table width="724" border="0" align="center" cellpadding="0" cellspacing="0" id="id_tabla_registro">
                        <tbody>
                            <tr>
                                <td colspan="3" align="center" bgcolor="#D4D4D4">
                                    <span class="badge badge-secondary"><strong>HORARIOS REGISTRADOS</strong></span>
                                </td>
                                <td width="80" valign="top" bgcolor="#D4D4D4"><input name="operacion_horario" type="radio" id="operacion_horario1" form="frm_agregar_horarios" value="1">
                                    <strong>
                                <label for="nuevo_horario">NUEVO</label></strong>
                                
                                </td>
                                <td width="183" valign="top" bgcolor="#D4D4D4">
                                    <input name="operacion_horario" type="radio" disabled="disabled" id="operacion_horario2" form="frm_agregar_horarios" value="2">
                                    <strong>
                                <label for="editar_horario">EDITAR</label></strong>
                                
                                </td>
                                <td width="109" valign="top" bgcolor="#D4D4D4">

                                    <span id="id_horario_mostrar" class="label"></span>
                                </td>
                                <td width="85" valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="23" valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td width="175" valign="top" bgcolor="#D4D4D4">
                                    <select name="horarios_registrados" size="25" id="horarios_registrados" form="frm_agregar_horarios">
                                        <?php foreach($horarios  as $imprimir):?>
                                        <option value="<?=$imprimir->IDHORARIO?>" id_horario="<?=$imprimir->IDHORARIO  ?>" codigo_horario="<?=$imprimir->CODIGOHORARIO  ?>" codigo_turno="<?=$imprimir->CODIGOTURNO  ?>" nombre_horario="<?=$imprimir->NOMBRE  ?>" hora_ingreso="<?=$imprimir->HORAINGRESO  ?>" hora_salida="<?=$imprimir->HORASALIDA  ?>" horas="<?=$imprimir->HORAS ?>" <font size="-2" color="#000000"><strong>
                                                 <?=$imprimir->CODIGOHORARIO ?> - <?=$imprimir->CODIGOTURNO ?> - <?=$imprimir->NOMBRE ?> - <?=$imprimir->HORAINGRESO ?> - <?= $imprimir->HORASALIDA ?> </font></strong>
                                            </option>
                                        <?php endforeach;?> </select>
                                </td>
                                <td width="69" bgcolor="#D4D4D4">&nbsp;</td>
                                <td colspan="3" align="left" valign="top" bgcolor="#D4D4D4">
                                    <label for="Codigo_ho" class="label">(1) Codigo Horario:</label><br>
                                    <input name="codigo_horario" type="text" disabled="disabled" id="codigo_horario" form="frm_agregar_horarios" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:20px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="23" maxlength="22"><br>
                                    <label for="Tipo de Turno" class="label">(2) Turno : </label>
                                    <div id="ver_codigo_turno" class="label"></div> <br>
                                    <select name="seleccion-turno" disabled="disabled" class="form-control" id="seleccion-turno" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:16px; color: #000000; font-weight: bold; vertical-align:9px" form="frm_agregar_horarios">
                                        <option value="">Seleccionar Turno</option>
                                        <?php foreach($turnos as $imprimir):?>
                                        <option value="<?=$imprimir->codigo?>" codigo_turno="<?=$imprimir->codigo ?>" <font size="2">
                                            <?=$imprimir->codigo?>-
                                            <?=$imprimir->nombre?>
                                            </font>
                                        </option>
                                        <?php endforeach;?>
                                    </select>
                                    <br>
                                    <label for="ingreso" class="label">(3) Hora de Ingreso: </label><br>

                                    <input name="hora_ingreso" type="text" disabled="disabled" id="hora_ingreso" form="frm_agregar_horarios" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:20px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="23" maxlength="22"><br>

                                    <label for="salida" class="label">(4) Hora de Salida: </label><br>

                                    <input name="hora_salida" type="text" disabled="disabled" id="hora_salida" form="frm_agregar_horarios" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:20px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="23" maxlength="22"><br>

                                    <label for="total_horas" class="label">(5) Total de Horas: </label><br>
                                    <input name="total_horas" type="text" disabled="disabled" id="total_horas" form="frm_agregar_horarios" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:20px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="23" maxlength="22"><br>



                                    <p>&nbsp;
                                        
                                        
       </p>
                                    <table width="200">
                                      <tr>
                                        <td><label>
                                          <input type="radio" name="todos_los_dias" value="1" id="todos_los_dias_0">
                                          Todos los dias</label></td>
                                      </tr>
                                      <tr>
                                        <td><label>
                                          <input type="radio" name="todos_los_dias" value="2" id="todos_los_dias_1">
                                          Desabilitar para todos los dias</label></td>
                                      </tr>
                                    </table>
                                    <p>
                                        
                                      
                                      
                                    </p>
                                </td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                            </tr>
                            <tr>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td bgcolor="#D4D4D4">&nbsp;</td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                                <td valign="top" bgcolor="#D4D4D4">&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>

                </form>

            </div>
            <div class="modal-footer">
                <input name="btn-guardar-nuevo-edicion-horario" type="button" disabled="disabled" class="btn btn-primary btn-lg  " id="btn-guardar-nuevo-edicion-horario" form="frm_agregar_horarios" title="Pulse aqui para guardar" value="Grabar Nuevo Horario">
                <input name="btn-cerrar-modal" type="button" class="btn btn-primary btn-lg" id="btn-cerrar-modal" form="frm_agregar_horarios" title="Cerrar Modal " onClick="window.location.reload()" value="Cerrar" data-dismiss="modal">
            </div>
        </div>
    </div>
</div>

</div>

