<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<div class="page-header">
    <div class="col-md-7">
        <div class="box">
            <div class="box-row">
                <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                    <div class="form-group"></div>
                    <div class="form-group">
                        &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Parametros : Unidad Prestadora de Servicio de Salud (UPSS)</strong>
                    </div>
                    <div class="form-group"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container pull-left">
    <div class="row">
        <div class="col-md-4">
            <strong><span class="form-control bg-default glyphicon glyphicon-pushpin">&nbsp;Unidad Prestadora de Servicio de Salud :</span></strong>
            <select name="slc_upss" size="20" id="slc_upss" class="form-control alert-warning"></select>
            <span id="espera_mientras_carga_upss" class="form-control"></span>
        </div>
        <div class="col-md-1">
            <button class="btn btn-info  btn-lg crear-tooltip" style="position:fixed;" id="agregar_upss" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar UPSS"><i class="fa fa-plus"></i></button>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <button class="btn btn-info  btn-lg crear-tooltip" style="position:fixed;" id="modificar_upss" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar UPSS"><strong> <i class="fa fa-pencil"></i> </strong></button>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <button class="btn btn-info  btn-lg crear-tooltip" style="position:fixed;" id="eliminar_upss" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar UPSS"><strong> <i class="fa fa-times"></i> </strong></button>
        </div>
        <div class="col-md-7">
            <div class="panel panel-default">
                <div class="panel-heading">Registro :</div>
                <div class="panel-body">
                    <div class="col-xs-2">
                        <strong>Codigo :</strong>
                        <input name="txt_codigo_upss" type="text" disabled="disabled" id="txt_codigo_upss" class="form-control">
                    </div>
                    <div class="col-xs-10">
                        <strong>Descripcion :</strong><input name="txt_descripcion_upss" id="txt_descripcion_upss" type="text" class="form-control initialism alert-warning">
                    </div>
                </div>
                <div class="form-group"></div>
                <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_upss" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Registro"><span class="glyphicon glyphicon-ok"></span> Grabar</button>
            </div>
            <span id="espera_grabacion"></span>
            <div class="form-group"></div>
        </div>
    </div>
</div>