<div class="row">
    <img src="<?= RUTA_PUBLIC_GRA?>sistema_de_turnos.jpg" width="961" height="80" alt=""/>';
</div>



<div class="row">
    <hr>
  <div class="col-md-4">
        <h4><span class="label label-info">Enlaces Directos al Sistema de Turnos y Programacion:</span></h4>
        <hr>

        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>asignacion/horario" title="Enlace Directo a Asignacion de Horario" target="_self">&#8226; Asig. Horario</a>: Se muestran el personal registrado que se le asignara el horario correspondiente, para el caso de asistencial se considera turno rotativo. </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>asignacion/asistencia" title="Enlace Directo a Asignacion de Asistencia" target="_self">&#8226; Asig. Asistencia</a>: Se muestran el personal al que se generara la asistencia por mes. </li>
            

            <li class="list-group-item"><a href="<?=BASE_URL ?>programacion/administrativos" title="Enlace Directo a Asignacion de Asistencia" target="_self">&#8226; Programacion Horario Administrativo</a>: Se muestran el personal al que se generara la asistencia por mes. </li>
            
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>programacion/asistencial" title="Enlace Directo a Asignacion de Asistencia" target="_self">&#8226; Programacion Horario Asistencial</a>: Se muestran el personal al que se generara la asistencia por mes. </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>actividades/registros" title="Enlace Directo a Asignacion de Asistencia" target="_self">&#8226; Actividades Registros </a>: Se muestran el personal al que se generara la asistencia por mes. </li>
            
            
            
            
        </ul>
    </div>


</div>
