<div class="row box-cell p-x-3 p-y-1 bg-default darken caja fixed-cabecera col-md-4 ">
    <div class="row">
        <h3 class="alert-warning text-center">Directorio</h3>
        <div class="col-md-12">
            <ol>
                <ul>Lineas de Color Verde se muestran en el directorio principal
                </ul>
                <ul>Lineas de Color Rojo bo se muestran en el directorio principal
                </ul>

            </ol>


        </div>
    </div>


</div>





<div class="row">
    <?php for ($i = 1; $i <= 2; $i++) {
        echo '<div class="form-group"></div>';
    } ?>

</div>

<div class="row">
    <div class="col-md-12 text-center"><span id="Nro_resultados"></span>
    </div>
</div>






<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading bg-info">

            </div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover table-condensed">
                    <tr class="">
                        <th class="fondo-azul">Nro</th>
                        <th>Cargo</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Anexo</th>
                        <th>Celular</th>
                        <th>RPM</th>
                        <th>Operaciones</th>
                    </tr>
                    <tbody id="mostrar-datos-busqueda">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>





<!-- Modal Modificar Directorio  -->
<div class="modal" id="modificar_directorio" role="dialog">

    <div class="modal-dialog modal-xs">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" name="id_directorio" id="id_directorio">
                <span class="alert-info" id="txt_titulo_directorio"></span>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_vapp">Cargo : </label><br>
                        <input type="text" name="txt_cargo" id="txt_cargo" class="form-control alert-warning">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_imagen">Nombre : </label><br>
                        <input type="text" name="txt_nombre" id="txt_nombre" class="form-control alert-warning">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_imagen">email : </label><br>
                        <input type="text" name="txt_email" id="txt_email" maxlength="50" class="form-control alert-warning">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_imagen">anexo : </label><br>
                        <input type="text" name="txt_anexo" id="txt_anexo" maxlength="4" class="form-control alert-warning">
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_imagen">celular : </label><br>
                        <input type="text" name="txt_celular" id="txt_celular" maxlength="9" class="form-control alert-warning">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <label for="txt_imagen">rpm : </label><br>
                        <input type="text" name="txt_rpm" id="txt_rpm" maxlength="9" class="form-control alert-warning">
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer bg-default">
            <div class="col-xs-3"></div>
            <div class="col-xs-3"><button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar_directorio" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button></div>
            <div class="col-xs-3"><button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button></div>
            <div class="col-xs-3"></div>
        </div>
    </div>
</div>




<!-- Modal Eliminar expediente -->
<div class="modal fade" id="EliminarAdjunto" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">--- CONFIRME ELIMINAR LOS ADJUNTOS --- </h4>
                <input type="hidden" name="id_autoridad_eliminar" id="id_autoridad_eliminar">
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-xs-1"></div>
                    <div class="col-xs-11">
                        <input id="chk_cv" type="checkbox" value="1">--<span id="archivo_cvt"></span><br>
                        <input id="chk_nepotismo" type="checkbox" value="2">--<span id="archivo_nepotismo"></span><br>
                        <input id="chk_bienes" type="checkbox" value="3">--<span id="archivo_bienes"></span><br>
                        <input id="chk_intereses" type="checkbox" value="4">--<span id="archivo_intereses"></span><br>
                    </div>

                    <div class="form-group"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip " id="btn_eliminar_adjunto" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Confirme eliminar  --- "><i class="fa fa-save"></i>&nbsp;ELIMINAR ADJUNTOS MARCADOS</button>
                    </div>

                </div>




            </div>

        </div>

    </div>
</div>








<!-- Modal mensaje emergente -->
<div class="modal" id="mostrar_mensaje_emergente" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center"> -- Importante -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12"></div>
                    <p class="text-center mensajes"></p>
                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>