<?php

$lc_actor = $_SESSION["usuario"]["actor"];

$lc_usuario = trim($_SESSION["usuario"]["nombreusuario"]);



?>


<style>
    .color-text {
        color: #ffffff;
    }
</style>
<div class="row box-cell p-x-3 p-y-1 bg-panel darken caja fixed-cabecera-entrada center">
    <div class="col-md-3">
        <span class="form-control bg-default">Nro. de Expediente : (Ejem. : 21TD-01000-00)</span>
        <input type="text" name="nro_expediente" class="form-control bg-color-input-text initialism crear-tooltip color-yellow-text-black text-largo" id="nro_expediente" data-placement="right" placeholder="Nro de Expediente" data-original-title="Digite Nro de Expediente" data-toggle="tooltip">
        <div class="col-xs-4"></div>
        <div class="col-xs-5">
            <button class="btn btn-info  btn-lg form-control  crear-tooltip " id="btn_busquar_expediente" data-toggle="tooltip" data-placement="right" title="" data-original-title="Buscar expediente"><span class="glyphicon glyphicon-search"></span>&nbsp;Buscar</button>
        </div>
        <div class="col-xs-3"></div>
    </div>
    <div class="col-md-6">
        <span class="form-control bg-default">Seleccione remitente / expediente :</span>
        <div class="form-group no-margin-hr  mostrarreferencia">
            <div class="input-group">

                <span class="input-group-addon bg-default glyphicon glyphicon-folder-close teal-color"></span>
                <input type="text" name="txt_referencia" class="form-control bg-color-input-text initialism crear-tooltip color-yellow" id="txt_referencia" placeholder="Ubique remitente" data-placement="bottom" data-original-title="Selecione remitente o expediente" data-toggle="tooltip">
                <span id="ver_msjreferencia"></span>
                <input type="hidden" name="txt_idexpediente" id="txt_idexpediente">
            </div>
        </div>
        <span id="espera_busqueda"></span>
    </div>
    <div class="col-md-2">
        <div class="form-group"></div>
        <div class="form-group"></div>
    </div>
</div>

<div class="row">
    <?php for ($i = 1; $i <= 2; $i++) {
        echo '<div class="form-group"></div>';
    } ?>

</div>


<div class="row">
    <div class="col-xs-2">
        <div class="form-group">

            <span class="input-group-addon bg-default   text-right">Nro: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <input type="text" id="txt_nro_expediente" name="txt_nro_expediente" class="form-control" readonly>

        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default   text-right">Fecha :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <input type="text" id="txt_fecha" name="txt_fecha" class="form-control" readonly>

        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default">Interesado : </span>
            <textarea name="txt_interesado" id="txt_interesado" rows="4" class="form-control" readonly></textarea>

        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default">Asunto : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
            <textarea name="txt_asunto" id="txt_asunto" rows="5" class="form-control" readonly></textarea>

        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default">Tipo documento:</span>
            <input type="text" id="txt_documento" name="txt_documento" class="form-control" readonly>

        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Fecha culminacion:</span>
            <input type="text" id="txt_fecha_culminacion" name="txt_fecha_culminacion" class="form-control" readonly>

        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default">Usuario culminacion:</span>
            <input type="text" id="txt_usuario_culminacion" name="txt_usuario_culminacion" class="form-control" readonly>

        </div>
    </div>



    <div class="col-xs-2">
        <div class="form-group">

            <span class="input-group-addon bg-default">Actor actual:</span>
            <textarea name="txt_actor_actual" id="txt_actor_actual" rows="4" class="form-control" readonly></textarea>


        </div>
        <div class="form-group">

            <span class="input-group-addon bg-default">Estado expediente:</span>
            <!-- <input type="textarea" id="txt_estado_expediente" name="txt_estado_expediente" class="form-control"> -->
            <textarea id="txt_estado_expediente" name="txt_estado_expediente" rows="2" class="form-control">
                </textarea>

        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Hora recepcion:</span>
            <input type="text" id="txt_hora_recepcion" name="txt_hora_recepcion" class="form-control" readonly>

        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Nro. Documento:</span>
            <textarea name="txt_nro_documento" id="txt_nro_documento" rows="3" class="form-control" readonly></textarea>


        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Dias en proceso:</span>
            <input type="text" id="txt_dias" name="txt_dias" class="form-control" readonly>

        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Hora de culminacion:</span>
            <input type="text" id="txt_hora_culminacion" name="txt_hora_culminacion" class="form-control" readonly>

        </div>

        <div class="form-group">

            <span class="input-group-addon bg-default">Comentario : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
            <textarea name="txt_comentario" id="txt_comentario" rows="3" class="form-control" readonly></textarea>

        </div>
    </div>


    <div class="col-xs-7">
        <div class="col-xs-12">
            <span class="input-group-addon bg-default">Detalle : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
            <select name="slt_expediente" id="slt_expediente" class="form-control alert-info" size="7"></select>
            <div class="row">
                <div class="col-md-2">
                    <div class="input-group">
                        <span class="input-group-addon bg-default">Derivacion :</span>
                        <strong><span id="nro"></span></strong>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="input-group">
                        <span class="input-group-addon bg-default">Cargo :</span>
                        <strong><span id="idcargo" class="text-md text-center form-control color-text"></span></strong>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="input-group">
                        <span class="input-group-addon bg-default">Recepcion :</span>
                        <strong><span id="idrecepcion" class="text-md text-center form-control color-text"></span></strong>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-1"></div>
                <div class="col-xs-10">
                    <span class="bg-default">Remite : </span><span class="text-bold" id="id_remite"></span>
                    <input type="text" id="txt_actor_de" name="txt_actor_de" class="form-control" readonly>
                    <div class="form-group"></div>
                    <span class="bg-default">Destino : </span><span class="text-bold" id="id_destino"></span>
                    <input type="text" id="txt_actor_para" name="txt_actor_para" class="form-control" readonly>
                    <span class="bg-default">Acciones: </span>
                    <input type="text" id="txt_acciones" name="txt_acciones" class="form-control" readonly>

                </div>

                <div class="row">
                    <div class="col-xs-1"></div>
                    <div class="col-xs-10">
                    </div>
                </div>
            </div>

        <?php
        if ($lc_usuario == "SUPERVISOR") {
            echo '
            <div class="row">
                 <div class="form-group"></div>
                 <div class="col-md-7"></div>
                 <div class="col-md-4">
                     <button id="Resolver-actor-errado" class="form-control">Cambiar Actor Destino</button>
                 </div>
            </div>
                ';
        }


        ?>


        <div class="form-group"></div>

        <div class="col-xs-12">
            <span class="bg-default">Documento Adjunto 1 : </span>
            <input type='text' name="txt_adj1" id="txt_adj1" class="form-control text-lg" readonly>
        </div>
        <div class="form-group"></div>

        <div class="col-xs-12">
            <span class="bg-default">Documento Adjunto 2 : </span>
            <input type='text' name="txt_adj2" id="txt_adj2" class="form-control text-lg" readonly>
        </div>
        <div class="form-group"></div>

        <div class="col-xs-12">
            <span class="input-group-addon bg-default">Observacion : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
            <textarea name="txt_observacion" id="txt_observacion" rows="2" class="form-control" readonly></textarea>
        </div>
    </div>


    <div class="col-xs-4"></div>
    <div class="col-xs-4">
        <button class="btn btn-info crear-tooltip" id="btn_impresion_de_kardex" data-toggle="tooltip" data-placement="bottom" title=" IMPRIMIR " disabled="disabled" data-original-title="Imprimir expediente"><i class="fa fa-print color-blanco"></i> - IMPRIMIR - </button>
    </div>
    <div class="col-xs-4"></div>





</div>

</div>













<!-- Modal mernsaje emergente -->
<div class="modal" id="mostrar_mensaje_emergente" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center" id="nro_expediente"> -- Expediente -- </h4>
                <input type="hidden" name="idexpediente" id="idexpediente">
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12"></div>
                    <p class="text-center mensajes"></p>
                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>