
 SELECT  1 as iverifica, bpa.vanio, ttb.vdescripcion as tipo_bien, bp.bhabilitado, bp.vcodbarra as codigo_barra, bp.vcodsbn as codigo_sbn, bp.vdescripcion as descripcion, cb.vdenominacion as bien_sbn, gru.dscgrupo as grupo, cla.dscclase as clase, mcu.vcuenta as c_cuenta, mcu.vdescripcion as n_cuenta, " +
                  bp.vobservacion as datos_adicionales,  bp.vobservacionesgenerales as obs_generales, esta.vdescripcion as estado,  sit.vdescripcion as situacion,  pen.vdescripcion as pendiente, CASE bpa.binventario WHEN TRUE THEN 'SI' ELSE 'NO' END as inventario, " +
                  teinv.vdescripcion as estado_inventario, bpa.vobservaciones as obsv_inventario, bpa.vobsinventario as nro_folio, gen.vdescripcion as genero, bp.vmarca as marca, bp.tipo as tipo, bp.vmodelo as modelo, bp.vserie as serie, bp.color as color, " +
                  bp.vnumtelefono as num_tele, bp.vnumcorto as rpm_rpc_radio, bp.longitud AS longitud, bp.altura AS altura, bp.ancho AS ancho, bp.votros as otros, bp.vplaca as placa_numero, bp.vaniofab as anio_fab, bp.vnummotor as num_motor_imei, bp.vnumchasis as num_chasis_simcard, " +
                  bp.matricula as matricula, bp.vpesobruto as peso_burto, bp.vpesoneto as peso_neto, bp.vformato as formato, bp.vfrecuenciacanal as frecuencia_canal, bp.vespecificacionestecnicas AS otras_especificaciones, bp.vobservacionestecnicas AS obs_tecnicas, " +
                  pro.vdescripcion as procedencia, tad.vdescripcion as tipo_adquisicion, bp.vresolucionprocedencia as resolucion,  bp.vnumocompra as numero_oc,  bp.vnumnea as num_nea, bp.vnumfactura as num_factura, bp.vnumpecosa as num_pecosa, bp.vnumguia as num_guia, " +
                  bp.vnroordencanjeprocedencia as num_o_canje, bp.vnronrcprocedencia as num_nrc, bp.vrucprov as ruc_prov, bp.vanio as anio, bp.vactaprocedencia as acta, bp.dfecharesolucion as fecha_resolucion, bp.dfechaalta as fecha_oc, bp.dfechanea as fecha_nea, " +
                  bp.dfechafactura as fecha_factura, bp.dfechapecosa as fecha_pecosa, bp.dfechaguiaremisionprocedencia as fecha_guia, bp.dfechaordencanjeprocedencia as fecha_orden_canje, bp.dfechanrcprocedencia as fecha_nrc, bp.vproveedor as proveedor, " +
                  bp.votrosdetalles as obs_compra, bp.vmoneda as moneda,  bp.nvalors AS valor_patrimonial,  CASE bpa.ncosto WHEN NULL THEN bp.nvalors ELSE(bpa.ncosto+bpa.ncostoregula) END as v_costo,    (bpa.ndepreacumulada + bpa.ndepreregula) as v_depreciacion, " +
                  bpa.nneto as v_neto,  (mpn.vpaterno || ' ' || mpn.vmaterno || ' ' || mpn.vnombre) as usuario, mof.vcodalmacen as codigo_division, mof.vnombre as division, a6.vdescripcion as oficina, a4.vdescripcion as sub_area, a2.vdescripcion as area,  reg.vdescripcion as direccion, " +
                  CASE bpa.bestado WHEN TRUE THEN 'NO' WHEN FALSE THEN 'SI' ELSE 'PENDIENTE' END as baja, rbaja.vresolucion as resolucion_baja,  bpa.fecbaja as fecha_baja, tbaj.vdescripcion as tipo_baja, bpa.vobsbaja as observacion_baja, " +
                  rdis.vresolucion as resolucion_dispocision, bpa.fecdisposicion as fecha_dispocision, bpa.vobsdisposicion as observacion_dispocision, mpn.iidpersona " +
                  FROM    bienes_patrimoniales.bienespatrimonio as bp LEFT JOIN bienes_patrimoniales.bienespatrimonioanual as bpa ON bp.iidbien = bpa.iidbien LEFT JOIN activo_fijo.mcuenta as mcu ON mcu.iidcuenta = bp.iidcuenta LEFT JOIN persona.mpernatural as mpn ON mpn.iidpersona = bpa.iidpersona " +
                  LEFT JOIN nucleo.moficina as mof ON mof.iidoficina = bpa.iidoficina LEFT JOIN bienes_patrimoniales.ttipobienpatrimonio as ttb ON ttb.iidtipobienpatrimonio = bp.iidtipobienpatrimonio LEFT JOIN bienes_patrimoniales.areas2 as a2 ON a2.vcodigo = SUBSTRING(mof.vcodalmacen, 1, 2) " +
                  LEFT JOIN bienes_patrimoniales.areas4 as a4 ON a4.vcodigo = SUBSTRING(mof.vcodalmacen, 1, 4) LEFT JOIN bienes_patrimoniales.areas6 as a6 ON a6.vcodigo = SUBSTRING(mof.vcodalmacen, 1, 6) " +
                  LEFT JOIN bienes_patrimoniales.region as reg ON bpa.iidregion = reg.iidregion LEFT JOIN bienes_patrimoniales.procedencia as pro ON pro.iidprocedencia = bp.iidprocedencia " +
                  LEFT JOIN bienes_patrimoniales.testadoinventario as teinv ON teinv.iidestadoinventario = bpa.iidestadoinventario LEFT JOIN bienes_patrimoniales.resolucionbaja as rbaja ON rbaja.iidresolucion = bpa.iidresolucion " +
                  LEFT JOIN bienes_patrimoniales.resolucionbaja as rdis ON rdis.iidresolucion = bpa.iidresoldisposicion LEFT JOIN bienes_patrimoniales.catalogobienes as cb ON cb.vcodigo = SUBSTRING(bp.vcodsbn, 1, 8) " +
                  LEFT JOIN bienes_patrimoniales.tsituacionbien as sit ON sit.iidsituacion = bpa.iidestado LEFT JOIN bienes_patrimoniales.testadobien as esta ON esta.iidestadobien = bpa.iidestadobien " +
                  LEFT JOIN bienes_patrimoniales.clases as cla ON cla.clase = SUBSTRING(cb.vcodigo, 3, 2) LEFT JOIN bienes_patrimoniales.grupos as gru ON gru.grupo = SUBSTRING(cb.vcodigo, 1, 2) " +
                  LEFT JOIN bienes_patrimoniales.pendiente as pen ON pen.iidpendiente = bp.iidpendiente LEFT JOIN bienes_patrimoniales.tgenerobien as gen ON gen.iidgenerobien = bp.iidgenerobien " +
                  LEFT JOIN bienes_patrimoniales.ttipoadquisicion as tad ON tad.iidtipoadquisicion = bp.iidtipoadquisicion LEFT JOIN bienes_patrimoniales.ttipobaja as tbaj ON tbaj.iidtipobaja = cast(bpa.tipobaja as integer) " +
                  WHERE bpa.vanio = (SELECT MAX(iidanoeje) FROM nucleo.tanoeje) AND bp.bhabilitado IS TRUE and mpn.iidpersona = " + Int32.Parse(iidusuario) + " ORDER BY bp.vcodbarra, bp.vdescripcion";