<?php

$listar_todo_personal = json_decode( $this->ver_todo_el_personal );
 

?>



<style type="text/css">
    .resaltado {
        background-color: #FCFBA0;
        border: solid 1px #000000;
        height: 20px;
        width: 170px;
        font-size: 14px;
        color: #000000;
        font-weight: bold;
        vertical-align: 9px
    }
    
    .color-fondo {
        background-color: #DFFFE6;
    }
    
    .color-fondo-columna {
        background-color: #E7E7E7;
    }
    
  
</style>



<div class="page-header">
    <img src="<?= RUTA_PUBLIC_GRA?>procesar_descuentos_administrativo_asistencial.jpg" width="960" height="80" alt=""/>';

</div>
<span id="fecha_completa" class="label bg-success"></span>

<div class="row ">

    <div class="col-md-3 color-fondo-columna">
        <form id="frm_procesar_descuentos">
            <select name="mes" size="1" class="select2-highlighted resaltado" id="mes" title="Seleccion de Mes" ng-model="month" style="width: 155px;">
                <option value="1">ENERO</option>
                <option value="2">FEBRERO</option>
                <option value="3">MARZO</option>
                <option value="4">ABRIL</option>
                <option value="5">MAYO</option>
                <option value="6">JUNIO</option>
                <option value="7">JULIO</option>
                <option value="8">AGOSTO</option>
                <option value="9">SEPTIEMBRE</option>
                <option value="10">OCTUBRE</option>
                <option value="11">NOVIEMBRE</option>
                <option value="12">DICIEMBRE</option>
            </select>
            <input name="anio" type="number" class="resaltado" id="anio" max="2050" min="2016" title="Seleccion de Año" onkeypress='return event.charCode >= 2016 && event.charCode <= 2100' style="width: 75px;">
            <table width="400">
                <tr>
                    <td><label>
              <input type="radio" name="opt_tipo_personal" value="1" id="opt_tipo_personal_0">
              ADMINISTRATIVOS</label>
                    

                        <label>
              <input type="radio" name="opt_tipo_personal" value="2" id="opt_tipo_personal_1">
              ASISTENCIAL</label>
                    


                        <label>
              <input type="radio" name="opt_tipo_personal" value="3" id="opt_tipo_personal_2">
              TODOS</label>
                    

                    </td>
            </table>

            <input name="btn_procesar" type="button" class="btn-primary btn-lg" id="btn_procesar" title="Pulse aqui para procesar descuentos" value="Iniciar Proceso" width="30" height="60" style="left:inherit">
            <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
            <span id="total_trabajadores" class="label label-default"></span><br>
            <span id="total_sueldos" class="label"></span>
            <span id="total_descuentos" class="label"></span>

            <select name="slc_mostrar_descuentos" size="40" id="slc_mostrar_descuentos" style="background-color:#FCFBA0; border: solid 1px #000000; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px;  width: 350px;">
        </select>
        


            <span id="esperar_mientras_procesa_descuentos"></span>
        </form>

    </div>




    <div class="col-md-4 ">

      <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tbody>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td colspan="6" bgcolor="#D4D4D4" style="text-align: center">DETALLE DEL PERSONAL - DESCUENTO</td>
                </tr>
                <tr>
                    <th height="16" scope="row">&nbsp;</th>
                    <td colspan="6" style="text-align: center;"></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td bgcolor="#D4D4D4" style="text-align: right">DNI: </td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="dni"  ></span>
                    </td>
                </tr>
                <tr>
                    <th width="1%" scope="row">&nbsp;</th>
                    <td width="45%" bgcolor="#D4D4D4" style="text-align: right"> Personal : </td>
                    <td width="1%">&nbsp;</td>
                    <td colspan="4"><span id="apellidos_nombres" ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td width="45%" bgcolor="#D4D4D4" style="text-align: right"> Cargo : </td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="cargo"  ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td width="45%" bgcolor="#D4D4D4" style="text-align: right"> Unidad : </td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="unidad_organica"  ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Grupo Ocupacional:</td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="grupo_ocupacional"  ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Ingreso:</td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="ingreso"  ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Sueldo :</td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="sueldo"  ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Costo Hora :</td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="costo_hora" ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Tipo Personal::</td>
                    <td>&nbsp;</td>
                    <td colspan="4"><span id="tipo_personal" class="label label-default" ></span> </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td colspan="6"><hr></td>
                </tr>
                <tr>
                  <th scope="row">&nbsp;</th>
                  <td bgcolor="#D4D4D4" style="text-align: right">Descuento:</td>
                  <td>&nbsp;</td>
                  <td><span id="descuento"></span> </td>
                  <td colspan="3"><span id="formula_descuento"></span> </td>
                </tr>
                <tr>
                  <th scope="row">&nbsp;</th>
                  <td colspan="6" bgcolor="#FFFFFF" style="text-align: center; color: #FFFFFF;"><hr></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td bgcolor="#D4D4D4" style="text-align: right">Minutos Descontar por tardanza :</td>
                    <td>&nbsp;</td>
                    <td width="12%"><span id="minutos_descontar"></span> </td>
                    <td width="16%" align="center"><input name="btn_modifica" type="button"   id="btn_modifica" title="Modifica datos de descuentos" value="Modificar"  disabled="disabled" class="btn-info btn-lg" ></td>
                    <td width="4%">&nbsp;</td>
                    <td width="21%" valign="top"><span class="label">Minutos</span><br>
                        <input type="text" name="txt_minutos_tardanza" id="txt_minutos_tardanza"   disabled="disabled" style="width: 70px;"  >
                  </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right" bgcolor="#D4D4D4">Falta (Inasistencia) :</td>
                    <td>&nbsp;</td>
                    <td><span id="faltas"></span> </td>
                    <td><span id="a_modificar" class="label label-warning"></span></td>
                    <td>&nbsp;</td>
                    <td valign="top"><span class="label">Dias</span><br>
                        <input type="text" name="txt_falta" id="txt_falta"  disabled="disabled" style="width: 70px;" > </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right"  bgcolor="#D4D4D4">Minutos Antes de Salida : </td>
                    <td>&nbsp;</td>
                    <td><span id="antes_salida"></span></td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td valign="top"><span class="label">Minutos</span><br><input type="text" name="txt_minutos_antes_salida" id="txt_minutos_antes_salida"  disabled="disabled" style="width: 70px;" >
                  </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td bgcolor="#D4D4D4" style="text-align: right">Exoneracion :</td>
                    <td>&nbsp;</td>
                    <td><span id="exoneracion"></span></td>
                    <td colspan="2">&nbsp;</td>
                    <td valign="top"><span class="label">Minutos</span><br><input type="text" name="txt_exoneracion" id="txt_exoneracion" disabled="disabled" style="width: 70px;" >
                  </td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="2">&nbsp;</td>
                    <td><span id="valor_pre"></span></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right">Minutos Extra :</td>
                    <td>&nbsp;</td>
                    <td><span id="minutos"></span> </td>
                    <td colspan="2">&nbsp;</td>
                    <td align="center"><input name="btn_pre_descuento" type="button" disabled="disabled" class= "btn-info btn-mg" id="btn_pre_descuento" value="Calcular Pre Descuento"></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td style="text-align: right">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><span id="horas"></span></td>
                    <td colspan="2">&nbsp;</td>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td align="center"><input name="bt_grabar" type="button"  disabled="disabled" class="btn-info btn-mg" id="bt_grabar" title="Graba modificaciones" value=" -- Grabar Descuento --"></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td><span id="espera_grabacion"></span></td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                </tr>
                <tr>
                    <th scope="row">&nbsp;</th>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                </tr>
            </tbody>
        </table>
        <hr>
        <span class="col-md-3 color-fondo-columna-2">
        <input name="btn_imprimir_descuento" type="button" disabled="disabled" class="btn-info btn-lg" id="btn_imprimir_descuento"  title="Pulse aqui para descargar impresiones" value="Imprimir Personal Descuento" width="30" height="60" style="left:inherit" >
        <input name="btn_imprimir_plh" type="button" disabled="disabled" class="btn-info btn-lg" id="btn_imprimir_plh"  title="Pulse aqui para descargar impresiones" value="Imprimir Archivo PLH" width="30" height="60" style="left:inherit" >
    </span></div>



    <div class="col-md-3 color-fondo-columna">

        <font size="1">
            <table width="300" border="1" align="left" cellspacing="0" id="mostrar_horario">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>

                <thead id="cabecera_administrativo">
                    <tr>
                        <th width="60" align="right" bgcolor="#E9E9E9" class="" scope="col"> Fecha </th>
                        <th width="105" align="right" valign="top" bgcolor="#E9E9E9" class="" scope="col"> Turno</th>
                        <th width="105" align="center" valign="top" bgcolor="#E9E9E9" class="" scope="col"> Dia </th>
                        <th width="110" align="left" valign="top" bgcolor="#E9E9E9" class="" scope="col"> Entrada</th>
                        <th width="110" align="center" bgcolor="#E9E9E9" class="" scope="col"> Marcacion</th>
                        <th width="110" align="center" bgcolor="#E9E9E9" class="" scope="col"> Salida</th>
                        <th width="110" align="center" bgcolor="#E9E9E9" class="" scope="col"> Marcacion</th>
                        <th width="110" align="center" bgcolor="#E9E9E9" class="" scope="col">Tard.</th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col">Desc.</th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col">Extra</th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col">Inas.</th>
                        <th width="90" align="center" class="" scope="col">Fer.</th>
                    </tr>
                </thead>
                <tbody id="mostrar_horario_descuento" border="0">
                </tbody>
            </table>
            <center><span id="esperar_mientras_procesa_horario" style="left:inherit"></span>
            </center>
            <br>


            <span id="descripcion"><br>
            Descripcion cabecera <br>
        
        Fecha : Fecha de programacion de asistencia<br>
        Turno : Turno que le corresponde al personal<br>
        Dia   : Nombre del Dia<br>
        Entrada : Horario de Entrada Normativo<br>
        Marcacion : Horario de Marcacion registrado en relog<br>
        Salida : Horario de Salida Normativo<br>
        Marcacion : Horario de Salida registrado en relog<br>
        Tard. : Minutos de tardanza, despues de la tolerancia de 5 minutos<br>
        Desc. : Minutos a descontar segun normatividad del Reglamento interno de servidores civiles HVES<br>
        Extra : Minutos despues de su horario de salida, registrado por relog<br>
        Inas. : Inasistencia equivalente a un dia de jornada laboral<br>
            
        
        </span>


        </font>
        
        
        

      <table width="300" border="1" align="center" cellspacing="0" id="marcacion_relog"><colgroup><col><col><col><col></colgroup><thead class="">
                            <tr>
                                <th width="96" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Fecha </th>
                                <th width="120" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                                <th width="65" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Hora</th>
                                <th width="75" align="center" bgcolor="#E9E9E9" class="" scope="col"> Relog</th>

                            </tr>
                        </thead>
                        <tbody id="primer_formato_marcacion" border="1"></tbody></table>
       <span id="espera_mientras_muestra_marcaciones" style="left:inherit" ></span>
        

    </div>

  
 





</div>