<?php
$personal_tempus = json_decode( $this->listarpersonal_tempus );
$tempus_marcaciones = json_decode( $this->marcaciones_personal_tempus );
$ver_ultima_marcacion = json_decode( $this->ver_ultima_marcacion );




?>

<link rel="stylesheet" href="../layout/default/css/themes.min.css">
<style type="text/css">
.modal-header,
    h4,
    .close {
        background-color: #2D4D31;
        color: white !important;
        text-align: center;
        font-size: 30px;
    }
    
    .modal-footer {
        background-color: #D0D0D0
    }
    
    .centrar-dialogo-modal {
        margin-top: 8%;
    }
    
    .flotante {
        display: scroll;
        position: fixed;
        top: 50px;
        background-color: #584D00;
        width: 85.5%;
    }
    
    .resaltado {
        background-color: #FCFBA0;
        border: solid 1px #000000;
        height: 20px;
        width: 170px;
        font-size: 14px;
        color: #000000;
        font-weight: bold;
        vertical-align: 9px
    }
    
    .resaltar_div {
        font-feature-settings: normal;
        font-size: 14px;
        font-weight: bold;
    }
}
</style>
<script type="text/javascript" src="/rrhh/control/public/js/validaciones.js"></script>
<script src="<?= RUTA_PUBLIC_JS; ?>personal_tempus_variables_data64.js"></script>




<div class="row">
    <div class="col-sm-10">
        <div class="panel">

            <div class="panel-heading flotante">
                <span class="panel-title">
                    <div class="row ">
                        <div class="col-md-10">
 
                          <form class="form-inline mostrar" id="frm-actualizar" accept-charset="UTF-8">
                                <div class="form-group ">
                                    <font color="#FFFFFF"><strong>&#124;&#124; REGISTRO DE MARCACIONES DESDE DICIEMBRE DEL 2017  &#124;&#124; </strong> </font>
                                    <font color="#FFFFFF"><strong>&#45; &#124;&#124; FECHA/HORA ULTIMA DESCARGA DE RELOG:    
                                    <span id="msj_carga">

                                    <?php foreach($ver_ultima_marcacion as $ver_ultimo):?>
                                    <?= $ver_ultimo->fecha_ultimo ?>
                                    <?php endforeach;?>

                                    </span>
                                        </strong> </font>
                                </div>
                                <input name="btn_actualizar" type="button" class="btn-primary" id="btn_actualizar" form="frm_impresion1" title="Pulse aqui para ultima actualizacion desde la descarga del relog..." value="Actualizar descarga" onClick="window.location.reload()">
                                <hr>
                             


                            </form>


                        </div>



                    </div>
                </span>
            </div>
</div>



<?php for ( $i = 1; $i <= 4; $i++ ) {echo '<br>';}?>



<div class="panel-body">
    <form id="frm_asistencia_tempus">

        <table width="898" border="0" align="center" cellpadding="0" cellspacing="0" id="ver_marcaciones_en_tabla">
            <tbody>
                <tr>
                  <td width="13" bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                  <td width="15" bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td width="559" bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td width="11" bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td width="282" bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td width="18" bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                  <td bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td style="text-align: center"> MES</td>
                    <td bgcolor="#CBCBCB" style="text-align: center">&nbsp;</td>
                    <td style="text-align: center"> AÑO</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td bgcolor="#CBCBCB">
                        <center>
                            <p>
                                <select name="mes_asistencia" size="1" class="select2-highlighted resaltado" id="mes_asistencia" form="frm_asistencia_tempus" title="Mes en curso" ng-model="month">
                                    <option value="1">ENERO</option>
                                    <option value="2">FEBRERO</option>
                                    <option value="3">MARZO</option>
                                    <option value="4">ABRIL</option>
                                    <option value="5">MAYO</option>
                                    <option value="6">JUNIO</option>
                                    <option value="7">JULIO</option>
                                    <option value="8">AGOSTO</option>
                                    <option value="9">SEPTIEMBRE</option>
                                    <option value="10">OCTUBRE</option>
                                    <option value="11">NOVIEMBRE</option>
                                    <option value="12">DICIEMBRE</option>
                                </select>
                            </p>
                        </center>
                    </td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td align="center" valign="top" bgcolor="#CBCBCB"><input name="anio_asistencia" type="number" class="resaltado" id="anio_asistencia" form="frm_asistencia_tempus" max="2050" min="2016" title="Seleccione año, en las flechitas arriba / abajo " onkeypress='return event.charCode >= 2016 && event.charCode <= 2100'>
                    </td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                  <td colspan="3" align="center" bgcolor="#CBCBCB"><input name="btn_procesar_reporte_masivo" type="button" class="btn-primary" id="btn_procesar_reporte_masivo" form="frm_asistencia_tempus" title="Procesar Reporte" value="Procesar Reporte">
                    </td>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td width="13" bgcolor="#CBCBCB"></td>
                  <td width="15" bgcolor="#CBCBCB"></td>
                    <td colspan="3"><table width="250" border="1" align="center" cellspacing="0" id="marcacion2">
                      <colgroup>
                        <col>
                        <col>
                        <col>
                        <col>
                      </colgroup>
                      <thead class="">
                        <tr>
                          <th width="92" align="center" bgcolor="#E9E9E9" class="" scope="col"> DNI </th>
                          <th width="250" align="center" bgcolor="#E9E9E9" class="" scope="col"> Apellidos Nombres </th>
                          <th width="250" align="center" bgcolor="#E9E9E9" class="" scope="col"> Cargo </th>
                          <th width="92" align="center" bgcolor="#E9E9E9" class="" scope="col"> Fecha </th>
                          <th width="41" align="center" bgcolor="#E9E9E9" class="" scope="col"> Entrada</th>
                          <th width="75" align="center" bgcolor="#E9E9E9" class="" scope="col"> Salida</th>
                        </tr>
                      </thead>
                      <tbody id="resultado2" border="1">
                        <?php foreach($tempus_marcaciones   as $imprimir):?>
                        <tr>
                          <td><?= $imprimir->dni ?></td>
                          <td><?= $imprimir->nombres ?></td>
                          <td><?= $imprimir->cargo ?></td>
                          <td><?= $imprimir->fecha ?></td>
                          <td><?= $imprimir->ingreso ?></td>
                          <td><?= $imprimir->salida ?></td>
                        </tr>
                        <?php endforeach;?>
                      </tbody>
                    </table>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p>
                      <p>&nbsp;</p>
                      
                    </td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB"></td>
                  <td bgcolor="#CBCBCB"></td>
                    <td>




                    </td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
                <tr>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                  <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                    <td bgcolor="#CBCBCB">&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </form>

</div>




</div>

</div>
</div>
</div>