<?php
$listar_documentos = json_decode( $this->listardocumentos );


?>

<div class="page-header">
    <img src="<?= RUTA_PUBLIC_GRA?>legajos_documentos_referenciales.jpg" width="960" height="80" alt=""/>';
</div>

<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Lista de Documento Referenciales Ingresadas:</div>
            <div class="panel-body">
                <select name="select_documentos" size="30" id="select_documentos" form="frm_documentos" title="Documentos y constancias de referencias" style="background-color:#FCFBA0; border: solid 1px #000000; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px; width: 250px;">
                    <?php foreach($listar_documentos  as $ver_documentos):?>
                    <option value="<?= $ver_documentos->idref ?>" id_ref="<?= $ver_documentos->idref ?>" nombre="<?= $ver_documentos->nombre ?>" constancia="<?= $ver_documentos->constancia ?>" <font size="-2" color="#000000"><strong>  <?=$ver_documentos->nombre ?>    </strong>
                        </font>
                    </option>
                    <?php endforeach;?>

                </select>

            </div>
            <div class="panel-footer"> </div>
        </div>

    </div>

    <div class="col-md-2">

        <div class="panel panel-default">
            <div class="panel-heading">Operaciones</div>
            <div class="panel-body">
                <center>
                    <input name="btn_nuevo" type="button" class="btn btn-info btn-lg " id="btn_nuevo" title="Registrar Nuevo Documento" value="- Nuevo - "><br><br>
                    <input name="btn_modificar" type="button" disabled="disabled" class="btn btn-info btn-lg " id="btn_modificar" title="Modificar registro de un documento" value="Modificar"><br><br>
                    <input name="btn_eliminar" type="button" disabled="disabled" class="btn btn-info btn-lg" id="btn_eliminar" title="Eliminar Registro de couemnto" value="Eliminar"><br>
                </center>
            </div>
            <div class="panel-footer"> </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Registre Documento:</div>
            <div class="panel-body">
                <input name="txt_documento" type="text" disabled="disabled" id="txt_documento" form="frm_documentos" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="50" maxlength="150">
                <input name="chk_constancia" type="checkbox" disabled="disabled" id="chk_constancia" form="frm_documentos" title="Documento o Constancia" value="0">
                <label for="chk_constancia" class="label">Es Constancia
          </label>
            </div>
            <div class="panel-footer"><input name="btn_Grabar" type="button" disabled="disabled" class="btn-primary btn-lg" id="btn_Grabar" form="frm_documentos" title="Grabar registro" value="-- Grabar --"> </div>
        </div>
    </div>
</div>