<?php
$listar_tipo_edad  = json_decode( $this->listar_tipo_edad );
?>
 
<div class="page-header">
    <img src="<?= RUTA_PUBLIC_GRA?>legajos_edad_cese.jpg" width="960" height="80" alt=""/>';
</div>




<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Lista de Tipos de Edad registrado:</div>
            <div class="panel-body">
                  <select name="select_documentos" size="30" id="select_documentos" form="frm_documentos" title="Tipo de Eventos" style="background-color:#FCFBA0; border: solid 1px #000000; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px; width: 300px;">
                        <?php foreach($listar_tipo_edad  as $ver):?>
                        <option value="<?= $ver->id ?>" id="<?= $ver->id ?>" genero="<?= $ver->genero ?>"  edad="<?= $ver->edad ?>"  <font size="-2" color="#000000"><strong>  <?=$ver->genero ?>    </strong></font>
                        </option>
                        <?php endforeach;?>

                    </select>
               
            </div>
            <div class="panel-footer"> </div>
        </div>

    </div>

   
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Registre Edad segun corresponda:</div>
            <div class="panel-body">
                 <input name="txt_documento" type="text" disabled="disabled" id="txt_documento" form="frm_documentos" style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:12px; color: #000000; font-weight: bold; vertical-align:14px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="20" maxlength="15">
      
            </div>
            <div class="panel-footer"><input name="btn_Grabar" type="button" disabled="disabled" class="btn-primary btn-lg" id="btn_Grabar" form="frm_documentos" title="Grabar registro" value="-- Grabar --">
        
        
        </div>
        </div>
    </div>
</div>




