<?php
$listar_tipo_meritos_demeritos = json_decode( $this->listar_tipo_meritos_demeritos );
?>

<div class="page-header">
    <img src="<?= RUTA_PUBLIC_GRA?>legajos_meritos_demeritos.jpg" width="960" height="80" alt=""/>';
</div>



<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Lista de Meritos Demeritos y Otros Registrados:</div>
            <div class="panel-body">
                <select name="select_documentos" size="30" id="select_documentos"  title="Documentos Meritos, Demeritos" style="background-color:#FCFBA0; border: solid 1px #000000; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px; width: 300px;">
                    <?php foreach($listar_tipo_meritos_demeritos  as $ver):?>
                    <option value="<?= $ver->id ?>" id="<?= $ver->id ?>" nombre="<?= $ver->nombre ?>" tipo="<?= $ver->tipo ?>" <font size="-2" color="#000000"><strong>  <?=$ver->nombre ?>    </strong>
                        </font>
                    </option>
                    <?php endforeach;?>

                </select>

            </div>
            <div class="panel-footer"> </div>
        </div>

    </div>

    <div class="col-md-2">

        <div class="panel panel-default">
            <div class="panel-heading">Operaciones</div>
            <div class="panel-body">
                <center><input name="btn_nuevo" type="button" class="btn btn-info btn-lg " id="btn_nuevo"   title="Registrar Nuevo Documento" value="- Nuevo - ">

                    <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
<input name="btn_modificar" type="button" disabled="disabled" class="btn btn-info btn-lg " id="btn_modificar"   title="Modificar registro de un documento" value="Modificar">

                    <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
                    <input name="btn_eliminar" type="button" disabled="disabled" class="btn btn-info btn-lg" id="btn_eliminar" form="frm_documentos" title="Eliminar Registro de couemnto" value="Eliminar">

                </center>

            </div>
            <div class="panel-footer"> </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Registre Meritos Demeritos u otros...</div>
            <div class="panel-body"> <input name="txt_documento" type="text" disabled="disabled" id="txt_documento"   style="background-color:#FCFBA0; border: solid 1px #000000; height: 35px; font-size:12px; color: #000000; font-weight: bold; vertical-align:9px" onKeyUp="document.getElementById(this.id).value=document.getElementById(this.id).value.toUpperCase()" size="70" maxlength="150">
                                    <table width="315">
                        <tr>
                            <td width="283"><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_0" form="frm_documentos" value="1">
                      MERITO</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_1" value="2">
                      DESMERITO</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_2" value="3">
                      REMUNERACION PERSONAL</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_3" value="4">
                      REMUNERACION FAMILIAR</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_4" value="5">
                      COMISIONES / INFORMES</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_5" value="6">
                      LICENCIAS</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_6" value="7">
                      ASCENSOS</label>
                            


                            </td>
                        </tr>
                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_7" value="8">
                      VACACIONES</label>
                            


                            </td>
                        </tr>


                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_8" value="9">
                      RESOLUCION DE CONTRATO</label>
                            


                            </td>
                        </tr>


                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_9" value="10">
                     RESOLUCION DE RENUNCIA Y LIQUIDACIONES</label>
                            


                            </td>
                        </tr>

                        <tr>
                            <td><label>
                      <input name="Tipos_meritos" type="radio" disabled="disabled" id="Tipos_meritos_10" value="11">
                     OTROS</label>
                            

                            </td>
                        </tr>




                    </table>


            </div>
            <div class="panel-footer"><input name="btn_Grabar" type="button" disabled="disabled" class="btn-primary btn-lg" id="btn_Grabar" form="frm_documentos" title="Grabar registro" value="-- Grabar --">


            </div>
        </div>
    </div>
</div>

