 
 <?php

 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
        
    }
</style>

 

<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Ambiente Funcional: Usado por personal asistencial</strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container pull-left">

    <div class="form-group"></div>
    <div class="row">
        <div class="col-md-4">
            <span class="form-control bg-default">Ambientes Funcionales Registrados</span>
            <select name="slt_lista_ambiente_funcional" disabled="disabled" class="form-control alert-warning" id="slt_lista_ambiente_funcional" title="Ambientes funcionales registrados"></select>

            <div class="form-group"></div>
            
             <div class="col-xs-12">
                <span class="form-control bg-default">Piso : </span>
            </div>
            <div class="col-xs-12">
                <span class="form-control" id="descripcion_piso" disabled="disabled"></span>
            </div>

            <div class="col-xs-12">
                <span class="form-control bg-default">Bloque Fisico: </span>
                <textarea name="descripcion_bloque" rows="2" disabled="disabled" class="form-control" id="descripcion_bloque"></textarea>
            </div>

            
          <div class="col-xs-12">
                <span class="form-control bg-default">Area Funcional: </span>
                <textarea class="form-control" id="descripcion_area_funcional" disabled="disabled" rows="2"></textarea>
            </div>

            <div class="col-xs-12">
                <span class="form-control bg-default">Descripcion del Ambiente Fisico: </span>
                <textarea class="form-control" id="descripcion_ambiente" disabled="disabled"></textarea>
            </div>
            
            <div class="col-xs-12">
                <span class="form-control bg-default">Servicio : </span>
                <textarea name="descripcion_servicio" disabled="disabled" class="form-control" id="descripcion_servicio"></textarea>
          </div>

            
          <div class="col-xs-12">
                <span class="form-control bg-default">Ambiente Funcional : </span>
            </div>
            <div class="col-xs-12">
                <textarea class="form-control" id="descripcion" disabled="disabled"></textarea>
            </div>
            <div class="form-group"></div>
            
            <!-- Inicio de cupos -->
            <div class="col-xs-12">
                <span class="form-control bg-default">Total Cupos:</span>
            </div>
            <div class="col-xs-12">
                <input name="nro_cupos" type="text" disabled="disabled" required="required" class="form-control alert-warning initialism" id="nro_cupos" title="Total de Cupos">
            </div>
            <div class="form-group"></div>
            
            <div class="col-xs-12">
                <span class="form-control bg-default">Cupos Adicionales:</span>
            </div>
            <div class="col-xs-12">
              <input name="nro_cupos_adicionales" type="text" disabled="disabled" required="required" class="form-control alert-warning" id="nro_cupos_adicionales" title="Total de Cupos Adicionales">
            </div>
            <div class="form-group"></div>

            
            
          <!--<div class="form-group"></div>
             <input name="btn_ir_asignacion_personal" type="button" disabled="disabled" class="btn btn-primary" id="btn_ir_asignacion_personal" value="Asignacion de Personal">
            <div class="form-group"></div>-->

        </div>

       

        <div class="col-md-1">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                        <div class="form-group"></div>
                        <div class="form-group">
                            <center>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_ambiente_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Ambiente Funcional" disabled="disabled"><i class="fa fa-plus"></i></button>
                                <div class="form-group"></div>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_ambiente_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Ambiente Funcional" disabled="disabled"><strong> <i class="fa fa-pencil"></i></strong></button>
                                <div class="form-group"></div>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_ambiente_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Dar de baja Ambiente Funcional" disabled="disabled"><strong> <i class="fa fa-times"></i></strong></button>
                            </center>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
              <div class="form-group"></div>  <div class="form-group"></div>  <div class="form-group"></div>  <div class="form-group"></div>  <div class="form-group"></div>
            <span class="form-control bg-default">Pisos: </span>
            <select name="slt_lista_pisos" class="form-control alert-warning" id="slt_lista_pisos" disabled="disabled"></select>
            <div class="form-group"></div>
            <span class="form-control bg-default">Bloque Fisico :</span>
            <select name="slt_lista_bloques" class="form-control alert-warning" id="slt_lista_bloques" disabled="disabled"></select>
            <div class="form-group"></div>
            <span class="form-control bg-default">Area Funcional :</span>
            <select name="slt_lista_funcionales" class="form-control alert-warning" id="slt_lista_funcionales" disabled="disabled"></select>
            <div class="form-group"></div>

            <span class="form-control bg-default">Ambiente Fisico : </span>
            <select name="slt_lista_ambientes" class="form-control alert-warning" id="slt_lista_ambientes" disabled="disabled"></select>
            <div class="form-group"></div>
            
            <span class="form-control bg-default">Seleccion del Servicio : </span>
            <select name="slt_servicios_registrados" class="form-control alert-warning" id="slt_servicios_registrados"></select>
            <span id="upss"></span><br>
            <span id="departamento"></span>
            
            
            <div class="form-group"></div>
            

            <span class="form-control bg-default">Registrar Ambiente Funcional: </span>
            <input name="txt_ambiente_funcional" type="text" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_ambiente_funcional" title="Describa el Ambiente Funcional">
            <div class="form-group"></div>
            
            <div class="col-xs-6">


            <span class="form-control bg-default">Total Cupos:</span>
            <input name="txt_cupos" type="text" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_cupos" title="Total de Cupos">
            <div class="form-group"></div>

            </div>
            
            <div class="col-xs-6">
            <span class="form-control bg-default">Cupos Adicionales:</span>
            <input name="txt_cupos_adicionales" type="text" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_cupos_adicionales" title="Cupos Adicionales">
            <div class="form-group"></div>
            </div>
            
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_grabar_ambiente_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Ambiente Funcional" disabled="disabled"><strong><span class="fa fa-floppy-o"></span></strong></button>
            
            <input name="btn_ir_asignacion_personal" type="button" disabled="disabled" class="btn btn-primary" id="btn_ir_asignacion_personal" value="Asignacion de Personal">



        </div>

        <span id="espera_de_carga_mantenimiento_funcional"></span>

        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>

    </div>

</div>





<div id="result"></div>