<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>

<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Bloques de Programacion : </strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container  pull-left">
    <div class="col-md-4">
        <span class="form-control bg-default">Bloques:</span>
        <select name="slt_lista_bloques_funcionales" disabled="disabled" class="form-control alert-warning" id="slt_lista_bloques_funcionales"></select>
        <div class="form-group"></div>
        <span class="form-control bg-default">Lista de Ambientes Funcionales :</span>
        <select name="slt_lista_bloques_funcionales_detalle" size="18" disabled="disabled" class="form-control alert-warning" id="slt_lista_bloques_funcionales_detalle"></select>
        <div class="form-group"></div>

        
        <span class="form-control bg-default">Bloques al que pertenece :</span>
        <select name="slt_lista_bloques_funcionales_detalle_muestra_bloque_cabecera" disabled="disabled" class="form-control alert-warning" id="slt_lista_bloques_funcionales_detalle_muestra_bloque_cabecera" size="10"></select>
        <div class="form-group"></div>

        
        
        
        
        
    </div>

    <div class="col-md-1">
        <div class="form-group"></div>
        <div class="box">
            <div class="box-row">
                <div class="box-cell p-x-3 p-y-1 bg-default darken">
                    <div class="form-group"></div>
                    <div class="form-group">
                        <center>
                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar bloque" disabled="disabled"><i class="fa fa-plus"></i></button>
                            <div class="form-group"></div>
                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar bloque" disabled="disabled"><strong> <i class="fa fa-pencil"></i></strong></button>
                            <div class="form-group"></div>
                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Dar de baja bloque" disabled="disabled"><strong> <i class="fa fa-times"></i></strong></button>
                        </center>
                    </div>
                    <div class="form-group"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-5">
        
        <div class="col-xs-4">
           <span class="form-control bg-default text-right">Pisos: </span>
        </div>
        <div class="col-xs-8">
        <select name="slt_lista_pisos" class="form-control alert-warning" id="slt_lista_pisos"></select>
        </div>

        <div class="form-group"></div>
        
        <div class="col-xs-4">
           <span class="form-control bg-default text-right">Bloque Fisico:</span>
        </div>
        <div class="col-xs-8">
            <select name="slt_lista_bloques" class="form-control alert-warning" id="slt_lista_bloques" disabled="disabled"></select>
        </div>                
        
        

        <div class="form-group"></div>

        <span class="form-control bg-default">Registre Nombre del Bloque:</span>
        <input name="txt_bloque_funcional" type="text" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_bloque_funcional" title="Describa el Bloque">

        
        <!--   
        
        <div class="form-group"></div>
        <button class="btn btn-info  btn-lg crear-tooltip form-control" id="btn_crear_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Crear Bloque de Programacion" disabled="disabled">Crear bloque de programación</button>


        <div class="form-group"></div>
        <div class="col-xs-4">
        </div>
        <div class="col-xs-8">
        </div>
        
        -->



        <div class="form-group"></div>

        <span class="form-control bg-default">Seleccionar Ambientes Funcionales:</span>
        <div class="form-group"></div>
        <select name="slt_lista_ambiente_funcional" disabled="disabled" size="10" class="form-control alert-warning" id="slt_lista_ambiente_funcional"></select>
        <div class="form-group"></div>
        

        <span class="form-control bg-default">Seleccion : </span>
        <select name="slt_lista_ambiente_funcional_seleccion" size="10" disabled="disabled" class="form-control alert-warning" id="slt_lista_ambiente_funcional_seleccion"></select>
        <span id="proceso_de_carga"></span>
        <div class="form-group"></div>
        <center>

            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_item_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Item de bloque de programacion" disabled="disabled"><i class="fa fa-times"></i></button>


            <button class="btn btn-info  btn-lg crear-tooltip" id="btn_cerrar_bloque" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Cerrar Bloque de programacion" disabled="disabled"><span class="fa fa-floppy-o"></span></button>
        </center>

        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>




    </div>
    <div class="col-md-3">
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>

        <div class="form-group"></div>
        <div class="form-group"></div>
        <div class="form-group"></div>
        <center>

        </center>


        <div class="form-group"></div>
    </div>

</div>


<div id="result"></div>