 <?php

 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>


<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Mantenedor de Area Funcional: </strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container pull-left">
    
   
    <div class="row">
        <div class="col-md-2">
            <span class="form-control bg-default">Pisos Registrados</span>
            <select name="slt_lista_pisos" size="8" class="form-control alert-warning" id="slt_lista_pisos" disabled="disabled"></select>
            <div class="form-group"></div>
        </div>
        <div class="col-md-4">
            <span class="form-control bg-default">Bloques Registrados</span>
            <select name="slt_lista_bloques" class="form-control alert-warning" id="slt_lista_bloques" disabled="disabled"></select>
            <div class="form-group"></div>
            <span class="form-control bg-default">Area Funcionales Registradas</span>
            <select name="slt_lista_funcionales" size="8" class="form-control alert-warning" id="slt_lista_funcionales" disabled="disabled"></select>
            <div class="form-group"></div>
            <span class="form-control" id="espera_de_carga_funcionales"></span>
            <div class="form-group"></div>
        </div>


        <div class="col-md-1">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                        <div class="form-group"></div>
                        <div class="form-group">
                            <center>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_area_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Area Funcional" disabled="disabled"><i class="fa fa-plus"></i></button>
                                <div class="form-group"></div>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_area_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Area Funcional" disabled="disabled"><strong> <i class="fa fa-pencil"></i></strong></button>
                                <div class="form-group"></div>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_area_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Dar de baja Area Funcional" disabled="disabled"><strong> <i class="fa fa-times"></i></strong></button>
                            </center>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <span class="form-control bg-default">Registrar Area Funcional:</span>
            <input name="txt_area_funcional" type="text" disabled="disabled" required="required" id="txt_area_funcional" class="form-control alert-warning initialism">
            <div class="form-group"></div>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_grabar_area_funcional" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Area Funcional" disabled="disabled"><strong><span class="fa fa-floppy-o"></span></strong></button> </center>

            <span id="espera_de_carga_area_funcional"></span>
        </div>



    </div>

</div>



<div id="result"></div>