 <?php

 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>


<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Gestion de Horarios y turnos </strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container pull-left">

    <div class="row">

        <div class="container">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#horario">Horario</a>
                </li>
                <li><a data-toggle="tab" href="#turno">Turno</a>
                </li>
            </ul>

            <div class="tab-content">
                <div id="horario" class="tab-pane fade in active">
                    <!--   inicio de horario-->
                    <div class="col-md-4">
                        <span class="form-control bg-default">Tipos de horarios Registrados</span>
                        <select name="slt_tipos_horarios_turnos" size="31" class="form-control alert-warning" id="slt_tipos_horarios_turnos" disabled="disabled"></select>
                        <div class="form-group"></div>
                        <span class="form-control" id="espera_de_tipos_horarios_turnos"></span>
                        <div class="form-group"></div>
                    </div>
                    <div class="col-md-1">
                        <div class="box">
                            <div class="box-row">
                                <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                    <div class="form-group"></div>
                                    <div class="form-group">
                                        <center>
                                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_horarios_turnos" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Horarios Turnos" disabled="disabled"><i class="fa fa-plus"></i></button>
                                            <div class="form-group"></div>
                                            <div class="form-group"></div>
                                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_horarios_turnos" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Dar de baja Horarios Turnos" disabled="disabled"><strong> <i class="fa fa-times"></i></strong></button>
                                        </center>
                                    </div>
                                    <div class="form-group"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <span class="form-control bg-default">Seleccion de tipos de Horarios :</span>
                        <select name="slt_tipo_turno_para_horarios" id="slt_tipo_turno_para_horarios" class="form-control alert-warning"></select>
                        <div class="form-group"></div>

                        <span class="form-control bg-default">Horarios:</span>
                        <input name="txt_tipo_horario_turno" type="text" disabled="disabled" required="required" id="txt_tipo_horario_turno" class="form-control alert-warning initialism">
                        <div class="form-group"></div>

                        <span class="form-control bg-default">Hora total:</span>
                        <input name="txt_hora_total" type="number" disabled="disabled" required="required" class="form-control alert-warning " id="txt_hora_total" max="24" min="1" step="1" maxlength="2" oninput="if(this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);">

                        <div class="form-group"></div>

                        <span class="form-control bg-default">Hora Inicio:</span>
                        <input name="txt_hora_inicial" type="time" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_hora_inicial" title="Hora de Inicio del Horario Turno">


                        <div class="form-group"></div>

                        <span class="form-control bg-default">Hora Fin:</span>
                        <input name="txt_hora_fin" type="time" disabled="disabled" required="required" class="form-control alert-warning initialism" id="txt_hora_fin" max="24:00:00" min="01:00:00">
                        <div class="form-group"></div>


                        <span class="form-control bg-default">Horario Abreviado:</span>
                        <input name="txt_hora_abreviado" type="text" disabled="disabled" required="required" id="txt_hora_abreviado" class="form-control alert-warning initialism">
                        <div class="form-group"></div>
                        
                        
                        <span class="form-control bg-default">Observacion:</span>
                        <textarea name="txt_observacion" id="txt_observacion" rows="10" class="form-control alert-warning initialism" disabled="disabled"></textarea>
                        
                        
                        <div class="form-group"></div>

                        
                        

                        <center>
                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_grabar_tipo_horario_turno" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Horario Registrado" disabled="disabled"><strong><span class="fa fa-floppy-o"></span></strong></button> </center>
                        <span id="espera_de_grabacion_tipo_horario_registrado"></span>
                        <div class="form-group"></div>
                        <div class="form-group"></div>
                        <div class="form-group"></div>
                        <div class="form-group"></div>

                    </div>

                </div>



                <!--                    fin de horario-->



                <div id="turno" class="tab-pane fade">
                    <!--                  inicio de turno -->
                    <div class="col-md-3">
                        <span class="form-control bg-default">Tipos de Turnos  Registrados</span>
                        <select name="slt_tipos_horarios" size="8" class="form-control alert-warning" id="slt_tipos_horarios" disabled="disabled"></select>
                        <div class="form-group"></div>
                        <span class="form-control" id="espera_de_tipos_horarios"></span>
                        <div class="form-group"></div>

                        <div class="box-cell p-x-3 p-y-1 bg-default darken">
                            <div class="form-group"></div>
                            <center>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_tipos_horarios" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Tipos de Horarios"><i class="fa fa-plus"></i></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_tipos_horarios" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Tipos de Horarios" disabled="disabled"><strong> <i class="fa fa-pencil"></i></strong></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_tipos_horarios" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Tipos de Horarios" disabled="disabled"><strong> <i class="fa fa-times"></i></strong></button>
                            </center>
                            <div class="form-group"></div>
                            <div class="form-group"></div>
                        </div>

                        <span class="form-control bg-default">Registrar Tipo de Turnos:</span>
                        <input name="txt_tipo_horario" type="text" disabled="disabled" required="required" id="txt_tipo_horario" class="form-control alert-warning initialism">
                        <div class="form-group"></div>
                        <center>
                            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_grabar_tipo_horario" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Piso Registrado" disabled="disabled"><strong><span class="fa fa-floppy-o"></span></strong></button> </center>
                        <span id="espera_de_grabacion_tipo_horario"></span>
                    </div>


                    <!--                 fin de turno    -->
                </div>
            </div>
        </div>



    </div>



    <div id="result"></div>