

<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>


<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Registrar Programacion </strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container pull-left">
    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> UPSS:</span>
        </div>

        <div class="col-md-4">
            <select name="slt_upss_seleccion" class="form-control alert-warning" id="slt_upss_seleccion" title="Seleccione UPSS Respectivo (UPSS: Unidad Prestadora de Servicio)"></select>
            <div class="form-group"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Departamento:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_departamento_seleccion" class="form-control alert-warning" id="slt_departamento_seleccion"></select>
            <div class="form-group"></div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Servicio:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_servicio_seleccion" class="form-control alert-warning" id="slt_servicio_seleccion"></select>
            <div class="form-group"></div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Personal:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_personal_a_seleccionar" class="form-control alert-warning" id="slt_personal_a_seleccionar"></select>
            <div class="form-group"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-light"> Profesion:</span>
            <span class="form-control" id="descripcion_profesion"></span>
            <input name="dni_personal" type="hidden" id="dni_personal">
        </div>

        <div class="col-md-2">
            <span class="form-control bg-default text-light"> Labor:</span>
            <span class="form-control" id="tipo_de_labor"></span>
        </div>


        <div class="col-md-2">
            <span class="form-control bg-default text-light"> Condicion:</span>
            <span class="form-control" id="condicion_laboral"></span>
        </div>
        <div class="form-group"></div>


    </div>


    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Periodo de Programacion:</span>
        </div>
        <div class="col-md-2">
            <select name="slt_mes" size="1" disabled="disabled" class="select2-highlighted form-control alert-warning" id="slt_mes" title="Seleccion de Mes" ng-model="month">
                <option value="1">ENERO</option>
                <option value="2">FEBRERO</option>
                <option value="3">MARZO</option>
                <option value="4">ABRIL</option>
                <option value="5">MAYO</option>
                <option value="6">JUNIO</option>
                <option value="7">JULIO</option>
                <option value="8">AGOSTO</option>
                <option value="9">SEPTIEMBRE</option>
                <option value="10">OCTUBRE</option>
                <option value="11">NOVIEMBRE</option>
                <option value="12">DICIEMBRE</option>
            </select>

            <div class="form-group"></div>
        </div>
        <div class="col-md-2">
            <input name="anio" type="number" disabled="disabled" class="form-control alert-warning" id="anio" max="2050" min="2016" title="Seleccion de Año" onkeypress='return event.charCode >= 2016 && event.charCode <= 2100'>
            <div class="form-group"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <span id="espera_crear_programacion"></span>
            <span> Registrado : </span>
            <span id="upss"></span>
            <span id="departamento"></span>
            <span id="servicio"></span>

        </div>
        <div class="col-md-1">
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_crear_programacion" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Crear programacion...."><i class="fa fa-plus"></i></button>
            <div class="form-group"></div>
            <div class="form-group"></div>
        </div>

        <div class="col-md-1">
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_programacion" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar programacion...."><i class="fa fa-times"></i></button>
            <div class="form-group"></div>
            <div class="form-group"></div>
        </div>

    </div>


    <div class="row">

        <div class="col-md-3">
            <span class="form-control bg-default"> Ambiente Funcional:</span>
            <select name="slt_lista_ambiente_funcional" disabled="disabled" class="form-control alert-warning" id="slt_lista_ambiente_funcional"></select>
            <div class="form-group"></div>
            <span class="form-control bg-default">Actividad </span>
            <select name="slt_actividad" disabled="disabled" class="form-control alert-warning" id="slt_actividad"></select>
            <div class="form-group"></div>
            <span id="actividad" class="form-control"></span>









        </div>

        <div class="col-md-4">
            <span class="form-control bg-default"> Horarios :</span>
            <select name="slt_tipos_horarios_turnos" class="form-control alert-warning" size="12" id="slt_tipos_horarios_turnos" disabled="disabled"></select>

            <span id="tipo_de_turno"></span><br>

            <span id="inicio"></span><br>


            <span id="fin"></span><br>

            <span id="total_horas"></span>
        </div>

        <div class="col-md-3">
            <table width="300">
                <tr>
                    <td><label><input type="radio" name="tipo_de_dia" value="1" id="tipo_de_dia_0"> Dia Especifico</label>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td>
                         <input name="slt_fechas_para_programacion" type="text"   class="form-control clsDatePicker" id="slt_fechas_para_programacion" placeholder="Fecha de Programacion" title="Fecha de Programacion" readonly="readonly">
                    </td>
                </tr>
                <tr>
                    <td><label>
              <input type="radio" name="tipo_de_dia" value="2" id="tipo_de_dia_1">
              Todos los dias: </label>
                    



                    </td>
                    <td> </td>
                </tr>
                <tr>
                    <td>
                        <select name="slt_nombre_dia" disabled="disabled" class="form-control alert-info" id="slt_nombre_dia" title="Seleccion del dia">
                            <option value="0">Seleccione : </option>
                            <option value="LUNES">LUNES</option>
                            <option value="MARTES">MARTES</option>
                            <option value="MIERCOLES">MIERCOLES</option>
                            <option value="JUEVES">JUEVES</option>
                            <option value="VIERNES">VIERNES</option>
                            <option value="SABADO">SABADO</option>
                            <option value="DOMINGO">DOMINGO</option>
                        </select>
                    </td>
                </tr>
            </table>
            <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_registrar_horario_actividad" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Cerrar Programacion.."><span class="glyphicon glyphicon-ok"></span> Cerrar programacion</button>

        </div>
        <div class="col-md-1">
            <?php for ( $i = 1; $i <= 1; $i++ ) {echo '<br>';}?>
            <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_actividad" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar actividad...."><i class="fa fa-times"></i></button>



        </div>
    </div>


    <!--
            <button class="form-control btn btn-info  btn-lg crear-tooltip " id="btn_registrar_horario_actividad" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Registrar Horario / Actividad.."><span class="glyphicon glyphicon-ok"></span></button>
            -->







    <div class="row">
        <?php for ( $i = 1; $i <= 4; $i++ ) {echo '<br>';}?>
        <div class="col-md-3">

            <span id="total_hora_contadas"></span>


            <table width="100%" border="1" cellspacing="1" cellpadding="1">
                <tbody>
                    <tr>
                        <td><span class="form-control bg-default">Lunes : </span>
                        </td>
                        <td><span class="form-control bg-default">Martes : </span>
                        </td>
                        <td><span class="form-control bg-default">Miercoles : </span>
                        </td>
                        <td><span class="form-control bg-default">Jueves : </span>
                        </td>
                        <td><span class="form-control bg-default">Viernes : </span>
                        </td>
                        <td><span class="form-control bg-default">Sabado : </span>
                        </td>
                        <td><span class="form-control bg-default">Domingo : </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_lunes">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_lunes" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_lunes"></span>
                        </td>
                        <td>
                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_martes">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_martes" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_martes"></span>
                        </td>


                        <td>

                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_miercoles">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_miercoles" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_miercoles"></span>



                        </td>
                        <td>

                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_jueves">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_jueves" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_jueves"></span>

                        </td>
                        <td>
                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_viernes">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_viernes" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_viernes"></span>

                        </td>
                        <td>
                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_sabado">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_sabado" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_sabado"></span>

                        </td>
                        <td>
                            <table width="150" border="1" align="left" cellspacing="0" id="turnos_domingo">
                                <colgroup>
                                    <col>
                                    <col>
                                    <col>
                                    <col>
                                </colgroup>
                                <thead class="">
                                    <tr></tr>
                                </thead>
                                <tbody id="contenido_turno_domingo" border="1"></tbody>
                            </table>
                            <span id="espera_mientras_muestra_domingo"></span>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>

    </div>






    <div id="result"></div>