<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>


<div class="container pull-left">
    <div class="row">
        <div class="col-md-7">
            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1  darken" style="background: #DEF0FC;">
                        <div class="form-group"></div>
                        <div class="form-group">
                            &nbsp;&nbsp;<span class="fa fa-hospital-o"></span><strong> &nbsp;Programacion de Sala de Operaciones </strong>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container pull-left">

    <div class="row">

        <div class="col-md-2">
            <span class="form-control bg-default text-left"> Mes / Año:</span>
            <div class="form-group"></div>
        </div>


        <div class="col-md-2">
            <select name="mes" size="1" disabled="disabled" class="select2-highlighted form-control alert-warning" id="mes" title="Seleccion de Mes" ng-model="month">
                <option value="1">ENERO</option>
                <option value="2">FEBRERO</option>
                <option value="3">MARZO</option>
                <option value="4">ABRIL</option>
                <option value="5">MAYO</option>
                <option value="6">JUNIO</option>
                <option value="7">JULIO</option>
                <option value="8">AGOSTO</option>
                <option value="9">SEPTIEMBRE</option>
                <option value="10">OCTUBRE</option>
                <option value="11">NOVIEMBRE</option>
                <option value="12">DICIEMBRE</option>
            </select>
        </div>


        <div class="col-md-1">

            <input name="anio" type="number" disabled="disabled" class="form-control alert-warning" id="anio" max="2050" min="2016" title="Seleccion de Año" onkeypress='return event.charCode >= 2016 && event.charCode <= 2100'>
            <div class="form-group"></div>

        </div>

    
        <div class="col-md-2">
            <button class="btn btn-info  btn-lg crear-tooltip" id="btn_crear_programacion_mensual" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Crear Programacion Fija...."><span class="glyphicon glyphicon-plus"></span>  Crear Programacion</button>
            <div class="form-group"></div>
        </div>


    </div>










    <div class="row">

        <div class="col-md-3">
            <span class="form-control bg-default text-right"> UPSS:</span>
        </div>

        <div class="col-md-4">
            <select name="slt_upss_seleccion" class="form-control alert-warning" id="slt_upss_seleccion" title="Seleccione UPSS Respectivo (UPSS: Unidad Prestadora de Servicio)"></select>
            <div class="form-group"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Departamento:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_departamento_seleccion" class="form-control alert-warning" id="slt_departamento_seleccion"></select>
            <div class="form-group"></div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Servicio:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_servicio_seleccion" class="form-control alert-warning" id="slt_servicio_seleccion"></select>
            <div class="form-group"></div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-3">
            <span class="form-control bg-default text-right"> Ambiente Funcional:</span>
        </div>
        <div class="col-md-4">
            <select name="slt_lista_ambiente_funcional" disabled="disabled" class="form-control alert-warning" id="slt_lista_ambiente_funcional"></select>
            <div class="form-group"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">

            <!--            <span class="form-control" id="descripcion_ambiente"></span>
            <span class="form-control" id="area_funcional"></span>
            <span class="form-control" id="bloque"></span>
            <span class="form-control" id="espera_generacion_grabacion"></span>
-->



        </div>



    </div>

    <div class="row">
        <div class="col-md-4">

            <span class="form-control bg-default">Tipos de Horarios :</span>
            <select name="slt_tipos_horarios_turnos" class="form-control alert-warning" id="slt_tipos_horarios_turnos" disabled="disabled"></select>
            <div class="form-group"></div>

        </div>

        <div class="col-md-2">

            <span class="form-control bg-default">&nbsp;&nbsp; D i a : </span>


            <input name="slt_programacion_mensual" type="date" class="form-control alert-info" disabled="disabled" required="required" id="slt_programacion_mensual" title="fecha de Programacion">


            <span class="form-control bg-default">&nbsp;&nbsp; Dias Frecuentes : </span>
            <select name="slt_nombre_dia" disabled="disabled" class="form-control alert-info" id="slt_nombre_dia" title="Seleccion del dia">
                <option value="0">Seleccione : </option>
                <option value="LUNES">LUNES</option>
                <option value="MARTES">MARTES</option>
                <option value="MIERCOLES">MIERCOLES</option>
                <option value="JUEVES">JUEVES</option>
                <option value="VIERNES">VIERNES</option>
                <option value="SABADO">SABADO</option>
                <option value="DOMINGO">DOMINGO</option>
            </select>







        </div>

        <div class="col-md-5">
            <span class="form-control bg-default">Programacion Registrada:</span>
            <select name="slt_programacion_registrada" class="form-control alert-warning" size="8" id="slt_programacion_registrada" disabled="disabled"></select>
            <div class="form-group"></div>

        </div>


        <div class="col-md-1">
            <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <div class="form-group"></div>
            <button class="btn btn-info  btn-lg crear-tooltip" id="btn_eliminar_programacion" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Programacion Fija...."><i class="fa fa-times"></i></button>



        </div>







    </div>


    <div class="row">

        <div class="col-md-2">
            <span class="form-control bg-default">Lunes : </span>
            <table width="300" border="1" align="left" cellspacing="0" id="turnos_lunes">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead class="">
                    <tr>
                        <th width="40" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                        <th width="35" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Turno </th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> Servicio </th>
                    </tr>
                </thead>
                <tbody id="contenido_turno_lunes" border="1"></tbody>
            </table>
            <span id="espera_mientras_muestra_lunes"></span>
        </div>

        <div class="col-md-2">
            <span class="form-control bg-default">Martes : </span>

            <table width="300" border="1" align="left" cellspacing="0" id="turnos_martes">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead class="">
                    <tr>
                        <th width="40" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                        <th width="35" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Turno </th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> Servicio </th>
                    </tr>
                </thead>
                <tbody id="contenido_turno_martes" border="1"></tbody>
            </table>

        </div>

        <div class="col-md-2">
            <span class="form-control bg-default">Miercoles : </span>

            <table width="300" border="1" align="left" cellspacing="0" id="turnos_miercoles">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead class="">
                    <tr>
                        <th width="40" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                        <th width="35" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Turno </th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> Servicio </th>
                    </tr>
                </thead>
                <tbody id="contenido_turno_miercoles" border="1"></tbody>
            </table>

        </div>


        <div class="col-md-3">
            <span class="form-control bg-default">Jueves : </span>

            <table width="300" border="1" align="left" cellspacing="0" id="turnos_jueves">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead class="">
                    <tr>
                        <th width="40" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                        <th width="35" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Turno </th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> Servicio </th>
                    </tr>
                </thead>
                <tbody id="contenido_turno_jueves" border="1"></tbody>
            </table>

        </div>


        <div class="col-md-3">
            <span class="form-control bg-default">VIERNES : </span>

            <table width="300" border="1" align="left" cellspacing="0" id="turnos_viernes">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead class="">
                    <tr>
                        <th width="40" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Dia </th>
                        <th width="35" align="center" bgcolor="#E9E9E9" class="" scope="col">&nbsp; Turno </th>
                        <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> Servicio </th>
                    </tr>
                </thead>
                <tbody id="contenido_turno_viernes" border="1"></tbody>
            </table>

        </div>







    </div>










</div>









<div id="result"></div>