<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon bg-default">N</span>
                <input type="text" class="form-control crear-tooltip color-yellow" id="buscar" name="buscar" placeholder="Buscar" data-original-title="Buscar" data-toggle="tooltip">
            </div>
        </div>
    </div>
    <div class="col-md-1">
        <div class="form-group">
            <select class="form-control color-yellow" id="anio">
                <?php for ($i = date('Y'); $i >= 2010; $i--) { ?>
                    <option value="<?php echo $i; ?>" <?php echo ($i == date('Y') ? 'selected' : '') ?>><?php echo $i; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?php
            $month = array(0 => 'TODOS', 1 => 'ENERO', 2 => 'FEBRERO', 3 => 'MARZO', 4 => 'ABRIL', 5 => 'MAYO', 6 => 'JUNIO', 7 => 'JULIO', 8 => 'AGOSTO', 9 => 'SETIEMBRE', 10 => 'OCTUBRE', 11 => 'NOVIEMBRE', 12 => 'DICIEMBRE');
            ?>
            <select class="form-control color-yellow" id="mes">
                <?php
                $m = date("m");
                foreach ($month as $k => $v) { ?>
                    <option value="<?php echo $k; ?>" <?php echo ($k == date(0) ? 'selected' : ''); ?>><?php echo $v; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_busqueda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Buscar"><span class="glyphicon glyphicon-search"></span>&nbsp;Buscar</button>
        <div class="form-group"></div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_limpiar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Limpiar Filtros"><span class="glyphicon glyphicon-remove"></span>&nbsp;Limpiar</button>
        <div class="form-group"></div>
    </div>

    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_nuevo" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Nueva"><span class="glyphicon glyphicon-file"></span>&nbsp;Nuevo</button>
        <div class="form-group"></div>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-md-10">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <span class="form-control text-center alert-info texto-negro">Enlaces Gubernamentales</span>
                <div class="panel">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <span class="form-control" id="msj-titular"></span>
                            <table class="table table-striped table-bordered table-hover table-condensed">
                                <tr class="success">
                                    <th>Nro</th>
                                    <th>Fecha</th>
                                    <th>Descripcion</th>
                                    <th>Imagen</th>
                                    <th>Enlace</th>
                                    <th>Orden</th>
                                    <th>Seleccion</th>
                                    <th>Estado</th>
                                    <th>Eleccion</th>
                                    <th>---------</th>
                                    <th>Operador</th>
                                </tr>
                                <tbody id="mostrar-datos-busqueda">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal" id="registrar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="text-right">
                <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
            </div>

            <div class="modal-body">
                <div class="col-xs-12 alert-info">
                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">Descripcion del grafico : (Maximo 100 Caracteres)</span>
                            <input type="text" id="txtDescripcion" class="form-control crear-tooltip color-yellow-texto-large" maxlength="150">
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-xs-12">
                            <label class="alert-default">IMAGEN: (245 X 135 px)</label><br>
                            <input type="file" name="imagen1" id="imagen1" class="form-control alert-warning">
                            <br>
                            <span id="msj_imagen" class="alert-default"></span>
                            <br>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">Enlace, considere el http:// o https:// : </span>
                            <input type="text" id="txtEnlace" class="form-control crear-tooltip color-yellow-texto-large" maxlength="200">
                        </div>
                    </div>
                    <hr>

                    <hr>

                    <div class="row">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>




<div class="modal" id="mostrar_confirmar_eliminar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id">
                <h4 class="modal-title text-center"> -- Confirme Eliminar -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="si_eliminar" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="cancelar" class="btn btn-info">Cancelar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>



<div class="modal" id="crud_imagen1" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id_prensa_imagen">
                <h4 class="modal-title text-center"> -- Fotografia -- </h4>
            </div>
            <div class="modal-body">
                <div class="row alert-info">
                    <div class="col-md-2">
                        <img id="img-imagen1" width="89px" height="101px">
                    </div>
                   <br><br>
                </div>
                <br><br>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>




<div class="modal" id="mostrar_actualizar_orden" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="idorden">
                <h4 class="modal-title text-center"> -- Actualizar Orden -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <input type="number" name="orden" id="orden" min="1" max="99" step="1" value="1">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="grabar_orden" class="btn btn-default">Grabar Orden</button>
                        </div>
                    </div>
                    <div class="col-xs-12 text-center">
                        <span id="msj_imagen"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>