<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon bg-default">N</span>
                <input type="text" class="form-control crear-tooltip color-yellow" id="buscar" name="buscar_emergente" placeholder="Buscar" data-original-title="Buscar" data-toggle="tooltip">
            </div>
        </div>
    </div>
    <div class="col-md-1">
        <div class="form-group">
            <select class="form-control color-yellow" id="anio">
                <?php for ($i = date('Y'); $i >= 2010; $i--) { ?>
                    <option value="<?php echo $i; ?>" <?php echo ($i == date('Y') ? 'selected' : '') ?>><?php echo $i; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?php
            $month = array(0 => 'TODOS', 1 => 'ENERO', 2 => 'FEBRERO', 3 => 'MARZO', 4 => 'ABRIL', 5 => 'MAYO', 6 => 'JUNIO', 7 => 'JULIO', 8 => 'AGOSTO', 9 => 'SETIEMBRE', 10 => 'OCTUBRE', 11 => 'NOVIEMBRE', 12 => 'DICIEMBRE');
            ?>
            <select class="form-control color-yellow" id="mes">
                <?php
                $m = date("m");
                foreach ($month as $k => $v) { ?>
                    <option value="<?php echo $k; ?>" <?php echo ($k == date(0) ? 'selected' : ''); ?>><?php echo $v; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_busqueda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Buscar con los criterios indicados"><span class="glyphicon glyphicon-search"></span>&nbsp;Buscar</button>
        <div class="form-group"></div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_limpiar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Limpiar Filtros"><span class="glyphicon glyphicon-remove"></span>&nbsp;Limpiar</button>
        <div class="form-group"></div>
    </div>

    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_nuevo" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Nueva"><span class="glyphicon glyphicon-file"></span>&nbsp;Nuevo</button>
        <div class="form-group"></div>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-md-10">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <span class="form-control text-center alert-info texto-negro">Administracion de Banner & Slider Principal</span>
                <div class="panel">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <span class="form-control" id="msj-titular"></span>
                            <table class="table table-striped table-bordered table-hover table-condensed">
                                <tr class="success">
                                    <th>Nro</th>
                                    <th>Fecha</th>
                                    <th>Descripcion</th>
                                    <th>Archivo</th>
                                    <th>Imagen</th>
                                    <th>Estado</th>
                                    <th> ------ </th>
                                    <th>Operacion</th>
                                    <th> ----- </th>
                                </tr>
                                <tbody id="mostrar-datos-busqueda">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal" id="registrar_emergente" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="text-right">
                <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
            </div>

            <div class="modal-body">
                <div class="col-xs-12 alert-info">
                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">Descripcion : (Maximo 190 Caracteres)</span>
                            <input type="text" id="txtDescripcion" class="form-control crear-tooltip color-yellow-texto-large initialism" maxlength="150">
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-xs-12">
                            <label class="alert-default">IMAGEN PARA EL BANNER / SLIDER : (1200px (ancho)px  X 350px (Alto))</label><br>
                            <br>

                            <input type="file" name="imagen1" id="imagen1" class="form-control alert-warning">
                            <br>
                            <span id="msj_imagen" class="alert-default"></span>
                            <br>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <span id="msj_grabar" class="alert-default"></span>
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>




<div class="modal" id="mostrar_confirmar_eliminar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id">
                <h4 class="modal-title text-center"> -- Confirme Eliminar -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="si_eliminar" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="cancelar" class="btn btn-info">Cancelar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>



<div class="modal" id="crud_imagen1" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id_prensa_imagen">
                <h4 class="modal-title text-center"> -- Imagen se muestra en Emergente -- </h4>
            </div>
            <div class="modal-body">
                <div class="row alert-info">
                    <div class="col-md-10">
                        <img id="img-imagen1" width="100%" height="100%">
                    </div>

                    <br><br>
                </div>


                <br><br>


            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>