<?php
 


$listar_personal_tempus = json_decode( $this->ver_personal_tempus );
$ver_ultima_marcacion = json_decode( $this->ver_ultima_marcacion );


?>






<style type="text/css">
    .resaltado {
        background-color: #A1EBB4;
        border: solid 1px #000000;
        height: 30px;
        color: #000000;
        font-weight: bold;
        vertical-align: 9px
    }
    
    .color-fondo-columna {
        background-color: #E7E7E7;
    }
    
    .color-fondo-columna-2 {
        background-color: #FFFFFF;
    }
</style>
<link href="/rrhh/control/asistencia/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<div class="container-fluid pull-left">
    <div class="row">
        <center><span class="form-control bg-info"> Registro de Marcaciones en Relog: </span>
        </center>

    </div>
    <br>
    <div class="row bg-default">
        <br>
        <div class="col-md-4">
            <div class="form-group">
                <select name="mes" size="1" class="select2-highlighted form-control resaltado" id="mes" title="Seleccion de Mes" ng-model="month">
                    <option value="1">ENERO</option>
                    <option value="2">FEBRERO</option>
                    <option value="3">MARZO</option>
                    <option value="4">ABRIL</option>
                    <option value="5">MAYO</option>
                    <option value="6">JUNIO</option>
                    <option value="7">JULIO</option>
                    <option value="8">AGOSTO</option>
                    <option value="9">SEPTIEMBRE</option>
                    <option value="10">OCTUBRE</option>
                    <option value="11">NOVIEMBRE</option>
                    <option value="12">DICIEMBRE</option>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <input name="anio" type="number" class="form-control resaltado" id="anio" max="2050" min="2016" title="Seleccion de Año" onkeypress='return event.charCode >= 2016 && event.charCode <= 2100'>
        </div>
        <div class="col-md-3">
            <table width="200">
                <tr>
                    <td><label>
                  <input type="radio" name="tipo_personal" value="1" id="tipo_personal_0">
                  Asistencial</label>
                    

                    </td>
                </tr>
                <tr>
                    <td><label>
                  <input type="radio" name="tipo_personal" value="2" id="tipo_personal_1">
                  Administrativo</label>
                    

                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="row"><br>
        <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_procesar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="procesar datos "><span class="glyphicon glyphicon-ok"></span> Procesar Reporte (de 2 a 3 Minutos)</button>
    </div>
    
    <div class="row">
        <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
       <button class="btn btn-info   btn-lg crear-tooltip " id="btn_descargar_excel" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Descargar Excel"><span class="glyphicon glyphicon-ok"></span> Descargar Excel </button>
        <?php for ( $i = 1; $i <= 2; $i++ ) {echo '<br>';}?>
    </div>

    <div class="row"><br>



        <table width="100%" border="1" align="left" cellspacing="0" id="resultado_marcacion">
            <colgroup>
                <col>
                <col>
                <col>
                <col>
            </colgroup>
            <thead id="cabecera_administrativo">
                <tr>
                    <th width="60" align="right" bgcolor="#E9E9E9" class="" scope="col"> DNI </th>
                    <th width="250" align="center" valign="top" bgcolor="#E9E9E9" class="" scope="col"> APELLIDOS Y NOMBRES </th>
                    <th width="102" align="left" valign="top" bgcolor="#E9E9E9" class="" scope="col"> CARGO</th>
                    <th width="102" align="left" valign="top" bgcolor="#E9E9E9" class="" scope="col"> FECHA</th>
                    <th width="61" align="center" bgcolor="#E9E9E9" class="" scope="col"> DIA</th>
                    <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> INGRESO</th>
                    <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> SALIDA</th>
                </tr>
            </thead>
            <tbody id="listado_marcaciones" border="1">
            </tbody>
        </table>


        
        
          <table width="100%" border="1" align="left" cellspacing="0" id="resultado_marcacion_asistencial">
            <colgroup>
                <col>
                <col>
                <col>
                <col>
            </colgroup>
            <thead id="cabecera_asistencial">
                <tr>
                    <th width="40" align="right" bgcolor="#E9E9E9" class="" scope="col"> DNI </th>
                    <th width="40" align="right" bgcolor="#E9E9E9" class="" scope="col"> APELLIDOS Y NOMBRES </th>
                    <th width="150" align="center" valign="top" bgcolor="#E9E9E9" class="" scope="col"> CARGO </th>
                    <th width="102" align="left" valign="top" bgcolor="#E9E9E9" class="" scope="col"> DIA </th>
                    <th width="61" align="center" bgcolor="#E9E9E9" class="" scope="col"> FECHA </th>
                    <th width="80" align="center" bgcolor="#E9E9E9" class="" scope="col"> HORA </th>
                </tr>
            </thead>
            <tbody id="listado_marcaciones_asistencial" border="1">
            </tbody>
        </table>

        
        
        
        
        <span id="procesar_espera"></span>










    </div>





</div>