<div class="row">
    <?php for ($i = 1; $i <= 6; $i++) {
        echo '<div class="form-group"></div>';
    } ?>

</div>

<div class="row">
    <div class="container">
        <h2>PLANILLA NOMINAL </h2>
        <ul class="nav nav-tabs">
            <li class="active alert-info"><a data-toggle="tab" href="#boletin"><strong>SUBIR PLANILLA NOMINAL</strong></a></li>
          
        </ul>

        <div class="tab-content">
            <div id="boletin" class="tab-pane fade in active">
                <div class="col-xs-12">
                    <div class="col-xs-4">
                        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_nuevo" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Nueva"><span class="glyphicon glyphicon-file"></span>&nbsp;Nuevo</button>
                        <div class="form-group"></div>
                    </div>
                </div>

                <div class="col-xs-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <span class="form-control text-center alert-info texto-negro">Listado de documentos</span>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <span class="form-control" id="msj-titular"></span>
                                <table class="table table-striped table-bordered table-hover table-condensed">
                                    <tr class="success">
                                        <th>Accion</th>
                                        <th>Año</th>
                                        <th>Mes</th>
                                        <th>Descripcion</th>
                                        <th>Archivo</th>
                                        <th>Registro</th>
                                        <th>Enlace</th>
                                    </tr>
                                    <tbody id="mostrar-datos-documentos">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>





            </div>
          
            


            

        </div>
    </div>



</div>


<!-- Para Resoluciones   -->
<div class="modal" id="registrar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="text-right">
                <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
            </div>
            <div class="modal-body">
                <div class="col-xs-12 alert-info">
                    <div class="row">
                        <div class="col-xs-12">



                            <div class="form-group">
                                <select class="form-control color-yellow" id="anio">
                                    <?php for ($i = date('Y'); $i >= 2017; $i--) { ?>
                                        <option value="<?php echo $i; ?>" <?php echo ($i == date('Y') ? 'selected' : '') ?>><?php echo $i; ?></option>
                                    <?php } ?>
                                </select>
                            </div>


                            <div class="form-group">
                                <select class="form-control color-yellow" id="mostrar_mes">
                                </select>
                            </div>

                            

                            <span class="bg-default form-control">Descripcion : </span>
                            <input type="text" id="txtDescripcion" class="form-control crear-tooltip color-yellow-texto-large initialism" maxlength="150">
                           
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12">
                            <hr>
                            <label class="alert-default">Subir Archivo (PDF, Max : 50 Megas, Nombre de Archivo no debe tener caracteres extraños, como Ñ, ACENTOS): </label><br>
                            <input type="hidden" name="nombre_archivo" id="nombre_archivo">
                            <input type="file" name="subir_archivo" id="subir_archivo" class="form-control alert-warning crear-tooltip" data-toggle="tooltip" data-placement="up" title="" data-original-title="Archivo en PDF" data-buttonText="Archivo PDF">
                            <br>
                            <span id="msj_subida"></span>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>


<div class="modal" id="mostrar_confirmar_eliminar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id">
                <h4 class="modal-title text-center"> -- Confirme Eliminar -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="si_eliminar" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="cancelar" class="btn btn-info">Cancelar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

<!-- Fin de Resoluciones Calidad -->


 

 


<div class="modal" id="mostrar_eliminar_categoria" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id_categoria">
                <h4 class="modal-title text-center"> -- Confirme Eliminar Categoria -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="si_eliminar_categoria" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="cancelar" class="btn btn-info">Cancelar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>


<!-- Fin de Categorias -->