<div class="container">

    <div class="row">
        <div class="col-md-3">
            <p class="alert-danger text-center text-bold"> Estimado Usuario : </p>
        </div>
    </div>

    <div class="row">

        <div class="col-md-3 bg-default darken caja text-bold">
            Si llego a esta seccion, es por los siguientes motivos : <br>
            - Su nombre de usuario, expiro <br>
            - No dispone de permiso

        </div>


    </div>
    <div class="form-group"></div>

    <div class="row">
        <div class="col-md-3 bg-default darken caja text-bold">
            Comuniquese con el Area de Estadistica - Informatica.
        </div>
    </div>


</div>