<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon bg-default">N</span>
                <input type="text" class="form-control crear-tooltip color-yellow" id="buscar_nota_prensa" name="buscar_nota_prensa" placeholder="Buscar nota de prensa" data-original-title="Buscar nota de prensa" data-toggle="tooltip">
            </div>
        </div>
    </div>
    <div class="col-md-1">
        <div class="form-group">
            <select class="form-control color-yellow" id="anio">
                <?php for ($i = date('Y'); $i >= 2010; $i--) { ?>
                    <option value="<?php echo $i; ?>" <?php echo ($i == date('Y') ? 'selected' : '') ?>><?php echo $i; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <?php
            $month = array(0 => 'TODOS', 1 => 'ENERO', 2 => 'FEBRERO', 3 => 'MARZO', 4 => 'ABRIL', 5 => 'MAYO', 6 => 'JUNIO', 7 => 'JULIO', 8 => 'AGOSTO', 9 => 'SETIEMBRE', 10 => 'OCTUBRE', 11 => 'NOVIEMBRE', 12 => 'DICIEMBRE');
            ?>
            <select class="form-control color-yellow" id="mes">
                <?php
                $m = date("m");
                foreach ($month as $k => $v) { ?>
                    <option value="<?php echo $k; ?>" <?php echo ($k == date(0) ? 'selected' : ''); ?>><?php echo $v; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_busqueda_total" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Buscar con los criterios indicados"><span class="glyphicon glyphicon-search"></span>&nbsp;Buscar</button>
        <div class="form-group"></div>
    </div>
    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_limpiar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Limpiar Filtros"><span class="glyphicon glyphicon-remove"></span>&nbsp;Limpiar</button>
        <div class="form-group"></div>
    </div>

    <div class="col-md-1">
        <button class="btn btn-info  btn-md form-control  crear-tooltip " id="btn_nuevo" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Nueva Nota de Prensa"><span class="glyphicon glyphicon-file"></span>&nbsp;Nuevo</button>
        <div class="form-group"></div>
    </div>
</div>

<div class="row">
    <div class="col-xs-3 col-md-10">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <span class="form-control text-center alert-info texto-negro">NOTAS DE PRENSA</span>
                <div class="panel">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <span class="form-control" id="msj-prensa"></span>
                            <table class="table table-striped table-bordered table-hover table-condensed">
                                <tr class="success">
                                    <th>Nro</th>
                                    <th>Fecha</th>
                                    <th>Titulo</th>
                                    <th>Sub titulo</th>
                                    <th>Detalle</th>
                                    <th>Imagen</th>
                                    <th>Galerias</th>
                                    <th>Operaciones</th>
                                </tr>
                                <tbody id="mostrar-datos-busqueda">

                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>

            </div>
        </div>
    </div>
</div>




<div class="modal" id="registrar_nota_prensa" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="text-right">
                <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
            </div>

            <div class="modal-body">
                <div class="col-xs-12 alert-info">
                    <div class="row">
                        <div class="col-xs-3">
                            <span class="bg-default form-control">FECHA :</span>
                            <input type="text" class="form-control crear-tooltip color-yellow-texto-large" id="FechaPrensa" data-toggle="tooltip" data-placement="bottom" name="FechaPrensa" placeholder="Fecha Publicacion" value="<?= date("d/m/Y") ?>">
                        </div>
                        <div class="col-xs-6">
                            <span class="bg-default form-control">TITULO : (Maximo 190 Caracteres)</span>
                            <textarea id="TituloPrensa" class="form-control crear-tooltip color-yellow-texto-large initialism" rows="2" maxlength="190"></textarea>
                        </div>
                        <div class="col-xs-3">
                            <span class="bg-default form-control">SUB TITULO :(Maximo 140 Caracteres)</span>
                            <textarea id="SubTitulo" class="form-control crear-tooltip color-yellow-texto-large" rows="2" maxlength="140"></textarea>
                        </div>

                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-xs-6">
                            <span class="bg-default form-control">DETALLE :</span>
                            <textarea id="DetallePrensa" class="form-control crear-tooltip color-yellow-texto-large" rows="3"></textarea>
                        </div>
                        <div class="col-xs-6">
                            <label class="alert-default">IMAGEN : <span id="imagen-nombre"></span></label><br>
                            <input type="file" name="imagen1" id="imagen1" class="form-control alert-warning">
                            <br>
                            <span id="msj_imagen" class="alert-default"></span>
                            <br>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">CONTENIDO :</span>
                            <textarea id="ContenidoPrensa" class="form-control crear-tooltip color-yellow-texto-large" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12">
                            <label class="alert-default form-control">GALERIA DE IMAGENES: <span id="imagen-galeria"> 648 x 432 </span></label>
                            <div class="col-md-12">
                                <button class="btn btn-warning  btn-lg form-control  crear-tooltip" id="IdCambiarGaleria" data-toggle="tooltip" data-placement="up" title="" data-original-title=" Cambiar Galeria ">Cambiar Galeria </button>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-12">
                            <input type="file" name="imagen-multiple" id="imagen-multiple" class="form-control alert-warning" multiple>
                            <br>
                            <span id="msj_galeria_imagenes" class="alert-default"></span>
                            <br><br>

                        </div>

                    </div>
                    <div class="row">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>


<div class="modal" id="modificar_nota_prensa" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <input type="hidden" id="id_nota_prensa">
            <span id="msj_modificacion" class="form-control alert-info text-center"></span>
            <div class="text-right">
                <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
            </div>
            <div class="modal-body">
                <div class="col-xs-12 alert-info">
                    <div class="row">
                        <div class="col-xs-2">
                            <span class="bg-default form-control">FECHA :</span>
                            <input type="text" class="form-control crear-tooltip color-yellow-texto-large" id="FechaPrensam" data-toggle="tooltip" data-placement="bottom" name="FechaPrensam" placeholder="Fecha Publicacion" value="<?= date("d/m/Y") ?>">
                        </div>
                        <div class="col-xs-6">
                            <span class="bg-default form-control">TITULO : (Maximo 190 Caracteres)</span>
                            <textarea id="TituloPrensam" class="form-control crear-tooltip color-yellow-texto-large initialism" rows="2" maxlength="190"></textarea>
                        </div>
                        <div class="col-xs-4">
                            <span class="bg-default form-control">SUB TITULO :(Maximo 140 Caracteres)</span>
                            <textarea id="SubTitulom" class="form-control crear-tooltip color-yellow-texto-large" rows="2" maxlength="140"></textarea>
                        </div>

                    </div>
                    <hr>

                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">DETALLE :</span>
                            <textarea id="DetallePrensam" class="form-control crear-tooltip color-yellow-texto-large" rows="1"></textarea>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-xs-12">
                            <span class="bg-default form-control">CONTENIDO :</span>
                            <textarea id="ContenidoPrensam" class="form-control crear-tooltip color-yellow-texto-large" rows="3"></textarea>
                        </div>
                    </div>

                    <div class="row">
                        <br><br><br>
                    </div>


                    
                    <div class="row">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar_modificacion" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>


<div class="modal" id="crud_imagen1" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id_prensa_imagen">
                <h4 class="modal-title text-center"> -- Imagen se muestra en la portada Principal -- </h4>
            </div>
            <div class="modal-body">
                <div class="row alert-info">
                    <div class="col-md-5">
                        <img id="img-imagen1" width="100%" height="100%">
                    </div>
                    <div class="col-md-7">
                        <label>Puede Cambiar Imagen para Portada</label>
                        <input type="file" name="imagen2" id="imagen2" class="form-control alert-warning">
                        <br>
                        <span id="msj_imagen2" class="alert-default"></span>
                        <br>
                    </div>
                    <br><br>
                </div>


                <br><br>
                <div class="row alert-info">

                    <div class="col-md-3">
                    </div>

                    <div class="col-md-3">
                        <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar_imagen2" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                        <br><br>

                    </div>

                    <div class="col-md-3">
                    </div>


                </div>


            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>




<div class="modal" id="crud_galeria" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="text-right">
            <button type="button" class="btn btn-info" data-dismiss="modal">X</button>
        </div>
        <input type="hidden" id="id_prensa_galeria">
        <div class="modal-content">

            <div class="modal-body">
                <div class="row alert-info">
                    <div class="col-md-5">
                        <table class="table table-striped table-bordered table-hover table-condensed">
                            <tr class="success">
                                <th>Nro</th>
                                <th>Imagen</th>
                            </tr>
                            <tbody id="tbl-mostrar-galeria">
                            </tbody>
                        </table>
                    </div>

                    <div class="col-md-7">
                        <label>Cambiar las Galerias</label>
                        <input type="file" name="imagen-multiple2" id="imagen-multiple2" class="form-control alert-warning" multiple>
                        <br>
                        <span id="msj_galeria_imagenes2" class="alert-default"></span>
                        <br><br>


                        <div class="col-xs-3">
                        </div>

                        <div class="col-xs-5">
                            <button class="btn btn-info  btn-lg form-control  crear-tooltip" id="btn_grabar_galeria2" disabled="disabled" data-toggle="tooltip" data-placement="bottom" title="" data-original-title=" --- Grabar  --- ">GRABAR</button>
                            <br><br> <br><br><br><br> <br><br>

                        </div>

                        <div class="col-xs-3">
                        </div>

                    </div>
                    <br><br>
                </div>





            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>

<div class="modal" id="mostrar_confirmar_eliminar" role="dialog">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header bg-default">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <input type="hidden" id="id_prensa">
                <h4 class="modal-title text-center"> -- Confirme Eliminar Nota de Prensa -- </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <div class="btn-group" role="group" aria-label="...">
                            <button type="button" id="si_eliminar" class="btn btn-danger">Eliminar</button>
                            <button type="button" id="cancelar" class="btn btn-info">Cancelar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="modal-footer bg-default">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>