<div class="row">
    <div class="col-md-3">
        <?php 
                if($this->listar_modulos['success'] !== 0):
            	  echo '<div align="left"><strong><font color="#363636">Usted Tiene acceso a los siguientes Modulos...</font></strong></div><hr>';	
                  foreach($this->listar_modulos['data'] as $v): ?>
        <a href="<?php echo $v['URL'] ?>"><img width="200" height="47" src="<?php echo RUTA_PUBLIC_GRA . $v['IMAGEN'] ?>" alt="..." style="height: 47px;"></a>
        <div class="caption">
            <?php echo $v['DESCRIPCION'] ?>
            <hr>
            <?php endforeach;
                else: ?>
            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-heading">
                        <span class="panel-title"><i class="fa fa-comment-o"></i>&nbsp;Enlace Equivocado:</span>
                    </div>
                    <div class="panel-body">
                        <div class="alert alert-danger">
                            <strong>
                                <?php echo $this->listar_modulos['msg'] ?>
                            </strong>
                        </div>
                    </div>
                </div>
            </div>
            <?php endif;?>
        </div>
    </div>
</div>    
    