<?php
$listar_personal_no_personal = json_decode( $this->listar_personal_no_personal );

?>

<div class="container-fluid  pull-left">
    
    <link rel="stylesheet" href="../layout/default/css/themes.min.css">
  
    <div class="row">
        <div class="col-md-8">

            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="tabla_profesionales">
                    <thead>
                        <tr>
                            <th bgcolor="#DDDBDB">DNI</th>
                            <th bgcolor="#DDDBDB">APELLIDOS Y NOMBRES</th>
                            <th bgcolor="#DDDBDB">PROFESION</th>
                            <th bgcolor="#DDDBDB">COLEGIO PROFESIONAL</th>                            
                            <th bgcolor="#DDDBDB">ESPECIALIDAD</th>                                                        
                            <th bgcolor="#DDDBDB">RNE </th>                                                        
                            <th bgcolor="#DDDBDB">SERVICIO </th>
                        </tr>
                    </thead>
                    <tbody id="tabla_profesionales">
                        <?php foreach($listar_personal_no_personal as $llave => $imprimir ): ?>
                        <tr>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->dni ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->apellidos_nombres ?>
                            </td>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->profesion ?>
                            </td>
                            
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->colegio_profesional ?>
                            </td>
                            
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->especialidad ?>
                            </td>
                            
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->rne ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->servcio ?>
                            </td>

                            
                        </tr>
                        <?php endforeach;   ?>
                    </tbody>
                </table>
            </div>
            
            
        </div>
    </div>
</div>
