<?php
$listar_personal_tercero = json_decode( $this->listar_personal_no_personal );

?>

<div class="container-fluid  pull-left">
    
    <link rel="stylesheet" href="../layout/default/css/themes.min.css">
    <div class="page-header">
    
    </div>
    <div class="row">
        <div class="col-md-10">
            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="tabla_terceros">
                    <thead>
                        <tr>
                            <th bgcolor="#DDDBDB">DNI</th>
                            <th bgcolor="#DDDBDB">RUC</th>
                            <th bgcolor="#DDDBDB">APELLIDOS Y NOMBRES</th>
                            <th bgcolor="#DDDBDB">INICIO</th>
                            <th bgcolor="#DDDBDB">FIN</th>
                            <th bgcolor="#DDDBDB">NOTA INFORMATIVA</th>
                            <th bgcolor="#DDDBDB">NRO DE PEDIDO</th>
                            <th bgcolor="#DDDBDB">META ACTUAL</th>                            
                            <th bgcolor="#DDDBDB">FUENTE FINANCIAMIENTO</th>                                                        
                            <th bgcolor="#DDDBDB">PAO</th>                                                                                    
                            <th bgcolor="#DDDBDB">CCP</th>                                                                                                                
                            <th bgcolor="#DDDBDB">MONTO TOTAL</th>
                            <th bgcolor="#DDDBDB">MES 1</th>                            
                            <th bgcolor="#DDDBDB">MES 2</th>                            
                            <th bgcolor="#DDDBDB">MES 3</th> 
                            <th bgcolor="#DDDBDB">CARGO </th>                                                        
                            <th bgcolor="#DDDBDB">PROFESION</th>
                            <th bgcolor="#DDDBDB">CONDICION</th>                            
                            <th bgcolor="#DDDBDB">TIPO LABOR</th>                                                        
                            <th bgcolor="#DDDBDB">CENTRO DE COSTO</th>                                                                                    
                        </tr>
                        
                    </thead>
                    <tbody id="tabla_terceros">
                        <?php foreach($listar_personal_tercero as $llave => $imprimir ): ?>
                        <tr>
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->dni ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->ruc ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->apellidos_nombres ?>
                            </td>
                            
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->fecha_inicio ?>
                            </td>

                              <td bgcolor="#FCFBA0">
                                <?= $imprimir->fecha_fin ?>
                            </td>
                            
                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->nota_informativa ?>
                            </td>

                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->nro_pedido ?>
                            </td>


                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->meta_actual_usuaria ?>
                            </td>

                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->fuente_financiamiento ?>
                            </td>

                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->pao ?>
                            </td>

                           <td bgcolor="#FCFBA0">
                                <?= $imprimir->ccp ?>
                            </td>

                          

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->monto_total ?>
                            </td>
                            
                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->mes1 ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->mes2 ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->mes3 ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->cargo ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->profesion ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->condicion ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->tipo_labor ?>
                            </td>

                            <td bgcolor="#FCFBA0">
                                <?= $imprimir->centro_costo ?>
                            </td>
                            
                        </tr>
                        <?php endforeach;   ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


