<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sistema de Control de Acceso a Modulos Informaticos del Sistema de Monitoreo de RRHH  - HEVES - Lima - Peru</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes"  />    
     <link href="<?= $_layoutParams['ruta_css'];?>bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="<?= $_layoutParams['ruta_css'];?>pixel-admin.min.css" rel="stylesheet" type="text/css" />    
    <link href="<?= $_layoutParams['ruta_css'];?>pages.min.css" rel="stylesheet" type="text/css" />        
    <link href="<?= $_layoutParams['ruta_css'];?>rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="<?= $_layoutParams['ruta_css'];?>themes.min.css" rel="stylesheet" type="text/css" />
    
    <link href="<?= $_layoutParams['ruta_css'];?>sweetalert.css" rel="stylesheet" type="text/css" />
    
    
    <link rel="shortcut icon" href="<?= $_layoutParams['ruta_img'];?>favicon.ico" type="image/x-icon">
    

    <style type="text/css">
    .modal-header,
    h4,
    .close {
        background-color: #6F6F6F;
        color: white !important;
        text-align: center;
        font-size: 30px;
    }
    
    .modal-footer {
        background-color: #D0D0D0
    }
    
    .centrar-dialogo-modal {
        margin-top: 8%;
    }
    
    .flotante {
        display: scroll;
        position: fixed;
        bottom: 780px;
        background-color: #374247;
        width: 85.5%;
    }
</style>

</head>
    

    
 <body class="theme-default page-signin" > 
    

	<div id="page-signin-bg">
		<div class="overlay"></div>
		 <img src="<?=  RUTA_PUBLIC_GRA.'fondo-inicio.jpg' ?>" alt="">
	</div>
	<div class="msg-error">
	</div>
	<div class="signin-container">
		<div class="signin-info">
          <?php for ( $i = 1; $i <= 23; $i++ ) {echo '<br>';}?>
           <div  > <font color="#EDE7E7">Si no dispone de usuario/contraseña,</font>  <a href="http://soporte-ti.heves.gob.pe/" title="Soporte Tecnico" target="_blank">pulse aqui</a></div><hr>
		</div>
        
		<div class="signin-form">
            	 <div class="signin-info">
			<center>
				 <a href="<?php  echo DIRECCION_URL;   ?>" class="logo"></a>
					<img src="<?= $_layoutParams["ruta_img"];?>logo-heves.png" alt="" style="margin-top: -5px;">
				</a> 
			</center>			
			<div class="slogan">
				<center>Hospital de Emergencias de Villa el Salvador</center>
			</div> 
			<ul>
				<li>Para poder ingresar al sistema, debe de digitar su numero de DNI y clave designada.</li>
			</ul> 
            
		</div>
            
			<form action="index.html" id="form-verificar-ingreso">
				<div class="signin-text">
					<span>SISTEMA MONITOREO DE RRHH </span>
				</div>  

				<div class="form-group w-icon">
					<input name="dni" type="text" autofocus="autofocus" required="required" class="form-control input-lg" id="dni" placeholder="DNI de 8 digitos" autocomplete="off" onkeypress="return valida_ingreso_de_dni(event)" maxlength="8"  >
					<span class="fa fa-user signin-form-icon"></span>
				</div>  

				<div class="form-group w-icon">
					<input name="clave" type="password" required="required" class="form-control input-lg" id="clave" placeholder="Clave">
					<span class="fa fa-lock signin-form-icon"></span>
				</div>  

				<div class="form-actions">
					<input type="submit" disabled="disabled" class="btn-primary btn-lg" id="ingresar" value="Iniciar sesi&oacute;n">
					 
				</div>  
			</form>
			 
			<div class="signin-with" style="min-height:85px;">

			 
			</div>
			
	
		</div>
	
	</div>
	

<script src="<?= $_layoutParams["ruta_js"];?>jquery.min.js"></script>
<script src="<?= $_layoutParams["ruta_js"];?>bootstrap.min.js"></script>
<script src="<?= $_layoutParams["ruta_js"];?>pixel-admin.min.js"></script>
<script src="<?= $_layoutParams['ruta_js'];?>sweetalert.min.js"></script> 
<script src="<?= $_layoutParams['ruta_js'];?>sweetalert.js"></script> 
<script src="<?= BASE_URL ?>views/index/js/verificar.js" type="text/javascript"></script>
<script src="<?=  RUTA_PUBLIC_JS ?>validaciones.js" type="text/javascript"></script>
   
    
    
</body>
</html>