 <?php
 $listar_paises = json_decode( $this->listar_paises );
 $listar_tipos_documentos = json_decode( $this->listar_tipos_documentos );
 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>




<div class="container pull-left ">
    <div class="row">
        <div class="col-md-3">
            <label for="txt_buscar_nombre" class="bg-info form-control">Personal CAS Registrado </label>
            <input name="txt_buscar_nombre" type="text" id="txt_buscar_nombre" class="form-control alert-warning text-secondary initialism" autocomplete="off">
            <select name="select_personal_cas_existente" size="25" id="select_personal_cas_existente" class="form-control">
           </select>
        
            <span id="espera_mientras_carga_personal" class="form-control"></span>

            <div class="form-group">
                <input name="chk_debaja" type="checkbox" id="chk_debaja" title="Mostrar Personal de Baja" value="Personal de baja">&nbsp;Mostrar Personal de Baja
            </div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_empleado"><span class="form-control bg-default glyphicon glyphicon-plus"><strong>  Datos del Registro: </strong>
                    </span>
                    </a>
                    </h4>
                    </div>
                    <div id="datos_empleado" class="panel-collapse collapse in ">
                        <div class="panel-body">
                            <div class="col-xs-12">
                                <table border="1" cellspacing="0" id="estadistica_total" width="100%">
                                    <colgroup>
                                        <col>
                                        <col>
                                        <col>
                                    </colgroup>
                                    <thead id="cabecera_estadistica_tercero">
                                        <tr>
                                            <th width="50%" align="left" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Empleados </th>
                                            <th width="40%" align="right" valign="top" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Total </th>
                                        </tr>
                                    </thead>
                                    <tbody id="mostrar_estadistica_registro" border="1">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="form-group"></div>
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_registros"><span class="form-control bg-default glyphicon glyphicon-plus"><strong> Usuarios (DNI): </strong> </span></a></h4>
                    </div>
                    <div id="datos_registros" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="col-xs-8">
                                Ingreso:
                            </div>
                            <div class="col-xs-4">
                                <span id="dni_usuario"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_registro"></span>
                            </div>


                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Ult. Modifico/hab.:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_modificacion"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_modificacion"></span>
                            </div>

                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Dio de baja:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_de_baja"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_de_baja"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        <div class="col-md-4">




            <div class="form-group">
                <span id="personal_seleccion_nombre" class="form-control bg-info"></span>
                <span id="condicion_personal" class="form-control"></span>
            </div>



            <div class="box">

                <div class="box-row">

                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                        <div class="form-group"></div>

                        <div class="form-group">
                            <center>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_cas" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Personal CAS"><i class="fa fa-plus"></i></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_cas" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Personal CAS"><strong> <i class="fa fa-pencil"></i></strong></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_cas" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Personal CAS "><strong> <i class="fa fa-times"></i></strong></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_habilitar_cas" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Habilitar Personal CAS "><strong> <i class="fa fa-refresh"></i></strong></button>

                                
                            </center>
                        </div>
                        <div class="form-group"></div>
                    </div>

                </div>

            </div>



            <div class="form-group">
                <div class="col-xs-5">
                    <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                    <span id="nombre_pais_registrado" class="form-control "></span>

                </div>
                <div class="col-xs-7">
                    <span class="form-control bg-default">&#9679; Pais :</span>
                    <select name="slt_pais" disabled="disabled" id="slt_pais" title="Seleccione el Pais" class="form-control alter-warning">
                        <option id="174" pais="PERU">PERU</option>
                        <?php foreach($listar_paises as $mostrar):?>
                        <option id="<?=$mostrar->codigo ?>" documento="<?=$mostrar->descripcion ?>">
                            <font size="2">
                                <?=$mostrar->descripcion ?>
                            </font>
                        </option>
                        <?php endforeach;?>
                    </select>
                </div>
            </div>

            <div class="form-group">

                <div class="col-xs-5">
                    <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                    <span id="nombre_documento_registrado" class="form-control "></span>
                </div>

                <div class="col-xs-7">
                    <span class="form-control bg-default">&#9679; Tipo de Documento:</span>

                    <select name="slt_tipo_documento" disabled="disabled" id="slt_tipo_documento" title="Seleccione el Tipo de Documento del Personal" class="form-control alert-warning">
                        <option id="0">Seleccione :</option>
                        <?php foreach($listar_tipos_documentos as $mostrar):?>
                        <option id="<?=$mostrar->codigo ?>" documento="<?=$mostrar->descripcion ?>">
                            <font size="2">
                                <?=$mostrar->descripcion ?>
                            </font>
                        </option>
                        <?php endforeach;?>
                    </select>
                    <span id="msj_tipo_documento"></span>
                </div>

            </div>


            <div class="col-xs-12">
                <div class="form-group">
                    <span id="txt_documento_descripcion" class="form-control bg-default text-left"></span>
                    <input name="txt_nro_documento" type="text" disabled="disabled" class="form-control alert-warning" id="txt_nro_documento">
                    <span id="msj_documento" class="form-control"></span>
                </div>
            </div>





            <div class="col-xs-5">
                <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                <span id="sexo_registrado" class="form-control  "></span>

            </div>
            <div class="col-xs-7">
                <div class="form-group">
                    <span class="form-control bg-default">&#9679; Sexo :</span>
                    
                    <table width="200">
                      <tr>
                        <td><label>
                          <input name="slt_sexo" type="radio" disabled="disabled" id="slt_sexo_0" value="F">
                          FEMENINO</label></td>
                      </tr>
                      <tr>
                        <td><label>
                          <input name="slt_sexo" type="radio" disabled="disabled" id="slt_sexo_1" value="M">
                          MASCULINO</label></td>
                      </tr>
                    </table>
                    
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <span class="form-control bg-default">&#9679; Apellido Paterno: </span>
                    <input name="txt_paterno" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_paterno">
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <span class="form-control bg-default">&#9679; Apellido Materno: </span>
                    <input name="txt_materno" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_materno">
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <span class="form-control bg-default">&#9679; Apellido de Casada: </span>
                    <input name="apellido_casada" type="text" disabled="disabled" class="form-control initialism alert-warning" id="apellido_casada">
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <span class="form-control bg-default">&#9679; Nombres: </span>
                    <input name="txt_nombres" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_nombres">
                </div>
            </div>

            <div class="form-group">

                <div class="col-xs-6">
                    <span class="form-control bg-default">&#9679; Nacimiento: </span>
                </div>
                <div class="col-xs-6">
                    <input name="txt_nacimiento" type="text" disabled="disabled" class="form-control clsDatePicker" id="txt_nacimiento" placeholder="Nacimiento" title="Fecha de Nacimiento del Personal" value="<?=date('d-m-Y', strtotime('now - 20 year')) ?>" readonly="readonly">

                </div>
            </div>

            <div class="form-group">

                <div class="col-xs-6">
                    <span class="form-control bg-default">&#9679; Edad : </span>
                </div>
                <div class="col-xs-6">
                    <input name="txt_edad" type="text" disabled="disabled" class="form-control" id="txt_edad" placeholder="Edad" title="Edad del Personal" readonly="readonly">
                </div>
            </div>

        </div>


        <div class="col-md-4">
            
            
               <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Estado Civil : </span>
            </div>
            <div class="col-xs-6">
                <input type="text" id="estado_civil_registrado" name="estado_civil_registrado" class="form-control" disabled="disabled">
            </div>

            <div class="col-xs-6">
                <select name="slt_estado_civil" id="slt_estado_civil" class="form-control alert-warning"></select>

            </div>
            <div class="form-group"></div>
         

            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Departamento : </span>
            </div>
            <div class="col-xs-6">
                <input type="text" id="nombre_departamento" name="nombre_departamento" class="form-control alert-warning" disabled="disabled">
            </div>

            <div class="col-xs-6">
                <select name="slc_departamento" id="slc_departamento" class="form-control alert-warning"></select>

            </div>
            <div class="form-group"></div>


            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Provincia :</span>
            </div>
            <div class="col-xs-6">
                <input type="text" id="nombre_provincia" name="nombre_provincia" class="form-control" disabled="disabled">
            </div>
            <div class="col-xs-6">
                <select name="slc_provincia" disabled="disabled" class="form-control alert-warning" id="slc_provincia">
                                </select>

            </div>
            <div class="form-group"></div>
            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Distrito : </span>
            </div>

            <div class="col-xs-6">
                <input type="text" id="nombre_distrito" name="nombre_distrito" class="form-control" disabled="disabled">
            </div>

            <div class="col-xs-6">
                <div class="form-group">
                    <select name="slc_distrito" disabled="disabled" class="form-control alert-warning" id="slc_distrito"></select>
                </div>
                </select>
            </div>



            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Direccion Descriptiva : </span>
                <textarea name="txt_area_direccion" disabled="disabled" class="form-control initialism alert-warning" id="txt_area_direccion"></textarea>
            </div>

            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Correo Electronico Personal: </span>
                <input name="txt_correo_electronico" type="text" disabled="disabled" class="form-control alert-warning" id="txt_correo_electronico" value=" @ ">
            </div>


            <div class="col-xs-6">
                <span class="form-control bg-default">&#9679; Telefono Fijo : </span>
            </div>

            <div class="col-xs-6">
                <input name="txt_telefono_fijo" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_telefono_fijo" maxlength="11">
            </div>

            <div class="col-xs-6">
                <span class="form-control bg-default">&#9679; Celular :  </span>
            </div>

            <div class="col-xs-6">
                <input name="txt_telefono_celular" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_telefono_celular" maxlength="9">
            </div>


            <div class="col-xs-6">
                <span class="form-control bg-default">&#9679; Cel. Emergencia :  </span>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <input name="telefono_emergencia" disabled="disabled" class="form-control alert-warning" id="telefono_emergencia" maxlength="9">
                </div>
            </div>

            <div class="col-xs-12">
                <span class="form-control bg-default">&#9679; Observacion:  </span>
                <div class="form-group">
                    <textarea name="observacion" class="form-control initialism alert-warning" rows="4" disabled="disabled" id="observacion"></textarea>
                </div>
            </div>


            <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_datos_personales" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Datos Personales CAS"><span class="glyphicon glyphicon-ok"></span> Grabar</button>
            <span id="espera_grabacion_cas"></span>
        </div>



    </div>


</div>









<div id="result"></div>