 <?php
 $listar_personal_cas_existente = json_decode( $this->listar_personal_cas_existente );
 $listar_paises = json_decode( $this->listar_paises );
 $listar_tipos_documentos = json_decode( $this->listar_tipos_documentos );
$listar_todos_los_motivos = json_decode( $this->listar_motivos );

 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>




<div class="container pull-left ">
    <div class="row">
        <div class="col-md-3">
            <label for="txt_buscar_nombre" class="bg-info form-control">Personal CAS Registrado </label>
            <input name="txt_buscar_nombre" type="text" id="txt_buscar_nombre" class="form-control alert-warning text-secondary initialism" autocomplete="off">
            <select name="select_personal_cas_existente" size="25" id="select_personal_cas_existente" class="form-control">
           </select>
        



            <span id="espera_mientras_carga_personal" class="form-control"></span>

            <div class="form-group">
                <input name="chk_debaja" type="checkbox" id="chk_debaja" title="Mostrar Personal de Baja" value="Personal de baja">&nbsp;Mostrar Personal de Baja
            </div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_empleado"><span class="form-control bg-default glyphicon glyphicon-plus"><strong>  Datos del Registro: </strong>
                    </span>
                    </a>
                    </h4>
                    </div>
                    <div id="datos_empleado" class="panel-collapse collapse in ">
                        <div class="panel-body">
                            <div class="col-xs-12">
                                <table border="1" cellspacing="0" id="estadistica_total" width="100%">
                                    <colgroup>
                                        <col>
                                        <col>
                                        <col>
                                    </colgroup>
                                    <thead id="cabecera_estadistica_tercero">
                                        <tr>
                                            <th width="50%" align="left" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Empleados </th>
                                            <th width="40%" align="right" valign="top" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Total </th>
                                        </tr>
                                    </thead>
                                    <tbody id="mostrar_estadistica_registro" border="1">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="form-group"></div>
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_registros"><span class="form-control bg-default glyphicon glyphicon-plus"><strong> Usuarios (DNI): </strong> </span></a></h4>
                    </div>
                    <div id="datos_registros" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="col-xs-8">
                                Ingreso:
                            </div>
                            <div class="col-xs-4">
                                <span id="dni_usuario"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_registro"></span>
                            </div>


                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Ult. Modifico/hab.:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_modificacion"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_modificacion"></span>
                            </div>

                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Dio de baja:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_de_baja"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_de_baja"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


        <div class="col-md-5">
            <div class="form-group">
                <span id="personal_seleccion_nombre" class="form-control bg-info"></span>
                <span id="condicion_personal" class="form-control"></span>
            </div>
            <span class="form-control bg-default">Inicio &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124;&nbsp; Termino &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124; Nro. Contrato&nbsp;&nbsp;&nbsp;&nbsp;&#124;&nbsp; Adenda </span>
            <div class="form-group">
                <select name="slt_contratos_seleccion" size="5" class="form-control" id="slt_contratos_seleccion"></select>
            </div>

            <div class="box">
                <div class="box-row">
                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                        <div class="form-group"></div>
                        <div class="form-group">
                            <center>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Nuevo Contrato"><i class="fa fa-plus"></i></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Contrato Existente"><strong> <i class="fa fa-pencil"></i></strong></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Contrato (En caso de registrado por error) "><strong> <i class="fa fa-times"></i> </strong></button>
                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_mostrar_adenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Ver Adendas"><strong><span class="glyphicon glyphicon-zoom-in"></span> </strong></button>
                               <button class="btn btn-info  btn-lg crear-tooltip " id="btn_registrar_cese_cas" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Registrar Cese CAS"><strong> <i class="fa fa-refresh"></i></strong></button>
                            </center>
                        </div>
                        <div class="form-group"></div>
                    </div>
                </div>
            </div>


            <div class="col-xs-12">
                <span class="form-control alert-success" id="msj_estado"></span>
                <div class="form-group"></div>
                <span class="form-control bg-default" id="tipo_condicion_laboral">Condicion Laboral:</span>
                <div class="form-group">
                    <select name="slc_condicion_laboral" id="slc_condicion_laboral" class="form-control alert-warning">
                        <option id="0">Seleccione : </option>
                    </select>
                </div>
            </div>
            <div class="col-xs-12">
                <span class="form-control bg-default" id="lugar_origen">Origen de destaque:</span>
                <div class="form-group">
                    <input name="txt_buscar_establecimiento" type="text" id="txt_buscar_establecimiento" class="form-control initialism alert-warning">
                    <div id="lgr_origen_destaque">
                        <select name="slc_origen_destaque" id="slc_origen_destaque" class="form-control alert-warning" size="4">
                            <option id="0">Seleccione : </option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="col-xs-12">
                <textarea name="txt_renaes" cols="3" rows="3" readonly="readonly" class="form-control" id="txt_renaes"></textarea>
                <span id="msj_condicion_laboral" class="form-control"></span>
            </div>
            <div class="form-group"></div>
            <div class="col-xs-4">
                <span class="form-control bg-default text-left">RUC : </span>
                <input name="ruc" type="text" disabled="disabled" class="form-control alert-warning" id="ruc" title="RUC del Titular" maxlength="11">
            </div>
            <div class="col-xs-4">
                <span class="form-control bg-default text-left">Nro. Proceso : </span>
                <input name="txt_nro_proceso" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_nro_proceso">
            </div>
            <div class="col-xs-4">
                <span class="form-control bg-default text-right">Nro. Contrato : </span>
                <input name="txt_nro_contrato" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_nro_contrato">
            </div>
            <div class="form-group"></div>
            <div class="col-xs-4">
                <span class="form-control bg-default text-left">Inicio  : </span>
                <input name="fecha_inicio_contrato" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_inicio_contrato" title="Fecha de Inicio de contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
            </div>
            <div class="col-xs-4">
                <span class="form-control bg-default text-left">Fin : </span>
                <input name="fecha_fin_contrato" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin_contrato" title="Fecha Fin de Contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
            </div>

            <div class="col-xs-4">
                <span class="form-control bg-default text-left">Sueldo : </span>
                <input name="sueldo" type="text" disabled="disabled" class="form-control alert-warning" id="sueldo" title="Registre Sueldo" value="" maxlength="12">
            </div>

            <div class="form-group"></div>

            <div class="col-xs-12">
                <span class="form-control bg-default text-left">Cargo: </span>
                <select name="slt_cargos" size="20" disabled="disabled" id="slt_cargos" title="Cargos seleccionado...." class="form-control"></select>
                <span class="form-control bg-default text-center">Grupo Ocupacional </span>
                <textarea name="grupo_ocupacional" cols="3" rows="2" readonly="readonly" class="form-control" id="grupo_ocupacional"></textarea>
            </div>


        </div>

        <div class="col-md-4">




            <div class="col-xs-12">
                <span class="form-control bg-default text-center">Cadena Programatica </span>
                <select name="slt_cadena_programatica" id="slt_cadena_programatica" title="Seleccion de cadena programatica" class="form-control">
                    </select>
            


                <textarea name="nombre_cadena_programatica" rows="4" readonly="readonly" class="form-control" id="nombre_cadena_programatica"></textarea>
            </div>
            <div class="form-group"></div>

            <div class="col-xs-4">
                <span class="form-control bg-default ">Meta: </span>
                <input name="meta" type="text" disabled="disabled" class="form-control alert-warning" id="meta" title="Registre Meta" value="">

            </div>
            <div class="col-xs-3">
                <span class="form-control bg-default ">Plaza: </span>
                <input name="plaza" type="text" disabled="disabled" class="form-control alert-warning" id="plaza" title="Registre Plaza" value="">

            </div>


            <div class="col-xs-5">
                <span class="form-control bg-default ">Tipo de Labor: </span>
                <table width="100%">
                    <tr>
                        <td><label><input type="radio" name="tipo_de_labor" value="S" id="tipo_de_labor_0">Asistencial</label>
                        </td>
                    </tr>
                    <tr>
                        <td><label><input type="radio" name="tipo_de_labor" value="A" id="tipo_de_labor_1">Administrativo</label>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="col-xs-12">
                <span class="form-control bg-default">Unidad Organica/Organo/Servicio/UPSS: </span>
                <select name="slt_servicio_upss" disabled="disabled" id="slt_servicio_upss" title="Servicio UPSS ..." class="form-control"></select>
                <textarea name="txt_descripcion_upss" class="form-control" rows="6" disabled="disabled" id="txt_descripcion_upss"></textarea>
            </div>
            <div class="form-group"></div>
            <div class="col-xs-12">
                <span class="form-control bg-default">Especialidad : </span>
                <select name="slc_tipo_especialidad" id="slc_tipo_especialidad" class="form-control alert-warning"></select>
                <textarea name="txt_descripcion_especialidad" class="form-control" rows="4" disabled="disabled" id="txt_descripcion_especialidad"></textarea>
                <span class="form-control bg-default">Nro. RNE : </span>
                <input name="rne" type="text" disabled="disabled" class="form-control alert-warning" id="rne" title="Registre RNE" value="S/N">

            </div>
            <div class="form-group"></div>
            <div class="col-xs-12">
                <div class="form-group">
                    <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Contrato"><span class="fa fa-floppy-o"></span>&nbsp; Grabar</button>

                </div>
                <span id="espera_grabacion_contratos"></span>
                <?php for ( $i = 1; $i <= 4; $i++ ) {echo '<br>';}?>
            </div>

        </div>


    </div>


</div>



<div id="modal_registrar_adendas" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <span class="glyphicon glyphicon-text-color"></span>
                <h4 class="modal-title" id="myModalLabel">&nbsp; Registrar Adenda del Contrato:</h4>
            </div>
            <div class="col-md-8 center-block">

                <div id="contenedor_listado_adenda">
                    <span class="form-control bg-default">Inicio  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124; &nbsp;&nbsp;&nbsp;&nbsp;Termino &nbsp;&nbsp;&nbsp;&#124;&nbsp;Nro. Adenda &nbsp;&nbsp;&#124;&nbsp;Estado</span>
                    <div class="form-group">
                        <select name="slc_contratos_adendas" id="slc_contratos_adendas" class="form-control" size="5"> </select>
                    </div>
                    <div class="box">
                        <div class="box-row">
                            <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                <div class="form-group"></div>
                                <div class="form-group">
                                    <center>
                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_adenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Nuevo Adenda"><i class="fa fa-plus"></i></button>
                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_adenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Adenda Existente"><strong> <i class="fa fa-pencil"></i></strong></button>
                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_adenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Anular Adenda (En caso de registrado por error) "><strong> <i class="fa fa-times"></i> </strong></button>
                                    </center>
                                </div>
                                <div class="form-group"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group"></div>
                <div class="col-xs-6">
                    <span class="form-control bg-default text-left">Inicio  : </span>
                    <input name="fecha_inicio_adenda" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_inicio_adenda" title="Fecha de Inicio de adenda" value="<?=date('d-m-Y')?>" readonly="readonly">
                </div>
                <div class="col-xs-6">
                    <span class="form-control bg-default text-left">Fin : </span>
                    <div class="form-group">
                        <input name="fecha_fin_adenda" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin_adenda" title="Fecha Fin de Adenda" value="<?=date('d-m-Y')?>" readonly="readonly">
                    </div>
                </div>
                <div class="form-group"></div>
                <div class="col-xs-12">
                    <span id="msj_estado_adenda" class="form-control"></span>
                </div>


                <div class="form-group"></div>
                <div class="col-xs-6">
                    <span class="form-control bg-default text-left">Nro. Adenda: </span>
                    <input name="txt_nro_adenda" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_nro_adenda">
                </div>
                <div class="col-xs-6">
                    <span class="form-control bg-default text-left">Estado : </span>
                    <div class="form-group">
                        <table width="200">
                            <tr>
                                <td><label>
                              <input type="radio" name="estado_adenda" value="V" id="estado_adenda_0">
                              VIGENTE</label>
                                </td>
                            </tr>
                            <tr>
                                <td><label>
                              <input type="radio" name="estado_adenda" value="T" id="estado_adenda_1">
                              TERMINO</label>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="form-group"></div>

                <div class="col-xs-12">
                    <div class="form-group">
                        <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_adenda" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Adenda"><span class="glyphicon glyphicon-ok"></span>&nbsp; Grabar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



  <div id="modal_registrar_cese_cas" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-desktop"></i>&nbsp; Registrar Cese Personal CAS:</h4>
                </div>
                <div class="col-md-6">
                    <div class="form-group no-margin-hr">
                        <span id="motivo_registrado" class="form-control alert-success"></span>

                        <label class="control-label" for="seleccion-motivo">Motivo:</label>
                        <select name="seleccion-motivo" required="required" class="form-control alert-warning" id="seleccion-motivo" title="Seleccione los tipos de motivos de renuncia (Obligatorio)">
                            <option id="">Seleccionar</option>
                            <?php foreach($listar_todos_los_motivos as $imprimir):?>
                            <option id="<?=$imprimir->idtipomotivo ?>">
                                <font size="2">
                                    <?=$imprimir->motivo ?>
                                </font>
                            </option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="form-group"></div>
                    <span class="form-control bg-default">&#9679; Fin de Servicio:  </span>
                    <input name="fecha_fin_servicio_cese" type="text" class="form-control clsDatePicker" id="fecha_fin_servicio_cese" title="Fecha Fin de Contrato" readonly="readonly" disabled="disabled">
                    <div class="form-group"></div>
                    <span class="form-control bg-default">&#9679; Monto Final:  </span>
                    <input name="txt_monto_total_cese" type="number" required="required" id="txt_monto_total_cese" max="100000" min="0" title="Monto del Servicio" value="0.00" class="form-control alert-warning" disabled="disabled">
                    <div class="form-group"></div>

                    <span class="form-control bg-default">&#9679; Observacion:  </span>
                    <div class="form-group">
                        <textarea name="observacion_servicio_cese" class="form-control initialism alert-warning" rows="6" disabled="disabled" id="observacion_servicio_cese"></textarea>
                    </div>
                    <div class="form-group"></div>
                    <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_registro_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Registro Cese"><span class="fa fa-floppy-o"></span> Grabar Registro Cese</button>
                    <div class="form-group"></div>
                </div>
            </div>
        </div>
    </div>











<div id="result"></div>