<div class="row">
    <img src="<?= RUTA_PUBLIC_GRA?>sistema_de_legajos.jpg" width="961" height="80" alt=""/>';
</div>


<div class="row">
    <hr>
    <div class="col-md-4">
        <h4><span class="label label-info">Enlaces Directos al Sistema de Legajos :</span></h4>
        <hr>

        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>secciones/datos_personales" title="Enlace Directo a Sistema LEGAJOS" target="_self">&#8226; Filiacion e Identificacion del Personal </a>: Datos de Filiacion Personal. </li>
            <li class="list-group-item"><a href="<?=BASE_URL ?>personal/personal_tempus" title="Enlace directo a personal TEMPUS" target="_self"> </a>. </li>

            
            
        </ul>
    </div>

    <div class="col-md-4">
        
                <h4><span class="label label-info">Enlaces Directos al Sistema de Parametros del Sistema de Legajos :</span></h4>
        <hr>

        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/documentos" title="Enlace Directo a Gestion de Documentos" target="_self">&#8226; Gestionar Documentos </a>: Permite gestionar los horarios para todo el personal que labora en el Hospital: asistencial o administrativo. </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/participaciones" title="Enlace Directo a Gestion de Licencias" target="_self">&#8226; Tipo de Participaciones </a>: </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/eventos" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Tipo de Eventos  </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/modalidad" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Tipo de Modalidad </a>: </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/fechas" title="Enlace Directo a Gestion de Feriados" target="_self">&#8226; Tipo de Fechas </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/servicios" title="Enlace Directo a Motivos de Renuncia" target="_self">&#8226; Tipo de Servicios </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/culminacion" title="Enlace Directo a Turnos" target="_self">&#8226; Tipos de Culminacion o Cese o Motivos de Renuncia </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/cargo_laboral" title="Enlace Directo a Turnos" target="_self">&#8226; Tipos de Cargos Laborales </a>: </li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/edad" title="Enlace Directo a Asignacion de Servicios" target="_self">&#8226; Tipos de Edad de Cese (M/F) </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/tipo_educacion" title="Enlace Directo a Asignacion de Servicios" target="_self">&#8226; Tipos de Educacion  </a>: </li>

            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/meritos_demeritos" title="Enlace Directo a Asignacion de Servicios" target="_self">&#8226; Tipos de Meritos, Demeritos, Otros  </a>: </li>

            
            <li class="list-group-item"><a href="<?=BASE_URL ?>parametros/universidades" title="Enlace Directo a Asignacion de Servicios" target="_self">&#8226; Lista de Universidades  </a>: </li>

            
            
            
            
            
            
            
            
            
            
        </ul>

        
        
        
        

    </div>




</div>

 