<div class="row">
    <img src="<?= RUTA_PUBLIC_GRA?>control_de_asistencia.jpg" width="961" height="81" alt=""/>';
</div>


<div class="row">
    <hr>
    <div class="col-md-4">
        <h4><span class="label label-info">Enlaces Directos al Sistema de Asistencia :</span></h4>
        <hr>

        <ul class="list-group">
            <li class="list-group-item"><a href="<?=BASE_URL ?>asistencia/marcaciones" title="Enlace Directo a Personal SIGALEN" target="_self">&#8226; Marcaciones</a>: Nos permite visualizar las marcaciones del personal registrado en RELOG. </li>
            <li class="list-group-item"><a href="<?=BASE_URL ?>asistencia/descuentos" title="Enlace directo a personal TEMPUS" target="_self">&#8226; Descuento </a>: Procesa los descuentos de personal administrativo, asistencial, y permite realizar diversas operaciones. </li>
            <li class="list-group-item"><a href="<?=BASE_URL ?>asistencia/mayor" title="Enlace directo a personal RRHH" target="_self">&#8226; Frecuencia de Marcaciones</a> : Nos muestra el personal que registra de manera reptitiva las marcaciones, con su detalle correspondiente.</li>
            
            <li class="list-group-item"><a href="<?=BASE_URL ?>asistencia/no_marcan" title="Enlace directo a personal Renunciante" target="_self">&#8226; No Marcan N dias </a> : Registro de Personal que no marcan en el relog, segun rango de fecha seleccionado. </li>

            
            
        </ul>
    </div>


</div>

 