 <div class="row">
     <hr>
     <div class="col-md-6">
         <h4><span class="form-control label label-info">Procesos INFORMATICA-04es de la Gestion del Sistema:</span></h4>
         <hr>

         <ul class="list-group">
             <li class="list-group-item"><a href="<?= BASE_URL ?>procesos/usuarios" title="Enlace Directo a Gestion de Usuarios" target="_self">&#8226; Administrar y Gestionar Usuarios </a>: Permite Listar los usuarios, por nombre, unidad, registro, muestra los botones de actualizacion de Modulos, registrar nuevos usuarios y eliminar. </li>
             <li class="list-group-item"><a href="<?= BASE_URL ?>procesos/aplicativos" title="Enlace directo a Gestion de Aplicativos" target="_self">&#8226; Aplicativos</a> : Registra Nuevo aplicativos, Nuevo Menu, Sub menu. Al desarrollar un nuevo modulo, es necesario registrarlo con todas sus caracteristicas para la administracion y asignacion de permisos a usuarios. </li>
         </ul>
     </div>

     <div class="col-md-6">
         <h4><span class="form-control label label-info">Revision de casos:</span></h4>
         <hr>

         <!-- <?php
            foreach ($listarusuarios as  $llave => $imprimir) :
                echo $imprimir->total;
            endforeach;
            ?>
        




         <?php
            foreach ($listarmodulos  as  $llave1 => $imprimir1) :
                echo $imprimir1->total;
            endforeach;

            ?> -->


     </div>



 </div>