<?php


$listar_todos_los_motivos = json_decode( $this->listar_motivos );

?>


<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">


<style>
    .select2-container {
        background-color: #FFFEE1;
    }
    
    .select2-search input {
        background-color: #FFFEE1;
    }
    
    .select2-search {
        background-color: #FFFEE1;
    }
    
    .select2-options {
        background-color: #FFFEE1;
    }
    
    .select2-results {
        background-color: #FFFBD1;
        max-height: 300px;
    }
    
    .select2-drop-mask {}
    
    .s2id_slt_cargos {
        background-color: #FFFEE1;
    }
    
    .select2-choice {
        background-color: #FFFEE1!important;
    }
    
    .select2-results .select2-highlighted {
        background: #3ea211;
    }
    
    .alert {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_azul {
        border: 2px solid #3D8FFF !important;
    }
    
    .color_borde_selector {
        border: 2px solid #FFFCBB !important;
    }
    
    #select2-drop-mask {
        background-color: #FFF9DC;
    }
</style>


<div class="container pull-left ">

    <div class="row">

        <div class="col-md-4">
            <label for="txt_buscar_nombre" class="bg-info form-control">Personas Juridicas: <span id="total_juridicos"> </label>
            <input name="txt_buscar_juridicos" type="text" id="txt_buscar_juridicos" class="form-control alert-warning text-secondary initialism">
            <span class="form-control bg-default">RUC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124; Razon social </span>
            <select name="slt_lista_juridicas" size="20" class="form-control" id="slt_lista_juridicas" title="Relacion de proveedores juridicos asistenciales"></select>
            <span id="espera_carga_personal_juridicos" class="form-control"></span>
            <div class="form-group">
                <input name="chk_debaja_juridicos" type="checkbox" id="chk_debaja_juridicos" title="Mostrar Juridicos de Baja" value="Entidades Juridicas de baja">&nbsp;Entidad Juridica de Baja
            </div>
            <div class="form-group"></div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_empleado"><span class="form-control bg-default glyphicon glyphicon-plus"><strong>  Datos del Registro: </strong></span> </a></h4>
                    </div>
                    <div id="datos_empleado" class="panel-collapse collapse in ">
                        <div class="panel-body">
                            <div class="col-xs-12">
                                <table border="1" cellspacing="0" id="estadistica_total" width="100%">
                                    <colgroup>
                                        <col>
                                        <col>
                                        <col>
                                    </colgroup>
                                    <thead id="cabecera_estadistica_tercero">
                                        <tr>
                                            <th width="50%" align="left" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Empleados </th>
                                            <th width="40%" align="right" valign="top" bgcolor="#E9E9E9" class="" scope="col">&nbsp;Total </th>
                                        </tr>
                                    </thead>
                                    <tbody id="mostrar_estadistica_registro" border="1">
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="form-group"></div>
                    <div class="panel-heading">
                        <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#datos_registros"><span class="form-control bg-default glyphicon glyphicon-plus"><strong> Usuarios (DNI): </strong> </span></a></h4>
                    </div>
                    <div id="datos_registros" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="col-xs-8">
                                Ingreso:
                            </div>
                            <div class="col-xs-4">
                                <span id="dni_usuario"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_registro"></span>
                            </div>


                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Ult. Modifico/hab.:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_modificacion"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_modificacion"></span>
                            </div>

                            <div class="form-group bg-color-gris"></div>
                            <div class="col-xs-8">
                                Dio de baja:
                            </div>

                            <div class="col-xs-4">
                                <span id="dni_usuario_de_baja"></span>
                            </div>
                            <div class="col-xs-8">
                                Fecha:
                            </div>

                            <div class="col-xs-4">
                                <span id="fecha_de_baja"></span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#datos_juridico">(1) Datos Empresa Juridica</a>
                    </li>
                    <li><a data-toggle="tab" href="#contratos_servicios">(2) Contratos y servicios </a>
                    </li>
                    <li><a data-toggle="tab" href="#empleado_empresa_juridica">(3) Empleados Empresa Juridica</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="datos_juridico" class="tab-pane fade in active">
                        <!--- Inicio de Identificacion Juridico -->
                        <div class="col-md-1">
                            <div class="box">
                                <div class="box-row">
                                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                        <div class="form-group"></div>
                                        <div class="form-group">
                                            <center>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Personal Juridico"><i class="fa fa-plus"></i></button>
                                                <div class="form-group"></div>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Personal Juridico"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                <div class="form-group"></div>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Dar de baja Personal Juridico"><strong> <i class="fa fa-times"></i></strong></button>
                                                <div class="form-group"></div>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_habilitar_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Habilitar Juridico dado de baja"><strong> <i class="fa fa-refresh"></i></strong></button>
                                            </center>
                                        </div>
                                        <div class="form-group"></div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="col-xs-12">
                                <span id="personal_juridico_seleccion" class="form-control alert-info"></span>
                                <div class="form-group"></div>
                            </div>
                            <div class="col-xs-5">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">RUC </span>
                                    <input name="ruc" type="text" disabled="disabled" class="form-control alert-warning" id="ruc" maxlength="11" required>
                                    <span id="msj_ruc_juridico"></span>
                                </div>
                            </div>
                            <div class="col-xs-7">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Razon Social:  </span>
                                    <textarea name="txt_razon_social" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_razon_social" rows="3"> </textarea>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Representante Legal:  </span>
                                    <input name="txt_representante_legal" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_representante_legal">
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_juridicos" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Juridicos"><span class="glyphicon glyphicon-ok"></span> Grabar Juridicos</button>
                                <center><span id="espera_grabacion_juridicos"></span>
                                </center>
                            </div>
                        </div>

                        <!--- Fin de Identificacion Juridico -->

                    </div>
                    <div id="contratos_servicios" class="tab-pane fade">



                        <div class="col-md-6">
                            <div class="col-xs-12">
                                <span id="personal_juridico_seleccion_para_servicios" class="form-control alert-info"></span>
                                <div class="form-group"></div>
                            </div>



                            <div class="col-xs-12">
                                <span id="" class="form-control alert-default">Servicios y contratos :</span>
                                <div class="form-group"></div>
                            </div>
                            <div class="col-xs-12">
                                <span class="form-control bg-default"> Inicio  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│&nbsp;  Fin &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│&nbsp; Nota Informativa </span>
                                <select name="slt_listado_servicios" size="5" id="slt_listado_servicios" class="form-control"></select>
                                <div class="box">
                                    <div class="box-row">
                                        <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                            <div class="form-group"></div>
                                            <div class="form-group">
                                                <center>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_juridico_servicio" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Servicio de Proveedor Juridico"><i class="fa fa-plus"></i></button>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_juridico_servicio" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Servicio de Proveedor  Juridico"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_juridico_servicio" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Servicio de Proveedor Juridico"><strong> <i class="fa fa-times"></i></strong></button>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_registrar_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Registrar Cese"><strong> <i class="fa fa-refresh"></i></strong></button>
                                                </center>
                                            </div>
                                            <div class="form-group"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-3">
                                    <span class="form-control bg-default"> Inicio : </span>
                                    <input name="fecha_inicio" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_inicio" title="Fecha de Inicio de contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
                                </div>
                                <div class="col-xs-3">
                                    <span class="form-control bg-default"> Fin : </span>
                                    <input name="fecha_fin" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin" title="Fecha de Fin de contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">Nota Informativa</span>
                                        <textarea name="txt_nota_informativa" id="txt_nota_informativa" rows="4" class="form-control alert-warning initialism" disabled="disabled"></textarea>

                                    </div>

                                </div>
                                <div class="col-xs-12">
                                    <center><span id="msj_nota_informativa_servicios_juridicos" class="form-control"></span>
                                    </center>
                                </div>
                                <div class="form-group"></div>


                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">Cargo:  </span>
                                        <textarea name="txt_cargo" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_cargo" rows="4"> </textarea>
                                    </div>
                                    
<!--                                    <div class="form-group">
                                        <span class="form-control bg-default">Centro de Costo : </span>
                                        <select name="slt_servicio_upss" disabled="disabled" id="slt_servicio_upss" title="Servicio UPSS ..." class="form-control"></select>
                                        <textarea name="txt_descripcion_upss" class="form-control" rows="4" disabled="disabled" id="txt_descripcion_upss"></textarea>
                                    </div>
-->                                    
                                    
                                     <span class="form-control bg-default">Centro de Costo (*): </span>
                                        <select name="slt_centro_costo" disabled="disabled" id="slt_centro_costo" title="Centro de Costo Unidad Organica" class="form-control color_borde"></select>
                                        <div class="form-group"></div>
                                        <span class="form-control bg-default">Centro de Costo: </span>
                                        <textarea name="txt_centro_costo" class="form-control" rows="1" disabled="disabled" id="txt_centro_costo"></textarea>

                                        <span class="form-control bg-default">Centro Sub Costo: </span>
                                        <textarea name="txt_centro_sub_costo" class="form-control" rows="1" disabled="disabled" id="txt_centro_sub_costo"></textarea>
                                        <div class="form-group"></div>


                                        <span class="form-control bg-default">Unidad Organica: </span>
                                        <textarea name="txt_unidad_organica" class="form-control" rows="1" disabled="disabled" id="txt_unidad_organica"></textarea>

                                        <span class="form-control bg-default">Organo: </span>
                                        <textarea name="txt_organica" class="form-control" rows="1" disabled="disabled" id="txt_organica"></textarea>
                                        <div class="form-group"></div>
                                        <textarea class="form-control" disabled="disabled">(*) Interrelacion de Centro de Costo y Unidad Organica, fue realizada por RRHH y OPE</textarea>
                                    
                                    
                                    

                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">

                            <div class="col-xs-6">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Nro. Expediente</span>
                                    <input name="txt_nro_expediente" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_nro_expediente">
                                </div>
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Meta Actual</span>
                                    <input name="txt_meta_actual" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_meta_actual">
                                </div>
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Meta Anterior</span>
                                    <input name="txt_meta_anterior" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_meta_anterior">
                                </div>
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Meta SIGA</span>
                                    <input name="txt_meta_siga" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_meta_siga">
                                </div>

                            </div>


                            <div class="col-xs-6">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">PAO</span>
                                    <input name="txt_pao" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_pao">
                                </div>

                                <div class="form-group">
                                    <span class="form-control bg-default text-left">CCP</span>
                                    <input name="txt_ccp" type="text" disabled="disabled" class="form-control alert-warning initialism" id="txt_ccp">
                                </div>

                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Nros. de Medicos</span>
                                    <input name="txt_nro_medico" type="number" disabled="disabled" class="form-control alert-warning initialism" id="txt_nro_medico">
                                </div>

                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Total Horas</span>
                                    <input name="txt_total_horas" type="number" disabled="disabled" class="form-control alert-warning initialism" id="txt_total_horas">
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <span class="form-control bg-default text-left">Monto Total</span>
                                <input name="txt_monto_total" type="number" required="required" id="txt_monto_total" max="100000" min="0" title="Monto del Servicio" value="" class="form-control alert-warning" disabled="disabled">
                            </div>



                            <div class="col-xs-3">
                                <span class="form-control bg-default text-left">Mes 1 </span>
                                <input name="txt_mes1" type="text" id="txt_mes1" title="Monto del Servicio" value="" class="form-control alert-warning" disabled="disabled">
                            </div>



                            <div class="col-xs-3">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Mes 2 </span>
                                    <input name="txt_mes2" type="text" id="txt_mes2" title="Monto del Servicio" value="" class="form-control alert-warning" disabled="disabled">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <input name="chk_distribuir_en_meses" type="checkbox" id="chk_distribuir_en_meses" title="Distribuir Monto en meses" value="1">&nbsp;Marcar: Distribuir en 2 Meses - Desmarcar (1 Mes)
                                </div>

                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default text-left">Observacion : </span>
                                    <textarea name="txt_observacion" class="form-control alert-warning initialism" rows="5" disabled="disabled" id="txt_observacion"></textarea>
                                </div>


                            </div>


                            <div class="col-xs-12">
                                <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_servicios_juridicos" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Servicios Juridicos"><span class="glyphicon glyphicon-ok"></span> Grabar Servicios</button>
                                <span id="espera_grabacion_servicios_juridicos"></span>
                                <?php for ( $i = 1; $i <= 3; $i++ ) {echo '<br>';}?>

                            </div>
                        </div>

                    </div>

                    <div id="empleado_empresa_juridica" class="tab-pane fade">
                        <div class="col-md-6">
                            <div class="col-xs-12">
                                <input type="hidden" id="id_contrato_servicios_juridicos" name="id_contrato_servicios_juridicos">
                                <input type="hidden" name="ruc_juridico_servicios_juridicos" id="ruc_juridico_servicios_juridicos">
                                <input type="hidden" name="nro_empleados_servicios_juridicos" id="nro_empleados_servicios_juridicos">
                                <span id="descripcion_nro_empleados_por_servicios_juridicos" class="form-control alert-info"></span>
                                <div class="form-group"></div>
                            </div>





                            <div class="col-xs-12">
                                <span class="form-control bg-default">&#9679; Registro de Empleados :</span>
                                <select name="slt_listado_empleados_por_servicios" size="5" id="slt_listado_empleados_por_servicios" class="form-control"></select>
                                <div class="box">
                                    <div class="box-row">
                                        <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                            <div class="form-group"></div>
                                            <div class="form-group">
                                                <center>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_empleado_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Empleados de Entidad Juridica"><i class="fa fa-plus"></i></button>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_empleado_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Empleados de Entidad Juridica"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                    <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_empleado_juridico" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Empleados de Entidad Juridica"><strong> <i class="fa fa-times"></i></strong></button>



                                                </center>
                                            </div>
                                            <div class="form-group"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-5">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">DNI : </span>
                                        <input name="txt_dni_medico" type="text" disabled="disabled" class="form-control alert-warning" id="txt_dni_medico" maxlength="8">

                                    </div>
                                </div>

                                <div class="col-xs-7">
                                    <div class="form-group">
                                        <textarea name="msj_dni_empleado" id="msj_dni_empleado" rows="3" class="form-control text-left"></textarea>
                                    </div>
                                </div>

                                <div class="col-xs-4">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">Apellido Paterno : </span>
                                        <input name="txt_medico_paterno" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_medico_paterno">
                                    </div>
                                </div>

                                <div class="col-xs-4">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">Apellido Materno : </span>
                                        <input name="txt_medico_materno" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_medico_materno">
                                    </div>
                                </div>

                                <div class="col-xs-4">
                                    <div class="form-group">
                                        <span class="form-control bg-default text-left">Nombres : </span>
                                        <input name="txt_medico_nombres" type="text" disabled="disabled" class="form-control initialism alert-warning" id="txt_medico_nombres">
                                    </div>
                                </div>

                                <div class="col-xs-12">
                                    <span class="form-control bg-default text-left">Profesion: </span>
                                </div>

                                <div class="col-xs-12">
                                    <select name="slt_cargos" size="20" disabled="disabled" id="slt_cargos" title="Cargos seleccionado...." class="form-control"></select>
                                </div>

                                <div class="col-xs-12">
                                    <span class="form-control bg-default text-left">Grupo Ocupacional: </span>
                                    <textarea name="grupo_ocupacional" cols="3" rows="2" readonly="readonly" class="form-control alert-warning" id="grupo_ocupacional"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">

                            <div class="col-xs-12">
                                <table width="200">
                                    <tr>
                                        <td><label>
                                       <input type="radio" name="tipo_de_labor" value="S" id="tipo_de_labor_0">
                                       Asistencial</label>
                                        
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label>
                                       <input type="radio" name="tipo_de_labor" value="A" id="tipo_de_labor_1">
                                       Administrativo</label>
                                        
                                        </td>
                                    </tr>
                                </table>



                            </div>



                            <div class="col-xs-12">
                                <div class="form-group">
                                    <div class="form-group">
                                       
                                         
                                            <div class="form-group">
                                            </div>

                                           




                                                <div class="col-xs-12">
                                                    <div class="form-group">
                                                        <span class="form-control bg-default text-left">Observacion : </span>
                                                        <textarea name="txt_observacion_empleados_juridicos" class="form-control alert-warning initialism" rows="4" disabled="disabled" id="txt_observacion_empleados_juridicos"></textarea>
                                                    </div>
                                                    <div class="form-group"></div>


                                                    <div class="col-xs-12">
                                                        <button class="btn btn-info form-control btn-lg crear-tooltip alert-warning" id="btn_grabar_empleados" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Empleados de Juridicos"><span class="glyphicon glyphicon-ok"></span> Grabar Empleados de Entidades Juridicas</button>
                                                        <span id="espera_grabacion_empleados"></span>
                                                    </div>
                                                </div>
                                             
                                         

                                    </div>
                                </div>
                            </div>
                        </div>






                        <div id="modal_registrar_cese_juridicos" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
                            <div class="modal-dialog modal-md">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-desktop"></i>&nbsp; Registrar Cese Entidad Juridica:</h4>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group no-margin-hr">
                                            <span id="motivo_registrado" class="form-control alert-success"></span>

                                            <label class="control-label" for="seleccion-motivo">Motivo:</label>
                                            <select name="seleccion-motivo" required="required" class="form-control alert-warning" id="seleccion-motivo" title="Seleccione los tipos de motivos de renuncia (Obligatorio)">
                                                <option id="">Seleccionar</option>
                                                <?php foreach($listar_todos_los_motivos as $imprimir):?>
                                                <option id="<?=$imprimir->idtipomotivo ?>">
                                                    <font size="2">
                                                        <?=$imprimir->motivo ?>
                                                    </font>
                                                </option>
                                                <?php endforeach;?>
                                            </select>
                                        </div>
                                        <div class="form-group"></div>
                                        <span class="form-control bg-default">&#9679; Fin de Servicio:  </span>
                                        <input name="fecha_fin_servicio_cese" type="text" class="form-control clsDatePicker" id="fecha_fin_servicio_cese" title="Fecha Fin de Contrato" readonly="readonly" disabled="disabled">
                                        <div class="form-group"></div>
                                        <span class="form-control bg-default">&#9679; Monto Final:  </span>
                                        <input name="txt_monto_total_cese" type="number" required="required" id="txt_monto_total_cese" max="100000" min="0" title="Monto del Servicio" value="0.00" class="form-control alert-warning" disabled="disabled">
                                        <div class="form-group"></div>

                                        <span class="form-control bg-default">&#9679; Observacion:  </span>
                                        <div class="form-group">
                                            <textarea name="observacion_servicio_cese" class="form-control initialism alert-warning" rows="6" disabled="disabled" id="observacion_servicio_cese"></textarea>
                                        </div>
                                        <div class="form-group"></div>
                                        <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_registro_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Registro Cese"><span class="fa fa-floppy-o"></span> Grabar Registro Cese</button>

                                        <div class="form-group"></div>




                                    </div>


                                </div>







                            </div>
                        </div>





                        <div id="result"></div>