 <?php
 $listar_personal_cas_existente = json_decode( $this->listar_personal_cas_existente );
 $listar_paises = json_decode( $this->listar_paises );
 $listar_tipos_documentos = json_decode( $this->listar_tipos_documentos );


 ?>
<link href="/rrhh/control/personal/views/layout/default/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<div class="container pull-left ">
    <div class="row">
        <div class="col-md-3">
            <label for="txt_buscar_nombre" class="bg-info form-control">Personal Tercero Registrado </label>
            <input name="txt_buscar_nombre" type="text" id="txt_buscar_nombre" class="form-control alert-warning text-secondary initialism">
            <select name="select_personal_existente" size="35" id="select_personal_existente" class="form-control"></select>
        </div>

        <!-- INICIO DE PESTAÑAS DE DATOS BASICOS - LABORALES - CESE --->

        <div class="col-md-9">
            <div class="container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#inicio_datos">Datos Personal</a>
                    </li>
                    <li><a data-toggle="tab" href="#datos_servicio">Datos de Servicios</a>
                    </li>
                    <li><a data-toggle="tab" href="#cese_tercero">Cese</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="inicio_datos" class="tab-pane fade in active">
                        <div class="col-md-4">
                            <div class="form-group">
                                <span class="form-control bg-default">&#9679; Personal :</span>
                                <span id="personal_seleccion_nombre" class="form-control bg-info"></span>
                            </div>



                            <div class="box">

                                <div class="box-row">

                                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                        <div class="form-group"></div>

                                        <div class="form-group">
                                            <center>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Personal Tercero"><i class="fa fa-plus"></i></button>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Personal Tercero"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Eliminar Personal Tercero"><strong> <i class="fa fa-times"></i></strong></button>
                                            </center>
                                        </div>
                                        <div class="form-group"></div>
                                    </div>

                                </div>

                            </div>



                            <div class="form-group">
                                <div class="col-xs-5">
                                    <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                                    <span id="nombre_pais_registrado" class="form-control "></span>

                                </div>
                                <div class="col-xs-7">


                                    <span class="form-control bg-default">&#9679; Pais :</span>
                                    <select name="slt_pais" disabled="disabled" id="slt_pais" title="Seleccione el Pais" class="form-control">
                                        <option id="174" pais="PERU">PERU</option>
                                        <?php foreach($listar_paises as $mostrar):?>
                                        <option id="<?=$mostrar->codigo ?>" documento="<?=$mostrar->descripcion ?>">
                                            <font size="2">
                                                <?=$mostrar->descripcion ?>
                                            </font>
                                        </option>
                                        <?php endforeach;?>
                                    </select>




                                </div>

                            </div>

                            <div class="form-group">

                                <div class="col-xs-5">
                                    <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                                    <span id="nombre_documento_registrado" class="form-control "></span>
                                </div>

                                <div class="col-xs-7">
                                    <span class="form-control bg-default">&#9679; Tipo de Documento:</span>

                                    <select name="slt_tipo_documento" disabled="disabled" id="slt_tipo_documento" title="Seleccione el Tipo de Documento del Personal" class="form-control">
                                        <option id="0">Seleccione :</option>
                                        <?php foreach($listar_tipos_documentos as $mostrar):?>
                                        <option id="<?=$mostrar->codigo ?>" documento="<?=$mostrar->descripcion ?>">
                                            <font size="2">
                                                <?=$mostrar->descripcion ?>
                                            </font>
                                        </option>
                                        <?php endforeach;?>
                                    </select>
                                    <span id="msj_tipo_documento"></span>
                                </div>

                            </div>


                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span id="txt_documento_descripcion" class="form-control bg-default text-left"></span>
                                    <input name="txt_nro_documento" type="text" disabled="disabled" class="form-control" id="txt_nro_documento">
                                </div>
                            </div>





                            <div class="col-xs-5">
                                <span class="form-control bg-default glyphicon glyphicon-pushpin"> Registrado</span>
                                <span id="sexo_registrado" class="form-control "></span>

                            </div>


                            <div class="col-xs-7">
                                <div class="form-group">
                                    <span class="form-control bg-default">&#9679; Sexo :</span>
                                    <select name="slt_sexo" disabled="disabled" id="slt_sexo" title="Sexo del Personal" class="form-control">
                                        <option lc_sexo="0">Sexo</option>
                                        <option lc_sexo="1">MASCULINO</option>
                                        <option lc_sexo="2">FEMENINO</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default">&#9679; Apellido Paterno: </span>
                                    <input name="txt_paterno" type="text" disabled="disabled" class="form-control initialism" id="txt_paterno">
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default">&#9679; Apellido Materno: </span>
                                    <input name="txt_materno" type="text" disabled="disabled" class="form-control initialism" id="txt_materno">
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default">&#9679; Apellido de Casada: </span>
                                    <input name="apellido_casada" type="text" disabled="disabled" class="form-control initialism" id="apellido_casada">
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <div class="form-group">
                                    <span class="form-control bg-default">&#9679; Nombres: </span>
                                    <input name="txt_nombres" type="text" disabled="disabled" class="form-control initialism" id="txt_nombres">
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-xs-6">
                                    <span class="form-control bg-default">&#9679; Nacimiento: </span>
                                </div>
                                <div class="col-xs-6">
                                    <input name="txt_nacimiento" type="text" disabled="disabled" class="form-control clsDatePicker" id="txt_nacimiento" placeholder="Nacimiento" title="Fecha de Nacimiento del Personal" value="<?=date('d-m-Y', strtotime('now - 20 year')) ?>" readonly="readonly">

                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-xs-6">
                                    <span class="form-control bg-default">&#9679; Edad : </span>
                                </div>
                                <div class="col-xs-6">
                                    <input name="txt_edad" type="text" disabled="disabled" class="form-control" id="txt_edad" placeholder="Edad" title="Edad del Personal" readonly="readonly">
                                </div>
                            </div>

                        </div>

                        <div class="col-md-4">

                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Departamento : </span>
                            </div>
                            <div class="col-xs-6">
                                <select name="slc_departamento" id="slc_departamento" class="form-control">
                                    <option id="0">Seleccione : </option>
                                </select>
                            </div>


                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Provincia :</span>
                            </div>
                            <div class="col-xs-6">
                                <select name="slc_provincia" disabled="disabled" class="form-control" id="slc_provincia">
                                    <option id="0">Seleccione : </option>
                                </select>
                            </div>


                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Distrito : </span>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <select name="slc_distrito" disabled="disabled" class="form-control" id="slc_distrito"></select>
                                </div>
                                </select>
                            </div>

                            <div class="col-xs-12">
                                <span class="form-control bg-default">&#9679; Direccion Descriptiva : </span>
                                <textarea name="txt_area_direccion" disabled="disabled" class="form-control initialism" id="txt_area_direccion"></textarea>
                            </div>

                            <div class="col-xs-12">
                                <span class="form-control bg-default">&#9679; Correo Electronico Personal: </span>
                                <input name="txt_correo_electronico" type="text" disabled="disabled" class="form-control" id="txt_correo_electronico" value=" @ ">
                            </div>


                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Telefono Fijo : </span>
                            </div>

                            <div class="col-xs-6">
                                <input name="txt_telefono_fijo" type="text" disabled="disabled" class="form-control initialism" id="txt_telefono_fijo">
                            </div>

                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Celular :  </span>
                            </div>

                            <div class="col-xs-6">
                                <input name="txt_telefono_celular" type="text" disabled="disabled" class="form-control initialism" id="txt_telefono_celular">
                            </div>


                            <div class="col-xs-6">
                                <span class="form-control bg-default">&#9679; Cel. Emergencia :  </span>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <input name="telefono_emergencia" class="form-control" disabled="disabled" id="telefono_emergencia">
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <span class="form-control bg-default">&#9679; Observacion:  </span>
                                <div class="form-group">
                                    <textarea name="observacion" class="form-control initialism" rows="4" disabled="disabled" id="observacion"></textarea>
                                </div>
                            </div>

                            <div class="col-xs-12">
                                <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_datos_personales" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Datos Personales Terceros"><span class="glyphicon glyphicon-ok"></span> Grabar</button>
                                <span id="espera_grabacion_cas"></span>


                            </div>
                        </div>



                    </div>
                    <div id="datos_servicio" class="tab-pane fade">
                        <!--- Inicio de DATOS DE SERVICIO -->


                        <div class="container">
                            
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#info_servicio">Informacion del Servicio</a>
                                </li>
                                <li><a data-toggle="tab" href="#carrera_colegio">Carrera y colegio profesional</a>
                                </li>
                               
                            </ul>

                            <div class="tab-content">
                                <div id="info_servicio" class="tab-pane fade in active">
                                     <!--- informacion del servicio --->
                                    
                                                    <div class="col-md-5">
                                    <span class="form-control bg-default">&#9679; Personal Tercero :</span>
                                    <span id="personal_seleccion_contrato" class="form-control bg-info"></span>
                                    <span class="form-control bg-default">Nro. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124;&nbsp; Inicio &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124; Termino&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#124;&nbsp; Cese</span>
                                    <div class="form-group">
                                        <select name="slt_contratos_seleccion" size="5" class="form-control" id="slt_contratos_seleccion"></select>
                                    </div>

                                    <div class="box">
                                        <div class="box-row">
                                            <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                                <div class="form-group"></div>
                                                <div class="form-group">
                                                    <center>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Nuevo Contrato"><i class="fa fa-plus"></i></button>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Contrato Existente"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Anular Contrato (En caso de registrado por error) "><strong> <i class="fa fa-times"></i> </strong></button>
                                                    </center>
                                                </div>
                                                <div class="form-group"></div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="col-xs-5">
                                        <span class="form-control bg-default text-right">Nro. Orden : </span>
                                    </div>
                                    <div class="col-xs-7">
                                        <input name="txt_nro_contrato" type="text" disabled="disabled" class="form-control initialism" id="txt_nro_contrato">
                                    </div>
                                    <div class="col-xs-5">
                                        <span class="form-control bg-default text-right">Inicio  : </span>
                                    </div>
                                    <div class="col-xs-7">
                                        <input name="fecha_inicio_contrato" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_inicio_contrato" title="Fecha de Inicio de contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
                                    </div>

                                    <div class="col-xs-5">
                                        <span class="form-control bg-default text-right">Fin : </span>
                                    </div>
                                    <div class="col-xs-7">
                                        <div class="form-group">
                                            <input name="fecha_fin_contrato" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin_contrato" title="Fecha Fin de Contrato" value="<?=date('d-m-Y')?>" readonly="readonly">
                                        </div>
                                    </div>
                                    <div class="col-xs-7">
                                        <span class="form-control bg-default text-right">Fecha de Desvinculacion : </span>
                                    </div>
                                    <div class="col-xs-5">
                                        <div class="form-group">
                                            <input name="fecha_fin_desvinculacion" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin_desvinculacion" title="Fecha desvinculacion" value="<?=date('d-m-Y')?>" readonly="readonly">
                                        </div>
                                    </div>


                                    <div class="col-xs-12">
                                        <span class="form-control bg-default text-left">Descripción del Servicio : </span>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <textarea name="txt_descripcion_servicio" rows="3" disabled="disabled" required="required" id="txt_descripcion_servicio" class="form-control"></textarea>
                                        </div>

                                    </div>

                                    <div class="col-xs-12">
                                        <span class="form-control bg-default text-left">Fuente de Financiamiento : </span>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <select name="slt_fuentes_financiamiento" class="form-control" id="slt_fuentes_financiamiento"></select>
                                        </div>

                                    </div>







                                </div>

                                <div class="col-md-4">

                                    <div class="col-xs-4">
                                        <span class="form-control bg-default text-right">RUC : </span>
                                    </div>
                                    <div class="col-xs-8">
                                        <input name="ruc" type="text" disabled="disabled" class="form-control" id="ruc" title="RUC del Titular">
                                    </div>
                                    <div class="form-group"></div>

                                    <div class="col-xs-4">
                                        <span class="form-control bg-default text-right">Cargo : </span>
                                    </div>

                                    <div class="col-xs-8">
                                        <select name="slt_cargos" size="20" disabled="disabled" id="slt_cargos" title="Cargos seleccionado...." class="form-control"></select>
                                    </div>

                                    <div class="col-xs-12">
                                        <span class="form-control bg-default text-center">Grupo Ocupacional </span>
                                        <textarea name="grupo_ocupacional" cols="3" rows="2" readonly="readonly" class="form-control" id="grupo_ocupacional"></textarea>
                                    </div>







                                    <div class="form-group"></div>
                                    <div class="col-xs-7">
                                        <span class="form-control bg-default text-right">Monto Orden Servicio: </span>
                                    </div>
                                    <div class="col-xs-5">
                                        <input name="sueldo" type="text" disabled="disabled" class="form-control" id="sueldo" title="Registre Sueldo" value="">
                                    </div>
                                    <div class="col-xs-7">
                                        <span class="form-control bg-default text-right">Tipo Empleado: </span>
                                    </div>
                                    <div class="col-xs-5">
                                        <select name="slt_asistencial" disabled="disabled" id="slt_asistencial" title="Asistencial / Administrativo" class="form-control">
                                            <option lc_tipo_servicio="0">Seleccione</option>
                                            <option lc_tipo_servicio="S">ASISTENCIAL</option>
                                            <option lc_tipo_servicio="A">ADMINISTRATIVO</option>
                                        </select>
                                    </div>
                                    <div class="form-group"></div>
                                    <div class="col-xs-12">
                                        <span class="form-control bg-default">Centro de Costo: </span>
                                        <select name="slt_servicio_upss" disabled="disabled" id="slt_servicio_upss" title="Servicio UPSS ..." class="form-control"></select>
                                        <textarea name="txt_descripcion_upss" class="form-control" rows="6" disabled="disabled" id="txt_descripcion_upss"></textarea>
                                    </div>
                                    <div class="form-group"></div>
                                    <div class="col-xs-12">
                                        <span class="form-control bg-default">Especialidad : </span>
                                        <select name="slc_tipo_especialidad" id="slc_tipo_especialidad" class="form-control"></select>
                                        <textarea name="txt_descripcion_especialidad" class="form-control" rows="4" disabled="disabled" id="txt_descripcion_especialidad"></textarea>
                                        <span class="form-control bg-default">Nro. RNE : </span>
                                        <input name="rne" type="text" disabled="disabled" class="form-control" id="rne" title="Registre RNE" value="S/N">

                                    </div>
                                    <div class="form-group"></div>
                                    <div class="col-xs-12">
                                        <div class="form-group">



                                            <!--<button type="button" class="form-control btn btn-primary" data-container="body" data-toggle="popover" data-state="primary" data-placement="top" data-content="Grabacion Conforme de registros Laborales" data-title="Primary title"><span class="fa fa-floppy-o"></span>&nbsp; Grabar</button>-->



                                            <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_contrato" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Contrato"><span class="fa fa-floppy-o"></span>&nbsp; Grabar</button>




                                        </div>
                                        <span id="espera_grabacion_contratos"></span>
                                        <?php for ( $i = 1; $i <= 4; $i++ ) {echo '<br>';}?>
                                    </div>

                                </div>

                                    
                                    
                                    <!--- Fin del servicio --->

                                </div>
                                <div id="carrera_colegio" class="tab-pane fade">
                                    <!--- informacion de la carrera y colegio  --->
                                    
                                    
                                <div class="col-md-4">
                                    <span class="form-control bg-default">&#9679; Personal :</span>
                                    <span id="personal_seleccion_carrera" class="form-control bg-info"></span>
                                    <div class="form-group">
                                        <select name="slt_carrera_profesional" size="5" class="form-control" id="slt_carrera_profesional"></select>
                                    </div>
                                    <div class="box">
                                        <div class="box-row">
                                            <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                                <div class="form-group"></div>
                                                <div class="form-group">
                                                    <center>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_carrera" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Agregar Carrera Profesional o Tecnica"><i class="fa fa-plus"></i></button>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_carrera" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Carrera Profesional o Tecnica"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                        <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_carrera" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Anular Carrera Profesional o Tecnica "><strong> <i class="fa fa-times"></i> </strong></button>

                                                    </center>
                                                </div>
                                                <div class="form-group"></div>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <center>
                                        </center>
                                    </div>

                                    <div class="col-xs-12">
                                        <span class="form-control bg-default">Carrera Profesional  : </span>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <select name="slt_carrera" disabled="disabled" id="slt_carrera" title="Carrera profesional ...." class="form-control"></select>
                                        </div>
                                    </div>



                                    <div class="col-xs-12">
                                        <span class="form-control bg-default">Colegio Profesional : </span>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <select name="slc_colegios_profesionales" size="25" id="slc_colegios_profesionales" class="form-control"></select>
                                            <span class="form-control bg-default">Nro. Colegiatura : </span>
                                            <input name="nro_colegiatura" type="text" disabled="disabled" class="form-control" id="nro_colegiatura" placeholder="Numero" value="S/N" maxlength="10">
                                        </div>
                                    </div>

                                    <center>
                                        <div class="col-xs-12">
                                            <span class="form-control bg-default">Habilidad  </span>
                                        </div>
                                    </center>
                                    <div class="col-xs-6">
                                        <span class="form-control bg-default">Emision : </span>
                                    </div>
                                    <div class="col-xs-6">
                                        <input name="fecha_inicio_habilitacion" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_inicio_habilitacion" title="Fecha de Inicio de Habilitacion" value="<?=date('d-m-Y')?>" readonly="readonly">
                                    </div>


                                    <div class="col-xs-6">
                                        <span class="form-control bg-default">Expira : </span>
                                    </div>
                                    <div class="col-xs-6">
                                        <input name="fecha_fin_habilitacion" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_fin_habilitacion" title="Fecha Fin de Habilitacion" value="<?=date('d-m-Y')?>" readonly="readonly">
                                    </div>


                                    <div class="col-xs-6">
                                        <span class="form-control bg-default">Nro : </span>
                                    </div>
                                    <div class="col-xs-6">
                                        <div class="form-group">
                                            <input name="nro_de_habilitacion" type="text" disabled="disabled" class="form-control" id="nro_de_habilitacion" title="Nro de Habilitacion" value="S/N">
                                        </div>
                                    </div>



                                    <div class="col-xs-12">

                                        <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_carrera" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Contrato"><span class="glyphicon glyphicon-ok"></span> Grabar</button>

                                    </div>


                                    <span id="espera_grabacion_carrera"></span>

                                    <?php for ( $i = 1; $i <= 5; $i++ ) {echo '<br>';}?>






                                </div>

                                    
                                    <!--- Fin de la carrera y colegio  --->

                                    
                                    
                                </div>
                            </div>
                        </div>






                        <!--- Inicio de FIN DE DATOS DE SERVICIO -->


                    </div>
                    <div id="cese_tercero" class="tab-pane fade">

                        <!--- Inicio de CESE -->

                        <div class="col-md-5">

                            <span class="form-control bg-default">&#9679; Personal :</span>
                            <span id="personal_seleccion_renuncia" class="form-control bg-info"></span>

                            <span class="form-control bg-default">Servicios Registrados : </span>
                            <div class="form-group">
                                <select name="slt_servicios" size="5" class="form-control" id="slt_servicios"></select>
                            </div>


                            <div class="box">
                                <div class="box-row">
                                    <div class="box-cell p-x-3 p-y-1 bg-default darken">
                                        <div class="form-group"></div>
                                        <div class="form-group">
                                            <center>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_agregar_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Registrar Cese"><i class="fa fa-plus"></i></button>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_modificar_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Modificar Cese"><strong> <i class="fa fa-pencil"></i></strong></button>
                                                <button class="btn btn-info  btn-lg crear-tooltip " id="btn_eliminar_cese" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Anular Cese"><strong> <i class="fa fa-times"></i> </strong></button>
                                            </center>
                                        </div>

                                        <div class="form-group"></div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-xs-12">
                                <span class="form-control bg-default">Motivos de Cese:</span>
                                <div class="form-group">
                                    <select name="slc_motivos_renuncia" id="slc_motivos_renuncia" class="form-control">
                                        <option id="0">Seleccione : </option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-6">
                                <span class="form-control bg-default">Fecha de Cese  : </span>
                            </div>
                            <div class="col-xs-6">
                                <div class="form-group">
                                    <input name="fecha_de_cese" type="text" disabled="disabled" class="form-control clsDatePicker" id="fecha_de_cese" title="Fecha ultimo dia de trabajo" value="<?=date('d-m-Y')?>" readonly="readonly">
                                </div>

                            </div>

                            <div class="col-xs-12">
                                <span class="form-control bg-default">Observacion :</span>
                                <div class="form-group">
                                    <textarea name="txt_observacion_renuncia" rows="3" disabled="disabled" id="txt_observacion_renuncia" class="form-control alert-warning  initialism"></textarea>
                                </div>

                            </div>

                            <button class="btn btn-info form-control  btn-lg crear-tooltip " id="btn_grabar_renuncia" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Grabar Registro"><span class="glyphicon glyphicon-ok"></span> Grabar</button>
                            <?php for ( $i = 1; $i <= 3; $i++ ) {echo '<br>';}?>

                            <span id="espera_grabacion_cese"></span>
                            <?php for ( $i = 1; $i <= 5; $i++ ) {echo '<br>';}?>



                        </div>



                        <!--- Fin de CESE --->

                    </div>

                </div>
            </div>

        </div>

        <!-- FIN DE PESTAÑAS DE DATOS BASICOS - LABORALES - CESE --->




    </div>







    <div id="result"></div>